### ISSUE TITLE
Unexpected behavior: successfully assigned address start to be unavailable

### ISSUE THREAD

**Issue by chief93** [metallb/metallb#628] opened 2020-06-11 17:04 UTC
Hi everyone! I've encountered weird behavior after about two months of active `MetalLB` using.

After a power-down of my host machine I've started the `Kubernetes` nodes, and all pods were successfully get up and running. But the pods of services, which obtained the broadcasted by `MetalLB` adresses started to get not routed: non access them by broadcasted IP and `Service`' port, non traceroute to them by theirs IP. In the logs of `MetalLB` everything is OK - no signs of any errors or so on. The `MetalLB` speakers are correctly connected to the `Mikrotik hAP`, as previously, but the routing seems to be broken.

The strangest thing is that previously all worked fine - even after a power down, the normally started pods were started to get working normally.

Mikrotik `Route` list, `BGP` table  and `Traceroute` results
![metallb1](https://user-images.githubusercontent.com/2089568/84412703-4a105b80-ac18-11ea-81ae-7e5cec76c727.PNG)
![metallb2](https://user-images.githubusercontent.com/2089568/84533026-04bf5d00-acf0-11ea-976f-d95118dafa0b.PNG)

Controller logs, related to app:
```
{"branch":"HEAD","caller":"main.go:142","commit":"v0.9.3","msg":"MetalLB controller starting version 0.9.3 (commit v0.9.3, branch HEAD)","ts":"2020-06-11T15:41:15.675559972Z","version":"0.9.3"}
{"caller":"main.go:108","configmap":"metallb-system/config","event":"startUpdate","msg":"start of config update","ts":"2020-06-11T15:41:15.899686114Z"}
{"caller":"main.go:121","configmap":"metallb-system/config","event":"endUpdate","msg":"end of config update","ts":"2020-06-11T15:41:15.899767781Z"}
{"caller":"k8s.go:402","configmap":"metallb-system/config","event":"configLoaded","msg":"config (re)loaded","ts":"2020-06-11T15:41:15.899794574Z"}
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:41:15.900368389Z"}
{"caller":"main.go:75","event":"noChange","msg":"service converged, no change","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:41:15.900500269Z"}
{"caller":"main.go:76","event":"endUpdate","msg":"end of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:41:15.900528825Z"}
{"caller":"main.go:49","event":"startUpdate","msg":"start of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T16:27:31.804992704Z"}
{"caller":"main.go:75","event":"noChange","msg":"service converged, no change","service":"netcount--production/netcount--production-service","ts":"2020-06-11T16:27:31.80510298Z"}
{"caller":"main.go:76","event":"endUpdate","msg":"end of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T16:27:31.805130213Z"}
```

One of the `Speaker` logs, related to app:
```
{"branch":"HEAD","caller":"main.go:82","commit":"v0.9.3","msg":"MetalLB speaker starting version 0.9.3 (commit v0.9.3, branch HEAD)","ts":"2020-06-11T15:42:07.308720864Z","version":"0.9.3"}
{"caller":"announcer.go:103","event":"createARPResponder","interface":"docker0","msg":"created ARP responder for interface","ts":"2020-06-11T15:42:07.311103871Z"}
{"caller":"announcer.go:103","event":"createARPResponder","interface":"kube-bridge","msg":"created ARP responder for interface","ts":"2020-06-11T15:42:07.311582161Z"}
{"caller":"announcer.go:112","event":"createNDPResponder","interface":"kube-bridge","msg":"created NDP responder for interface","ts":"2020-06-11T15:42:07.311939304Z"}
{"caller":"announcer.go:103","event":"createARPResponder","interface":"eth0","msg":"created ARP responder for interface","ts":"2020-06-11T15:42:07.313368488Z"}
{"caller":"announcer.go:112","event":"createNDPResponder","interface":"eth0","msg":"created NDP responder for interface","ts":"2020-06-11T15:42:07.313543575Z"}
{"caller":"main.go:186","msg":"Node event","node addr":"192.168.1.102","node event":"NodeJoin","node name":"s1-c3","ts":"2020-06-11T15:42:07.374780823Z"}
{"caller":"main.go:187","msg":"Call Force Sync","ts":"2020-06-11T15:42:07.374891515Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.103:7946","ts":"2020-06-11T15:42:07.575305728Z"}
{"caller":"main.go:202","component":"MemberList","msg":"state.go:1196: [WARN] memberlist: Refuting a dead message (from: s1-c3)","ts":"2020-06-11T15:42:07.576153738Z"}
{"caller":"main.go:186","msg":"Node event","node addr":"192.168.1.101","node event":"NodeJoin","node name":"s1-c2","ts":"2020-06-11T15:42:07.576449955Z"}
{"caller":"main.go:187","msg":"Call Force Sync","ts":"2020-06-11T15:42:07.576509584Z"}
{"caller":"main.go:186","msg":"Node event","node addr":"192.168.1.103","node event":"NodeJoin","node name":"s1-c4","ts":"2020-06-11T15:42:07.576546895Z"}
{"caller":"main.go:187","msg":"Call Force Sync","ts":"2020-06-11T15:42:07.576597379Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.101:7946","ts":"2020-06-11T15:42:07.576674912Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.102:7946","ts":"2020-06-11T15:42:07.57778855Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=192.168.1.102:59434","ts":"2020-06-11T15:42:07.578093332Z"}
{"caller":"main.go:163","error ?":null,"msg":"Memberlist join","nb joigned":3,"op":"startup","ts":"2020-06-11T15:42:07.675025141Z"}
{"caller":"main.go:386","configmap":"metallb-system/config","event":"startUpdate","msg":"start of config update","ts":"2020-06-11T15:42:08.07567656Z"}
{"caller":"bgp_controller.go:182","configmap":"metallb-system/config","event":"peerAdded","msg":"peer configured, starting BGP session","peer":"192.168.1.1","ts":"2020-06-11T15:42:08.0757342Z"}
{"caller":"main.go:410","configmap":"metallb-system/config","event":"endUpdate","msg":"end of config update","ts":"2020-06-11T15:42:08.075786643Z"}
{"caller":"k8s.go:402","configmap":"metallb-system/config","event":"configLoaded","msg":"config (re)loaded","ts":"2020-06-11T15:42:08.075804353Z"}
{"caller":"bgp_controller.go:232","event":"updatedAdvertisements","ip":"192.168.110.10","msg":"making advertisements using BGP","numAds":1,"pool":"default","protocol":"bgp","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:42:08.077749271Z"}
{"caller":"main.go:343","event":"serviceAnnounced","ip":"192.168.110.10","msg":"service has IP, announcing","pool":"default","protocol":"bgp","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:42:08.077818969Z"}
{"caller":"main.go:346","event":"endUpdate","msg":"end of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:42:08.07792216Z"}
{"caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"app-qr1demo-l7n-staging/app-qr1demo-l7n-staging-service","ts":"2020-06-11T15:42:08.077960444Z"}
{"caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:42:08.081327265Z"}
{"caller":"bgp_controller.go:232","event":"updatedAdvertisements","ip":"192.168.110.10","msg":"making advertisements using BGP","numAds":1,"pool":"default","protocol":"bgp","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:42:08.081357935Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.103:7946","ts":"2020-06-11T15:47:06.229197022Z"}
...
{"caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:47:08.360057234Z"}
{"caller":"bgp_controller.go:232","event":"updatedAdvertisements","ip":"192.168.110.10","msg":"making advertisements using BGP","numAds":1,"pool":"default","protocol":"bgp","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:47:08.360237638Z"}
{"caller":"main.go:343","event":"serviceAnnounced","ip":"192.168.110.10","msg":"service has IP, announcing","pool":"default","protocol":"bgp","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:47:08.360324036Z"}
{"caller":"main.go:346","event":"endUpdate","msg":"end of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:47:08.36039753Z"}
{"caller":"main.go:267","event":"startUpdate","msg":"start of service update","service":"netcount--production/netcount--production-service","ts":"2020-06-11T15:47:12.390420518Z"}
...
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=192.168.1.101:45686","ts":"2020-06-11T16:27:18.906431751Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:210: [DEBUG] memberlist: Stream connection from=192.168.1.103:58644","ts":"2020-06-11T16:27:29.389369316Z"}
{"caller":"main.go:202","component":"MemberList","msg":"net.go:785: [DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.103:7946","ts":"2020-06-11T16:27:36.405462997Z"}
...
```

App state in `Kubernetes Dashboard`:
![image](https://user-images.githubusercontent.com/2089568/84413384-387b8380-ac19-11ea-9f28-23cc690eb1e2.png)

The service itself can be accessed by IP of the node and autogenerated port `30332`, but is not accessed by `MetalLB` IP.

Kubernetes version: `1.18.1` (`1.18.3` same behavior)
MetalLB version: `0.9.3`
CNI: `kube-router`, latest
kube-proxy: not installed

**Comment by chief93** [comment] 2020-06-17 19:30
I have tested whole installation for all this time, and seems like something was broken in the MetalLB routing:
```
# traceroute 192.168.110.10
traceroute to 192.168.110.2 (192.168.110.10), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  0.563 ms  0.519 ms  0.498 ms
 2  192.168.1.103 (192.168.1.103)  1.231 ms  1.209 ms  1.185 ms
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  *^C
```

If I add my forced `ip route` rules, like:
```
# ip route add 192.168.110.0/24 via 10.244.1.1 kube-bridge
```
then in `traceroute` appear following line:
```
 3  s1-c3 (10.244.1.1)  3053.037 ms !H  3052.929 ms !H  3052.904 ms !H
```

Any ideas?

**Comment by chief93** [comment] 2020-06-17 20:00
One another note - I suspected that update of my Mikrotik was the problem, so I've restored the previous firmware, but with no success in solving this issue...

**Comment by russellb** [comment] 2020-06-17 20:18
I would suggest joining #metallb on Kubernetes slack to look for help with debugging your environment.

**Comment by chief93** [comment] 2020-06-18 07:27
Hi @russellb ! Thanks for advice, I'm already a member of Kubernetes Slack channel, but wanted previously to ask here.

**Comment by chief93** [comment] 2020-06-21 08:41
Seems like I've figured out what's going on - the problem indeed was not with `MetalLB`, but with my `Mikrotik` configuration. The main issue is that for `Mikrotik RoterOS` prior to `6.44` there was a need of following rules in `NAT` config:
![image](https://user-images.githubusercontent.com/2089568/85220235-8f6c2000-b3b2-11ea-9797-24566103d0a9.png)
But after the `6.47` (on which I updated right before current issue occurred), these `NAT` rules must be different (note the `defconf` rule, which also MUST be present for both cases):
![image](https://user-images.githubusercontent.com/2089568/85220281-d78b4280-b3b2-11ea-94ab-e688eb103d14.png)

Next, the issue sequence is clear:
1. after boot, the `MetalLB` tries to acquire the `BGP` peering with `Mikrotik`. The peering (from both sides!) is established, but the real traffic WILL NOT BE ROUTED, even after disabling the old rules (this can be the `Mikrotik` issue)
2. Additionally, any of the following rules, like
![image](https://user-images.githubusercontent.com/2089568/85220343-5b452f00-b3b3-11ea-85a1-30f17054058e.png)
will work incorrectly

The opened question is about `Mikrotik` "memorising" of incorrect behavior, even for manual `6.44` version installation (note, that I've tested this previously).

I'll continue to monitor the current state of whole installation, because it is very interesting, regardles of used technologies.

**Comment by chief93** [comment] 2020-06-21 08:53
Seems like I've figured out what's going on - the problem indeed was not with `MetalLB`, but with my `Mikrotik` configuration. The main issue is that for `Mikrotik RoterOS` prior to `6.45` there was a need of following rules in `NAT` config:
![image](https://user-images.githubusercontent.com/2089568/85220235-8f6c2000-b3b2-11ea-9797-24566103d0a9.png)
But after the `6.47` (on which I updated right before current issue occurred), these `NAT` rules must be different (note the `defconf` rule, which also MUST be present for both cases):
![image](https://user-images.githubusercontent.com/2089568/85220281-d78b4280-b3b2-11ea-94ab-e688eb103d14.png)
The `WAN` and `LAN` must be set in the `Out. interface list` selector, which is critical, because, as I said, prior to `6.45` the `LAN` was "emulated" by manual rules, specified above.

Next, the issue sequence is clear:
1. after boot, the `MetalLB` tries to acquire the `BGP` peering with `Mikrotik`. The peering (from both sides!) is established, but the real traffic WILL NOT BE ROUTED, even after disabling the old rules (this can be the `Mikrotik` issue)
2. Additionally, any of the following rules, like following (the `WAN` here is specified in `In. interface list`):
![metallb3](https://user-images.githubusercontent.com/2089568/85220602-9b0d1600-b3b5-11ea-83cf-20f32f72c71d.png)
will work incorrectly

The opened question is about `Mikrotik` "memorising" of incorrect behavior, even for manual `6.44` version installation (note, that I've tested this previously).

I'll continue to monitor the current state of whole installation, because it is very interesting, regardles of used technologies.

**Comment by johananl** [comment] 2020-06-22 11:52
@chief93 happy to hear you were able to figure out the problem. If you don't mind I'll close this as it doesn't sound like there is something to be done in MetalLB.

**Closed by johananl** 2020-06-22 11:52 UTC
Labels: protocol/BGP, question

**Comment by chief93** [comment] 2020-06-22 14:47
@johananl ok, but as I said, it strange fact that neither `MetalLB` nor `Mikrotik` noticed about routing problems, and even the `BGP` peering was established normally...

**Comment by johananl** [comment] 2020-06-22 15:26
@chief93 is there a way for me to reproduce the suspected bug? AFAIK when rebooting a speaker node or even an entire cluster, BGP converges as expected.

**Comment by chief93** [comment] 2020-06-22 20:15
@johananl sure you can, but I need to mention that this will require a bunch doze of preliminary steps:
1. Installing the `Mikrotik RouterOS` `6.44` in `VirtualBox`
2. Getting up the 3-node cluster (1 master, 2 workers)
3. Setup the `IPv4 NAT` like my first config (which, as I mentioned, worked for some time) in `Mikrotik`
4. Installing and configuring the `MetalLB` in `BGP` mode
5. Configuring the corresponding `BGP` Autonomous System on `Mikrotik`
6. Checking if `Service` with assigned by `MetalLB` address is available through network, managed by Mikrotik (at least, `traceroute`'ing to it)
7. upgrading it to the `6.47` (seems like there is also need to be a hardware reset by power down to changes take effect).
8. Checking the `Service` again: in described situation, the peering is established, the `Service` acquired the address from `MetalLB`, but it wasn't routed from `Mikrotik` network (in my case it's a real network of my home infrastructure)
9. And, of course, checking that applying of new `NAT` rules solves this problem (`Service` became available in the network)

But I'm not sure, that virtualized `RouterOS` will behave simillary like installed on a physical router (in my case it's `hAP AC`), and you also will need at least one another virtual machine, which emulate some physical host in `Mikrotik` network, for checking that `Service` really isn't available.

About rebooting - I tried it many times during debug, but with no success: rebooting the cluster nodes, rebooting the physical server, which hosts the cluster' nodes, rebooting the `Mikrotik` router, even within downgrading of the firmware.

I'm apreciated by your interest in solving this problem, because the "magical" solving of routing issue by disabling "wrong" `NAT` rules, then rebooting, then adding of the "correct" one is very weird... And I can help you with setup of such test environment, if you would like to check it.

**Comment by johananl** [comment] 2020-06-25 14:13
Thanks for the detailed info @chief93. To be honest this sounds to me like a highly specialized case, i.e. if there is a problem with BGP convergence in MetalLB I'd expect it to manifest itself using any router (as long as the Mikrotik stack doesn't do non-standard BGP stuff).

If someone is willing to take the time and create this environment for the sake of reproducing the suspected bug, I have no problem with that and will be happy to follow up with whatever fixes are necessary on the MetalLB side. However, since I'm not seeing similar reports from other community members, I'm kind of reluctant to spend more time on this as it is at the moment.

Again, it *could* be that there is a bug in MetalLB that is only ever triggered using Mikrotik with your specific config, but as you've said yourself this is unlikely. Therefore, I'd rather leave this issue be as long as we don't have a reason to believe the MetalLB code needs to be tweaked. Hope that's understandable.

**Comment by chief93** [comment] 2020-06-25 16:14
@johananl sure, thanks for detailed reply!
