### ISSUE TITLE
Update documentation on website with IP Address Sharing

### ISSUE THREAD

**Issue by lucasteligioridis** [metallb/metallb#2258] opened 2024-01-22 21:56 UTC
### Is your feature request related to a problem?

Documentation with the example over here:
https://metallb.universe.tf/usage/#ip-address-sharing

Is explaining an old issue if Kubernetes with multiple protocols on a single "LoadBalancer" type service, this has no longer been an issue since 1.24, so documentation just needs an update. Just needs a different example or something thats accurate now.
https://kubernetes.io/docs/concepts/services-networking/service/#load-balancers-with-mixed-protocol-types

This is a nit, just thought you might want a poke. :)

Sorry if this is the wrong location for this!

### Describe the solution you'd like

Docs updated!

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by clee** [comment] 2024-02-04 05:49
I think this is a dupe of #2100

**Closed** 2024-02-08 14:15 UTC
Labels: enhancement
