### ISSUE TITLE
Despite of removing the capabilities of speaker from metallb.yaml, service gets the external IP and also accessible using external IP

### ISSUE THREAD

**Issue by rahul-kr4604** [metallb/metallb#726] opened 2020-09-22 07:09 UTC
I have the removed the below added capabilities from speaker manifest mentioned in metallb.yaml:
```
capabilities:
            add:
            - NET_ADMIN             
            - NET_RAW               
            - SYS_ADMIN             
            drop:
            - ALL
```

After removal, I create a LoadBalancer service, which gets the IP and it is accessible using external IP.

Service:
```
$ oc get svc
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP      PORT(S)        AGE
nginx   LoadBalancer   172.30.80.168   192.168.200.90   80:30521/TCP   3m9s
[core@master0 ~]$ oc describe svc nginx
Name:                     nginx
Namespace:                metallb
Labels:                   <none>
Annotations:              Selector:  app=nginx
Type:                     LoadBalancer
IP:                       172.30.80.168
LoadBalancer Ingress:     192.168.200.90
Port:                     http  80/TCP
TargetPort:               8080/TCP
NodePort:                 http  30521/TCP
Endpoints:                10.131.0.8:8080,10.131.2.11:8080,10.131.2.45:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason        Age                   From                Message
  ----    ------        ----                  ----                -------
  Normal  IPAllocated   5m25s                 metallb-controller  Assigned IP "192.168.200.90"
  Normal  nodeAssigned  101s (x2 over 5m25s)  metallb-speaker     announcing from node "worker1.ocp4m.cluster.sub.nec.test"
```

As per my expectation after removal of these capabilities, though IP is allocated but service should not be accessible. As after removing the capabilities it will not be able to perform some networking configuration, which is required to access the service using external IP.

**Comment by russellb** [comment] 2020-09-22 15:11
Can you provide some more clear instructions on how to reproduce what you're talking about?  This sounds like just a misunderstanding of what capabilities metallb needs, and perhaps what capabilities you're granting.

**Comment by uablrek** [comment] 2020-09-24 05:26
If you use proxy-mode=ipvs the loadBalancer address will be assigned to `kube-ipvs0`;
```
ip addr show dev kube-ipvs0 
16: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 9a:4c:3b:69:4d:56 brd ff:ff:ff:ff:ff:ff
    inet 12.0.102.101/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 12.0.9.50/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 12.0.146.17/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 12.0.31.94/32 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
...
```
If you have "proxy arp" enabled linux will respond to arp requests for those addresses on other interfaces.

I think that is what's happening. I don't think this is a metallb fault. If you don't want the speaker function, then omit is entirely. Then if you still can access the load-balancer IP's it's surely not a metallb problem.

**Comment by rahul-kr4604** [comment] 2020-10-05 06:45
> Can you provide some more clear instructions on how to reproduce what you're talking about? This sounds like just a misunderstanding of what capabilities metallb needs, and perhaps what capabilities you're granting.

As per official manifest of metallb "metallb.yaml", the below capabilities are available to the speaker pod:

```
     capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL

```
After removing above capabilities I applied these changes, and configured Speaker with updated manifest.
After updating the Speaker, I created a LoadBalancer service which gets external IP and also accessible with that external IP.
Here my expectation is Speaker pod does not have any Capabilities so it will not be able to establish a dedicated route for external IP which results inaccessibility of service. 

If not so, then what is the relevance of these capability. 

**Steps to reproduce:**
1. Remove the capabilities of Speaker manifest from "[metallb.yaml](https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml)":
```
capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            drop:
            - ALL
```
2. Apply the changes:
```
$ oc apply -f metallb.yaml
podsecuritypolicy.policy/controller configured
podsecuritypolicy.policy/speaker configured
serviceaccount/controller unchanged
serviceaccount/speaker unchanged
clusterrole.rbac.authorization.k8s.io/metallb:controller unchanged
clusterrole.rbac.authorization.k8s.io/metallb:speaker unchanged
role.rbac.authorization.k8s.io/config-watcher unchanged
role.rbac.authorization.k8s.io/pod-lister unchanged
clusterrolebinding.rbac.authorization.k8s.io/metallb:controller unchanged
clusterrolebinding.rbac.authorization.k8s.io/metallb:speaker unchanged
rolebinding.rbac.authorization.k8s.io/config-watcher unchanged
rolebinding.rbac.authorization.k8s.io/pod-lister unchanged
daemonset.apps/speaker configured
deployment.apps/controller unchanged
```

3. Create the LoadBalancer service 
$ oc apply -f <service manifest file>

4. Get the service:
$ oc get svc <service-name>

5. Access the service using external IP from outside the cluster.

In my case service is accessible.

**Comment by rahul-kr4604** [comment] 2020-10-05 06:50
> If you use proxy-mode=ipvs the loadBalancer address will be assigned to `kube-ipvs0`;
> 
> ```
> ip addr show dev kube-ipvs0 
> 16: kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
>     link/ether 9a:4c:3b:69:4d:56 brd ff:ff:ff:ff:ff:ff
>     inet 12.0.102.101/32 scope global kube-ipvs0
>        valid_lft forever preferred_lft forever
>     inet 12.0.9.50/32 scope global kube-ipvs0
>        valid_lft forever preferred_lft forever
>     inet 12.0.146.17/32 scope global kube-ipvs0
>        valid_lft forever preferred_lft forever
>     inet 12.0.31.94/32 scope global kube-ipvs0
>        valid_lft forever preferred_lft forever
> ...
> ```
> 
> If you have "proxy arp" enabled linux will respond to arp requests for those addresses on other interfaces.
> 
> I think that is what's happening. I don't think this is a metallb fault. If you don't want the speaker function, then omit is entirely. Then if you still can access the load-balancer IP's it's surely not a metallb problem.

Here I'm using 'kube-proxy' in default mode 'iptables'.

As per your comment this is happening because "proxy arp", which is enabled by default. So what is the relevance of these capabilities of Speaker as per "[metallb.yaml](https://raw.githubusercontent.com/metallb/metallb/v0.9.3/manifests/metallb.yaml)"?

**Comment by uablrek** [comment] 2020-10-05 07:18
You should turn off proxy-arp if you have more than one node since _all_ nodes will respond. The node that gets the packets is random, and if it happens to work it's out of luck and it will inevitable fail at some point.

The metallb speaker in L2 mode ensures that only one node responds to arp, and also it supports ipv6 (neighbor discovery).

**Comment by russellb** [comment] 2021-05-24 21:47
it sounds like this conversation concluded, so i'm going to close this

**Closed by russellb** 2021-05-24 21:47 UTC
