### ISSUE TITLE
Lost speaker after network restart

### ISSUE THREAD

**Issue by duylong** [metallb/metallb#534] opened 2020-02-28 10:58 UTC
Hi,

Sometimes, when I restart my network (systemctl restart network), I lost speaker associated to my node. I must destroy the speaker in order to success again.

```
{"caller":"announcer.go:103","event":"createARPResponder","interface":"bond0.100","msg":"created ARP responder for interface","ts":"2020-02-27T14:35:03.618317007Z"}
{"caller":"announcer.go:112","event":"createNDPResponder","interface":"bond0.100","msg":"created NDP responder for interface","ts":"2020-02-27T14:35:03.61847568Z"}
{"caller":"announcer.go:103","event":"createARPResponder","interface":"bond0.101","msg":"created ARP responder for interface","ts":"2020-02-27T14:35:03.618797401Z"}
{"caller":"announcer.go:112","event":"createNDPResponder","interface":"bond0.101","msg":"created NDP responder for interface","ts":"2020-02-27T14:35:03.61894806Z"}
{"caller":"announcer.go:120","event":"deleteARPResponder","interface":"bond0.100","msg":"deleted ARP responder for interface","ts":"2020-02-27T14:35:03.629577351Z"}
{"caller":"announcer.go:120","event":"deleteARPResponder","interface":"bond0.101","msg":"deleted ARP responder for interface","ts":"2020-02-27T14:35:03.638527549Z"}
```

Network log:
```
systemd[1]: Stopping LSB: Bring up/down networking...
network[43142]: Interface shutdown bond0.100 :  [  OK  ]
network[43142]: Interface shutdown bond0.101 :  [  OK  ]
...
systemd[1]: Stopped LSB: Bring up/down networking.
systemd[1]: Starting LSB: Bring up/down networking...
...
network[44199]: Interface activation bond0.100 :  [  OK  ]
network[44199]: Interface activation bond0.101 :  [  OK  ]
...
systemd[1]: Started LSB: Bring up/down networking.
```

Is the problem known?

OS: RHEL7
MetalLB: 0.8.2

**Comment by russellb** [comment] 2020-08-06 18:07
Is this still problem for you?  Looking at the latest code, there is an infinite loop checking for the current list of active network interfaces every 10 seconds.  If the interfaces come back, i'd expect the arp responders to be recreated, as well.  This code hasn't changed in a long time, though (since before the release you're using).

**Comment by jokeyrhyme** [comment] 2022-03-08 05:59
Howdie, thanks so much for sharing this project, it has been very useful to me <3

I have a similar problem (perhaps the same problem), although I don't have logs from when it was last in an unexpected state (sorry, I'll share such logs next time I can reproduce this issue)

One thing I've noticed is that the metallb helm chart sets the liveness and readiness checks to use the Prometheus (?) endpoints:

```
Liveness:   http-get http://:monitoring/metrics delay=10s timeout=1s period=10s #success=1 #failure=3                                                             Readiness:  http-get http://:monitoring/metrics delay=10s timeout=1s period=10s #success=1 #failure=3          
```

However, setting up Prometheus happens right at the top of `func main()`: https://github.com/metallb/metallb/blob/main/speaker/main.go#L61

So, this combination means kubernetes will consider the container to be healthy as long as Prometheus and the instantiation of the k8s client doesn't instantly fail, but doesn't take into account whether the metallb-speaker is in a functioning state (i.e. actually able to make ARP / BGP operations that succeed in the intended outcome)

This makes sense for the liveness check, but I wonder if there's a more specific/thorough readiness check that we could expose that would help identify a faulty metallb-speaker early, and thus help k8s self-heal by restarting the container?

**Comment by fedepaol** [comment] 2024-04-12 10:15
Closing this as we did not hear back (nor others complained). Feel free to reopen if this happen again (or even better, file a new issue!)

**Closed by fedepaol** 2024-04-12 10:15 UTC
Labels: bug, protocol/layer2
