### ISSUE TITLE
Route advertisment fails when all available peers are added in the bgpadvertisment CR under peers

### ISSUE THREAD

**Issue by msyretis** [metallb/metallb#2113] opened 2023-10-12 13:20 UTC
### MetalLB Version

0.13.11

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

1.23 and 1.24

### Cluster Distribution

tkg

### Describe the bug

deploy metallb with the operator, crds, and frr.
create the cr for bgp peer, two peers, create the cr for advertisement, under the peers add both peers you created. 
Routes wont be advertised from none of the speakers to any of two peers
remove one of the peers under the advertisement cr, the routes are advertised by all speakers to the remaining peer.
remove both peers under the advertisement cr, the routes are advertised by all speakers to both peers.

### To Reproduce

deploy metallb with the operator, crds, and frr.
create the cr for bgp peer, two peers, create the cr for advertisement, under the peers add both peers you created. 
Routes wont be advertised from none of the speakers to any of two peers
remove one of the peers under the advertisement cr, the routes are advertised by all speakers to the remaining peer.
remove both peers under the advertisement cr, the routes are advertised by all speakers to both peers.

### Expected Behavior

I would expect if you have 2 peers, and you add both peers under the advertisement CR that routes will be advertised by both, rather than none

### Additional Context

I cannot pull the CR or logs, the environment is airgapped. I could potentially fudge it somehow, but it should be easy to reproduce.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment] 2023-10-13 08:22
Hey, I tried to reproduce this with the following setup:

Two bgp peers:

```
k get bgppeers -A
NAMESPACE        NAME    ADDRESS      ASN     BFD PROFILE   MULTI HOPS
metallb-system   peer    172.28.0.5   64512                 
metallb-system   peer1   172.30.0.3   64512 
```

A bgpadvertisement with a selector:

```
k get bgpadvertisement -A -o yaml
apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: BGPAdvertisement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"metallb.io/v1beta1","kind":"BGPAdvertisement","metadata":{"annotations":{},"name":"empty","namespace":"metallb-system"}}
    creationTimestamp: "2023-10-13T07:43:05Z"
    generation: 3
    name: empty
    namespace: metallb-system
    resourceVersion: "4181"
    uid: 0ae995ce-6033-476b-8b6e-1d6598e5d6e7
  spec:
    aggregationLength: 32
    aggregationLengthV6: 128
    peers:
    - peer
    - peer1
kind: List
metadata:
  resourceVersion: ""
```

A service

```
k get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1       <none>         443/TCP        37m
nginx        LoadBalancer   10.96.230.249   192.168.10.0   80:31951/TCP   12m
```

But both the frr configuration:

```
!                                                                                             
 address-family ipv4 unicast
  network 192.168.10.0/32
  neighbor 172.28.0.5 activate
  neighbor 172.28.0.5 route-map 172.28.0.5-in in
  neighbor 172.28.0.5 route-map 172.28.0.5-out out
  neighbor 172.30.0.3 activate
  neighbor 172.30.0.3 route-map 172.30.0.3-in in
  neighbor 172.30.0.3 route-map 172.30.0.3-out out
 exit-address-family

.....

ip prefix-list 172.28.0.5-pl-ipv4 seq 10 permit 192.168.10.0/32
ip prefix-list 172.30.0.3-pl-ipv4 seq 10 permit 192.168.10.0/32

```

and the status of the external frr

```
516df4df95b3# show bgp ipv4
BGP table version is 1, local router ID is 172.28.0.5, vrf id 0
Default local pref 100, local AS 64512
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

   Network          Next Hop            Metric LocPrf Weight Path
*=i192.168.10.0/32  172.28.0.3               0    100      0 i
*>i                 172.28.0.2               0    100      0 i
*=i                 172.28.0.4               0    100      0 i

Displayed  1 routes and 3 total paths
```

look fine to me. Are you able to reproduce this constantly on your side? Thanks!

**Comment by msyretis** [comment] 2023-10-13 09:36
Hi,

thanks for having a look. 


maybe it's my chart or my values then?
Can you use mine and see if it's happening?

it does not allow to attach the packaged chart, had to zip it. I left the values file that has the bgppeer and the advertisement.

[chart_and_values.zip](https://github.com/metallb/metallb/files/12892046/chart_and_values.zip)

**Comment by oribon** [comment] 2023-11-09 12:36
hey, sorry this took some time to answer. I believe the problem is in your chart - it seems that it doesn't parse the peers for the advertisements correctly, specifically the output of the advertisements under `helm template` is something like:
```yaml
# Source: metallb-crs/templates/bgpadvertisement.yaml
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: vrf1-summary-routes
  namespace: metallb-system
spec:
  aggregationLength: 29
  communities:
  - vrfone
  ipAddressPools:
  - vrf1-dynamic
  nodeSelectors:
  - matchLabels:
    
      nodepool: one
  peers: [globalbgppeer-en15 globalbgppeer-en16]
```
which k8s regards the peers as a single string instead of an array - when you run `kubectl get`:
```yaml
  kind: BGPAdvertisement
  metadata:
    name: vrf1-summary-routes
    namespace: metallb-system
  spec:
  ...
    peers:
    - globalbgppeer-en15 globalbgppeer-en16
```
I think yo need to fix `templates/bgpadvertisement.yaml` from:
```yaml
  peers: {{ $bgpadvertisements.peers }}
```
to:
```yaml
peers: {{ $bgpadvertisements.peers | toYaml | nindent 6 }}
```
and then it will render properly as:
```yaml
  peers: 
      - globalbgppeer-en15
      - globalbgppeer-en16
```

**Comment by msyretis** [comment] 2023-11-09 15:15
Hey, 
Amazing 👏. 
Thanks for taking the time. 

I will go fix my template and try again!

BR,
Mel

**Comment by fedepaol** [comment] 2023-12-01 15:04
Closing the issue, @msyretis please reopen if you still have some issues

**Closed by fedepaol** 2023-12-01 15:04 UTC
Labels: bug
