### ISSUE TITLE
After installing MetalLB in Kubernetes, there is an error timeout issue when reallocating IP pools

### ISSUE THREAD

**Issue by wh-zxt-01** [metallb/metallb#2599] opened 2024-11-21 01:59 UTC
### MetalLB Version

v0.14.0

### Deployment method

Charts

### Main CNI

calico

### Kubernetes Version

v1.31.2

### Describe the bug

After installing MetalLB, there is an error timeout issue when reallocating IP pools

### To Reproduce

**MetalLB was downloaded from GitHub and deployed using YAML and kubect app**
![1](https://github.com/user-attachments/assets/9cd59822-3574-4bdf-9520-093f249e67fc)
Normal startup completed ，But there was an error when reallocating the IP pool 
![2](https://github.com/user-attachments/assets/8a18de01-fc58-424f-9f48-9790b1263e1c)
```
kubectl apply -f metallb-config.yaml 
Error from server (InternalError): error when creating "metallb-config.yaml": Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://metallb-webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": context deadline exceeded
Error from server (InternalError): error when creating "metallb-config.yaml": Internal error occurred: failed calling webhook "l2advertisementvalidationwebhook.metallb.io": failed to call webhook: Post "https://metallb-webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-l2advertisement?timeout=10s": context deadline exceeded
```

### Expected Behavior

Successfully executed when allocating IP pool

### Additional Context

The operating system used is Ubuntu 22.04 , The IP address you want to allocate is also in the same network segment as the host computer

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment] 2024-11-21 08:21
Duplicate of https://github.com/metallb/metallb/issues/1597

**Closed** 2024-11-21 08:21 UTC
Labels: bug
