### ISSUE TITLE
Very frequent reloads in 0.13 causing high CPU usage

### ISSUE THREAD

**Issue by mac-chaffee** [metallb/metallb#1606] opened 2022-09-12 22:05 UTC
After upgrading from 0.12.1 to 0.13.5, I noticed very frequent reloads that caused CPU usage to spike which occasionally triggered failing probes and pod restarts (due to me setting the CPU limit to a low 100m).

These kinds of logs appear over and over again:

```
2022-09-12 17:30:07 {"caller":"config_controller.go:148","controller":"ConfigReconciler","end reconcile":"/k8s-node02","level":"info","ts":"2022-09-12T21:30:07Z"}
2022-09-12 17:30:07 {"caller":"config_controller.go:147","controller":"ConfigReconciler","event":"config reloaded","level":"info","ts":"2022-09-12T21:30:07Z"}
2022-09-12 17:30:07 {"caller":"config_controller.go:136","controller":"ConfigReconciler","event":"force service reload","level":"info","ts":"2022-09-12T21:30:07Z"}
2022-09-12 17:30:07 {"caller":"config_controller.go:48","controller":"ConfigReconciler","level":"info","start reconcile":"/k8s-node02","ts":"2022-09-12T21:30:07Z"}
2022-09-12 17:30:07 {"caller":"config_controller.go:148","controller":"ConfigReconciler","end reconcile":"/k8s-node10","level":"info","ts":"2022-09-12T21:30:07Z"}
2022-09-12 17:30:07 {"caller":"config_controller.go:147","controller":"ConfigReconciler","event":"config reloaded","level":"info","ts":"2022-09-12T21:30:07Z"}
2022-09-12 17:30:07 {"caller":"config_controller.go:136","controller":"ConfigReconciler","event":"force service reload","level":"info","ts":"2022-09-12T21:30:07Z"}
```

I've noticed a similar issue before, but never to this extent. My hunch is that something in my cluster frequently updates the `Node` objects because I can see the resourceVersion changing a lot. [Node Feature Discovery](https://github.com/kubernetes-sigs/node-feature-discovery/issues/805) is one thing that does this, although the behavior still occurred when I disabled NFD, so something else updates node objects frequently.

If MetalLB needs to do something when nodes change, it likely needs to check which fields changed rather than just always triggering the reload.

- Version of MetalLB: 0.13.5
- Version of Kubernetes: 1.23.7
- Name and version of network addon: Calico 3.22.3
- kube-proxy mode: ipvs

**Comment by fedepaol** [comment] 2022-09-13 07:17
Thanks for filing the issue! I am closing this as dupe of https://github.com/metallb/metallb/issues/1562
Looks like we need to cache the nodes and not process them unless something relevant changes.
cc @pperiyasamy

**Closed by fedepaol** 2022-09-13 07:17 UTC
