### ISSUE TITLE
MetalLB bgpadvertisementvalidationwebhook always reports pool prefix is more specific than aggregation length

### ISSUE THREAD

**Issue by Jeroen0494** [metallb/metallb#1538] opened 2022-07-27 10:45 UTC
Hi,

I'm facing the problem that no matter what subnet I set for my pools, and what aggregation length I set for BGP, the validation webhook always rejects my configuration.

MetalLB version 0.13.4
Kubernetes version 1.21.6

All values are testing values, actual working BGP is not required. I'm just testing resource creation.

Ansible setup:
```
[ -d ${PWD}/python-env ] && rm -rf ${PWD}/python-env
mkdir -p ${PWD}/python-env
python3 -m venv ${PWD}/python-env/ansible2.10

source ${PWD}/python-env/ansible2.10/bin/activate
pip install --upgrade pip setuptools
pip install --upgrade -r library/kubespray/requirements.txt
pip install openshift==0.13.1 markupsafe==2.0.1
ansible-galaxy collection install kubernetes.core
```

Pool creation
```
changed: [acc-jri-ot-k8sm001] => changed=true 
  invocation:
    module_args:
      api_key: null
      api_version: v1
      append_hash: false
      apply: false
      ca_cert: null
      client_cert: null
      client_key: null
      context: null
      delete_options: null
      force: false
      host: null
      kind: null
      kubeconfig: null
      merge_type: null
      name: null
      namespace: null
      password: null
      persist_config: null
      proxy: null
      resource_definition: |-
        # yamllint disable-file
        ---
  
        # Create all pools
  
        ---
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          namespace: "metallb-system"
          name: "primary"
        spec:
          addresses:
          - "172.18.113.167-172.18.113.169"
          autoAssign: True
          avoidBuggyIPs: true
  
  
        ---
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          namespace: "metallb-system"
          name: "pool1"
        spec:
          addresses:
          - "172.18.113.180/30"
          autoAssign: False
          avoidBuggyIPs: true
  
  
        ---
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          namespace: "metallb-system"
          name: "pool2"
        spec:
          addresses:
          - "172.18.113.184/30"
          autoAssign: False
          avoidBuggyIPs: true
      src: null
      state: present
      template: null
      username: null
      validate: null
      validate_certs: null
      wait: false
      wait_condition: null
      wait_sleep: 5
      wait_timeout: 120
  result:
    results:
    - changed: false
      diff: {}
      method: patch
      result:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          creationTimestamp: '2022-07-27T10:17:18Z'
          generation: 1
          managedFields:
          - apiVersion: metallb.io/v1beta1
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                .: {}
                f:addresses: {}
                f:autoAssign: {}
                f:avoidBuggyIPs: {}
            manager: OpenAPI-Generator
            operation: Update
            time: '2022-07-27T10:17:18Z'
          name: primary
          namespace: metallb-system
          resourceVersion: '25084640'
          uid: a5cdd260-f6ed-4f1d-8ddb-987898b91e89
        spec:
          addresses:
          - 172.18.113.167-172.18.113.169
          autoAssign: true
          avoidBuggyIPs: true
      warnings: []
    - changed: true
      diff:
        after:
          metadata:
            generation: 3
            resourceVersion: '25087328'
          spec:
            autoAssign: false
        before:
          metadata:
            generation: 2
            resourceVersion: '25084863'
          spec:
            autoAssign: true
      method: patch
      result:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          creationTimestamp: '2022-07-27T10:17:18Z'
          generation: 3
          managedFields:
          - apiVersion: metallb.io/v1beta1
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                .: {}
                f:addresses: {}
                f:autoAssign: {}
                f:avoidBuggyIPs: {}
            manager: OpenAPI-Generator
            operation: Update
            time: '2022-07-27T10:17:18Z'
          name: pool1
          namespace: metallb-system
          resourceVersion: '25087328'
          uid: b6f38c43-1071-4e7d-b501-b9dc7f7f0c36
        spec:
          addresses:
          - 172.18.113.180/30
          autoAssign: false
          avoidBuggyIPs: true
      warnings: []
    - changed: true
      diff:
        after:
          metadata:
            generation: 3
            resourceVersion: '25087329'
          spec:
            autoAssign: false
        before:
          metadata:
            generation: 2
            resourceVersion: '25084864'
          spec:
            autoAssign: true
      method: patch
      result:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          creationTimestamp: '2022-07-27T10:17:18Z'
          generation: 3
          managedFields:
          - apiVersion: metallb.io/v1beta1
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                .: {}
                f:addresses: {}
                f:autoAssign: {}
                f:avoidBuggyIPs: {}
            manager: OpenAPI-Generator
            operation: Update
            time: '2022-07-27T10:17:18Z'
          name: pool2
          namespace: metallb-system
          resourceVersion: '25087329'
          uid: 47c70f6b-7d74-4c2e-a1be-0820f81fb50a
        spec:
          addresses:
          - 172.18.113.184/30
          autoAssign: false
          avoidBuggyIPs: true
      warnings: []
```

layer2 configuration
```
ok: [acc-jri-ot-k8sm001] => changed=false 
  diff: {}
  invocation:
    module_args:
      api_key: null
      api_version: v1
      append_hash: false
      apply: false
      ca_cert: null
      client_cert: null
      client_key: null
      context: null
      delete_options: null
      force: false
      host: null
      kind: null
      kubeconfig: null
      merge_type: null
      name: null
      namespace: null
      password: null
      persist_config: null
      proxy: null
      resource_definition: |-
        # yamllint disable-file
        ---
  
        # Create layer2 configuration
  
        # L2 Configuration
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: "primary"
          namespace: "metallb-system"
        spec:
          ipAddressPools:
          - "primary"
      src: null
      state: present
      template: null
      username: null
      validate: null
      validate_certs: null
      wait: false
      wait_condition: null
      wait_sleep: 5
      wait_timeout: 120
  method: patch
  result:
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      creationTimestamp: '2022-07-26T09:33:25Z'
      generation: 1
      managedFields:
      - apiVersion: metallb.io/v1beta1
        fieldsType: FieldsV1
        fieldsV1:
          f:spec:
            .: {}
            f:ipAddressPools: {}
        manager: OpenAPI-Generator
        operation: Update
        time: '2022-07-26T09:33:25Z'
      name: primary
      namespace: metallb-system
      resourceVersion: '24889376'
      uid: e53b06c7-8c1b-4e8b-bc94-06164dba4424
    spec:
      ipAddressPools:
      - primary
```

layer3 configuration:
```
fatal: [acc-jri-ot-k8sm001]: FAILED! => changed=false 
  error: 403
  invocation:
    module_args:
      api_key: null
      api_version: v1
      append_hash: false
      apply: false
      ca_cert: null
      client_cert: null
      client_key: null
      context: null
      delete_options: null
      force: false
      host: null
      kind: null
      kubeconfig: null
      merge_type: null
      name: null
      namespace: null
      password: null
      persist_config: null
      proxy: null
      resource_definition: |-
        # yamllint disable-file
        ---
  
        # Create layer3 configuration
        ---
        apiVersion: metallb.io/v1beta1
        kind: Community
        metadata:
          name: "vpn-only"
          namespace: "metallb-system"
        spec:
          community:
          - name: "vpn-only"
            value: "1234:1"
  
        ---
        apiVersion: metallb.io/v1beta1
        kind: Community
        metadata:
          name: well-known
          namespace: "metallb-system"
        spec:
          community:
          - name: no-export
            value: 65535:65281
          - name: no-advertise
            value: 65535:65282
          - name: local-as
            value: 65535:65283
          - name: nopeer
            value: 65535:65284  
  
        # External BGP Advertisement. The IP range specified in the address pool is advertised to the BGP peer.
        ---
        apiVersion: metallb.io/v1beta1
        kind: BGPAdvertisement
        metadata:
          name: "peer1-external"
          namespace: "metallb-system"
        spec:
          ipAddressPools:
          - "pool1"
  
  
        # Configuration for the BGP peer.
        ---
        apiVersion: metallb.io/v1beta2
        kind: BGPPeer
        metadata:
          name: "peer1"
          namespace: "metallb-system"
        spec:
          myASN: 4200000000
          peerASN: 64512
          peerAddress: 172.18.113.162
  
          peerPort: 179
  
  
  
          holdTime: 120s
  
          keepaliveTime: 120s
  
  
  
  
        ---
        apiVersion: metallb.io/v1beta1
        kind: BGPAdvertisement
        metadata:
          name: "peer2-local"
          namespace: "metallb-system"
        spec:
          aggregationLength: 32
          communities:
          - no-advertise
          localpref: "100"
          ipAddressPools:
          - "pool2"
  
  
        # External BGP Advertisement. The IP range specified in the address pool is advertised to the BGP peer.
        ---
        apiVersion: metallb.io/v1beta1
        kind: BGPAdvertisement
        metadata:
          name: "peer2-external"
          namespace: "metallb-system"
        spec:
          aggregationLength: "30"
          ipAddressPools:
          - "pool2"
          communities:
          - "vpn-only"
  
  
        # Configuration for the BGP peer.
        ---
        apiVersion: metallb.io/v1beta2
        kind: BGPPeer
        metadata:
          name: "peer2"
          namespace: "metallb-system"
        spec:
          myASN: 4200000000
          peerASN: 64513
          peerAddress: 172.18.113.161
  
          peerPort: 179
  
          password: "changeme"
  
          routerID: "1.2.3.5"
  
          holdTime: 60s
  
          keepaliveTime: 60s
  
          ebgpMultiHop: "True"
      src: null
      state: present
      template: null
      username: null
      validate: null
      validate_certs: null
      wait: false
      wait_condition: null
      wait_sleep: 5
      wait_timeout: 120
  msg: 'Failed to patch object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \\"bgpadvertisementvalidationwebhook.metallb.io\\" denied the request: invalid aggregation length 24: prefix 30 in this pool is more specific than the aggregation length for addresses 172.18.113.180/30","reason":"invalid aggregation length 24: prefix 30 in this pool is more specific than the aggregation length for addresses 172.18.113.180/30","code":403}\n'''
  reason: Forbidden
  status: 403
```

**Comment by fedepaol** [comment] 2022-07-27 10:49
Thanks for reporting this, I'll try to reproduce and publish a fix

**Comment by fedepaol** [comment] 2022-07-27 10:57
Also, this is totally weird because the pool it's referring to is pool1 (172.18.113.180/30) whose bgpadvertisement (peer1-external) doesn't have any aggregation length specified.

Can you add here also the metallb resources present on the cluster (if any)? 
k get ipaddresspool -A -o yaml
k get bgpadvertisement -A -o yaml

**Comment by Jeroen0494** [comment] 2022-07-27 12:06
Hi,
Thank you for looking into this. It should be in the output above, but I can get you the output of those commands tomorrow.
I'm guessing there is some hard coded value in de validation webhook set to 24. I've also had this exact error message with pool1 when my BGP peer1-external does have the aggregation length set, no matter what value.

**Comment by fedepaol** [comment] 2022-07-27 12:25
> Hi, Thank you for looking into this. It should be in the output above, but I can get you the output of those commands tomorrow. I'm guessing there is some hard coded value in de validation webhook set to 24. I've also had this exact error message with pool1 when my BGP peer1-external does have the aggregation length set, no matter what value.

Yup, that was the first thing I checked, and I couldn't find any hardcoded value. I'll try to reproduce it myself too

**Comment by Jeroen0494** [comment] 2022-07-28 07:08
Here is the output:
```
$  k get ipaddresspool -A -o yaml
apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    creationTimestamp: "2022-07-27T10:17:18Z"
    generation: 3
    name: pool1
    namespace: metallb-system
    resourceVersion: "25087328"
    uid: b6f38c43-1071-4e7d-b501-b9dc7f7f0c36
  spec:
    addresses:
    - 172.18.113.180/30
    autoAssign: false
    avoidBuggyIPs: true
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    creationTimestamp: "2022-07-27T10:17:18Z"
    generation: 3
    name: pool2
    namespace: metallb-system
    resourceVersion: "25087329"
    uid: 47c70f6b-7d74-4c2e-a1be-0820f81fb50a
  spec:
    addresses:
    - 172.18.113.184/30
    autoAssign: false
    avoidBuggyIPs: true
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    creationTimestamp: "2022-07-27T10:17:18Z"
    generation: 1
    name: primary
    namespace: metallb-system
    resourceVersion: "25084640"
    uid: a5cdd260-f6ed-4f1d-8ddb-987898b91e89
  spec:
    addresses:
    - 172.18.113.167-172.18.113.169
    autoAssign: true
    avoidBuggyIPs: true
kind: List
metadata:
  resourceVersion: ""

$  k get bgpadvertisement -A -o yaml
apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: BGPAdvertisement
  metadata:
    creationTimestamp: "2022-07-26T09:52:31Z"
    generation: 1
    name: peer1-external
    namespace: metallb-system
    resourceVersion: "24892075"
    uid: 81502585-163d-4cda-9944-8dbd86a56869
  spec:
    aggregationLength: 24
    aggregationLengthV6: 128
    ipAddressPools:
    - pool1
- apiVersion: metallb.io/v1beta1
  kind: BGPAdvertisement
  metadata:
    creationTimestamp: "2022-07-26T09:40:59Z"
    generation: 1
    name: peer1-local
    namespace: metallb-system
    resourceVersion: "24890535"
    uid: 7a3616ca-98cb-4990-9562-31fd02cced84
  spec:
    aggregationLength: 32
    aggregationLengthV6: 128
    communities:
    - vpn-only
    ipAddressPools:
    - pool1
kind: List
metadata:
  resourceVersion: ""

$  k get Community -A -o yaml
apiVersion: v1
items:
- apiVersion: metallb.io/v1beta1
  kind: Community
  metadata:
    creationTimestamp: "2022-07-26T09:40:09Z"
    generation: 1
    name: no-advertise
    namespace: metallb-system
    resourceVersion: "24890418"
    uid: 6cc30760-ae50-447f-93df-c0b98fcb6974
  spec: {}
- apiVersion: metallb.io/v1beta1
  kind: Community
  metadata:
    creationTimestamp: "2022-07-26T09:38:09Z"
    generation: 1
    name: vpn-only
    namespace: metallb-system
    resourceVersion: "24890152"
    uid: 4ce14768-8d15-4d4f-a273-bf53a8a0ecb1
  spec: {}
- apiVersion: metallb.io/v1beta1
  kind: Community
  metadata:
    creationTimestamp: "2022-07-27T10:17:20Z"
    generation: 1
    name: well-known
    namespace: metallb-system
    resourceVersion: "25084654"
    uid: f575f053-62e3-47b1-a54d-058d8c7e7d4f
  spec: {}
kind: List
metadata:
  resourceVersion: ""
```

**Comment by Jeroen0494** [comment] 2022-08-17 10:01
@fedepaol have you had success replication this issue?

**Comment by fedepaol** [comment] 2022-09-01 12:39
Sorry for the delay.
I _think_ I found the issue.
You already have an incompatible couple in your config:

```
- apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    creationTimestamp: "2022-07-27T10:17:18Z"
    generation: 3
    name: pool1
    namespace: metallb-system
    resourceVersion: "25087328"
    uid: b6f38c43-1071-4e7d-b501-b9dc7f7f0c36
  spec:
    addresses:
    - 172.18.113.180/30
    autoAssign: false
    avoidBuggyIPs: true
```

and 

```
- apiVersion: metallb.io/v1beta1
  kind: BGPAdvertisement
  metadata:
    creationTimestamp: "2022-07-26T09:52:31Z"
    generation: 1
    name: peer1-external
    namespace: metallb-system
    resourceVersion: "24892075"
    uid: 81502585-163d-4cda-9944-8dbd86a56869
  spec:
    aggregationLength: 24
    aggregationLengthV6: 128
    ipAddressPools:
    - pool1
```

and this ^^^ is where the /24 is coming from.
This should've been blocked by the webhook, but they were probably created with a sequence that escaped the webhooks (i.e. I see now that creating the advertisement BEFORE the pool would've make it pass).

Then, when we add a new bgpadvertisement, the validation is done against all the existing advertisements (plus the newly added) and the existing addresspools to check incompatibilities, hence the refusal.

I am gonna close this issue and open a new one to:
- change the error message so it's clear which advertisement and which advertisements are incompatible
- enforce the pool validation webhook to comprehend also the advertisements

**Closed by fedepaol** 2022-09-01 12:39 UTC
Labels: bug

**Comment by Jeroen0494** [comment] 2022-09-02 12:43
Ah, interesting. I'll perform a new test in the coming days to verify your findings.
