### ISSUE TITLE
Is it possible to deploy multiple controllers

### ISSUE THREAD

**Issue by fan1emon** [metallb/metallb#2276] opened 2024-02-05 02:27 UTC
### Is your feature request related to a problem?

The operations manager told me that I must start more than 1 instances to avoid single points of failure.

### Describe the solution you'd like

Introducing a leader selection mechanism like Kube-Scheduler?

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by fedepaol** [comment] 2024-02-05 09:54
This is a dupe of https://github.com/metallb/metallb/issues/2216 . Please have a look at the motivations provided there.
Closing the issue

**Closed by fedepaol** 2024-02-05 09:54 UTC
Labels: enhancement
