### ISSUE TITLE
Metallb on openstack based kubernetes cluster

### ISSUE THREAD

**Issue by deep7710** [metallb/metallb#536] opened 2020-03-04 06:46 UTC
I Have kubernetes cluster deployed on openstack. have deployed metallb and all works fine. Extrernal IP is also assigned. But the problem is i am unable to access nginx running behind external IP outside the kubernetes cluster.
i can curl http://externalip:8080/ inside the k8s cluster and get response, But not outside the cluster from other nodes.
k8s - 1.16.0
cni - calico
Using layer 2 protocol in metallb

documention talks about disabling arp spoofing but not sure how to do it.
Any help would be appreciated.

**Comment by elgamal2020** [comment] 2020-03-21 06:06
Same problem

**Comment by rata** [comment] 2020-03-23 03:34
If it's routed inside the cluster using the assigned IP, I guess the problem is not in metalLB but in the network setup to route traffic to that IP from outside?

Can you explain in more detail why this might be a bug in metalLB and not in other parts of the network setup you are using? If you need help debugging, please join slack and close the issue :)

**Comment by elgamal2020** [comment] 2020-03-23 03:46
Acutally it works when I have disabled anti spoofing for those ip on the openstack 

Ex: openstack port set 5662a4e0-e646-47f0-bf88-d80fbd2d99ef --allowed-address ip-address=10.233.0.0/18 --allowed-address ip-address=10.233.64.0/18

**Comment by elgamal2020** [comment] 2020-03-23 03:47
but for the curl on the port , still I cant ping this IP , it seems that metllb is only working on layer 4 , is that correct ?

**Comment by rata** [comment] 2020-03-23 04:12
Yes, if iptables mode (at least). MetalLB depends on kube-proxy for routing, and in iptables mode it only routes protol+port specified in the service.

ICMP is left out of the picture by kube-proxy in iptables mode, at least. Can you confirm this is in iptables mode? And, if so, is this issue closed? :)

**Comment by elgamal2020** [comment] 2020-03-23 05:01
Yes it is iptable , actually my setup is microk8s with metallb addson over openstack 

So ticket can be closed , I would like to ask you if you can guide me to a more explenation document about metallb function in both iptables and ipvs modes , we want to rely on it extensively and we would like to understand it

**Comment by rata** [comment] 2020-03-23 14:34
@elgamal2020 but which configuration did you added in openstack exactly? Can you please share?

**Comment by rata** [comment] 2020-05-04 13:46
IIUC this is what is mentioned here: https://metallb.universe.tf/installation/clouds/#metallb-on-openstack. If something is missing, please don't hesitate to re-open.

**Closed by rata** 2020-05-04 13:46 UTC

**Comment by wsoualhi** [comment] 2023-07-23 19:55
@deep7710, could you please share the steps to deploy Metallb on a Kubernetes cluster on Openstack ? I used layer2 protocol, and I created a dummy port associated with a floating IP as recommended here :  https://github.com/metallb/metallb/issues/486, but it didn't work for me.
Many thanks !

**Comment by Alixpat** [comment] 2024-09-01 17:59
This works well for me on Openstack with a microk8s cluster. Have you considered the L2Advertisement?

**Comment by mohsenasm** [comment] 2025-03-01 12:36
Same problem. 

> I can curl http://externalip:8080/ inside the k8s cluster and get response, But not outside the cluster from other nodes.


No luck with:
- Using a dummy port
- Not using a dummy port
- Disabling `Port Security`
- Configuring allowed address
- Using the Layer 2 mode 

It would be much appreciated if someone could share a working configuration.
