### ISSUE TITLE
L2 mode doesn't resend gratuitous arp when node is diconnected and reconnected

### ISSUE THREAD

**Issue by liuyuan10** [metallb/metallb#584] opened 2020-04-15 03:07 UTC
If the master node is disconnected for some time, another node will start to announce as the master. But after the original master node is reconnected, it doesn't resend gratuitous arp because it doesn't think it ever lose mastership. But now it's in a inconsistent state where traffic still go through the 2nd master because gratuitous arp is not sent. This inconsistent state may take a long time due to ongoing traffic with wrong MAC refreshing gateway arp table.

Shall we consider sending garp all the time instead of only the first 5 seconds?

     - Version of MetalLB v0.9.3
     - Version of Kubernetes v1.15
     - Name and version of network addon (e.g. Calico, Weave...) calico
     - Whether you've configured kube-proxy for iptables or ipvs mode iptable

**Comment by champtar** [comment] 2020-04-15 03:23
Hello @liuyuan10 
Are you using memberlist ?

**Comment by champtar** [comment] 2020-04-15 03:33
Let's say we have API and B C D workers, service S, with pod on B and C
Everything runs fine, B is announcing the IP for service S
Now B is cut from the network (can't talk to API or C / D) but still running, C now announces the IP for service S
B comes back online before the pods on B change status on the API side, so when running the sync loop there is nothing to sync, so no gratuitous ARP are sent
@liuyuan10 is it something like that ?

=> maybe we should force gratuitous ARP each time there is a memberlist change ?

**Comment by liuyuan10** [comment] 2020-04-15 05:10
Yes. It's exactly what you described.

=> maybe we should force gratuitous ARP each time there is a memberlist
change ?
Is it still correct to only send garp on node join?

**Comment by rata** [comment] 2020-04-15 14:56
> Is it still correct to only send garp on node join?

@liuyuan10  Do you observe a node-join in your clusters? I thought it is just a small glitch, maybe the node was not even marked as "not ready".

> => maybe we should force gratuitous ARP each time there is a memberlist change ?
 
@champtar definitely something to take a look, specially if we know the announcing node for a service changed :-)

**Comment by liuyuan10** [comment] 2020-04-15 16:09
On Wed, Apr 15, 2020 at 7:57 AM rata <notifications@github.com> wrote:

> Is it still correct to only send garp on node join?
>
> @liuyuan10 <https://github.com/liuyuan10> Do you observe a node-join in
> your clusters? I thought it is just a small glitch, maybe the node was not
> even marked as "not ready".
>
The node is still ready in k8s. Yes there is a node join after the node is
reconnected again.

**Comment by rata** [comment] 2020-05-04 15:42
@champtar Thanks for the PR!

I think the issue is: we don't really know if we need to send the gratious ARP or not. We have the memberlist source of truth and k8s api source of truth and not mixing that info in any way.

In any case, I don't think [what was described](https://github.com/metallb/metallb/issues/584#issuecomment-613796278) can happen. But let me know if I'm missing something (I might try to reproduce this later, but I think looking at the PR #595 might be more important to fix it there). Quoting the example:

> Let's say we have API and B C D workers, service S, with pod on B and C
> Everything runs fine, B is announcing the IP for service S
> Now B is cut from the network (can't talk to API or C / D) but still running, C now announces the IP > for service S

This next step is what I think is wrong in the current code-base:
> B comes back online before the pods on B change status on the API side, so when running the sync loop there is nothing to sync, so no gratuitous ARP are sent

When B comes back online again, it doesn't join the memberlist (PR https://github.com/metallb/metallb/pull/595 tries to address that, though). So, the master node will still be C and announced by C. No issues now in that situation (except that B will be out of the memberlist and not usable if C goes down, etc.).

That the node doesn't join the memberlist is of course unintended, and when it does joing, this issue will happen will happen, IIUC.

**Comment by rata** [comment] 2020-05-07 23:22
@liuyuan10 can you please confirm if you can reproduce [this][link] with memberlist disabled too?

Maybe I'm is too tired to think correctly, but I think it should happen too.

[link]: https://github.com/metallb/metallb/issues/584#issue-599985362

**Comment by champtar** [comment] 2020-05-08 00:28
@rata it's not impossible but it's way harder to hit without MemberList I think:
1) disconnect a node advertising an ip
2) wait until it becomes notready, another node will start advertising
3) reconnect the node, have the kubelet talk to the API and put everything in ready state before the speaker talk to the API and get the not ready info foe the service he was advertising

**Comment by liuyuan10** [comment] 2020-05-08 03:19
Yes. as said, it all depends on if the node has become ready when the speaker reprocess all the services. There is a race condition there so it might not be reproduced from testing

**Comment by rata** [comment] 2020-08-20 09:41
Some things to take into account when solving this:

* We don't want to send ARP too much, as that can break routers (https://github.com/metallb/metallb/pull/595#discussion_r434891401)
* We just want to recover *after* a split brain, it doesn't really matters that some nodes announce the same IP during a split brain or similar. This is the behavior before memberlist too (and in fact, a decided trade-off that I think is mentioned in some issue).

There are several ways to fix this. There was some discussion about different ideas on this thread: https://github.com/metallb/metallb/pull/595#discussion_r434781491 and on slack. That PR has the fix from @champtar that, IMHO, seems too complicated and sending the ARP unconditionally there defeats the purpose of not wanting to spam and all the code that is already present to only announce the IP once.

@russellb What I say there is basically what I said to you the other day. I think an easy way to solve it is just re-announce if we are masters and the `usableNodes()` changed. We would need to store the `usableNodes()` that we aren't storing right now, though. I haven't tried to do this change, but I _hope_ it is possible as it sounds in my mind :-D. 

There might be other ideas, of course. Don't restrict yourself to these if you think of a better way :)

**Comment by johananl** [comment] 2020-10-02 18:48
Let me try to summarize the status of this issue.

As far as I can tell, we have 3 implementations with the following statuses:

- https://github.com/metallb/metallb/pull/595
  - The implementation is complicated (according to @rata). I admit this PR is hard to digest for me, too, and I think that the fact we couldn't either close or merge it after >200 comments is strongly suggesting an alternative implementation is in order.
  - GARP is sent more than necessary (according to @rata).
- https://github.com/metallb/metallb/pull/709
  - Has a potential race condition.
- https://github.com/metallb/metallb/pull/730
  - Has a risk of sending too much ARP traffic.

@rata and I have discussed this offline and would like to move forward with #709 as follows:

- Verify the race condition described [here](https://github.com/metallb/metallb/pull/709#discussion_r490961070) indeed occurs and understand **how likely** it is to occur.
- Measure the **impact** when the race condition *does* occur. For example, we should be able to say "every time this condition occurs the user sees a downtime of up to 40 seconds".
- Merge #709 unless we realize doing so will make the layer 2 behavior worse compared to what we already have in `v0.9.3`.

The rationale for the plan above is that right now the user sees the same behavior as they would in the suspected race condition **all the time**. This means that even if the race condition is frequent, #709 still looks like an improvement over `v0.9.3` because it will make convergence faster at least *some* of the time.

I will look into the race condition matter and comment with some more data so that we can decide if we should merge #709.

We are reluctant to adopt #730 because spamming ARP messages excessively does look like a more serious problem compared to improving the convergence time only in *some* cases, and in addition the ARP spam problem could be an issue regardless of network partitions, which is a regression we would like to avoid.

Lastly, I'd like to remind that we have the opportunity to re-evaluate this entire functionality in a minor release where we can introduce better designs (e.g. using the k8s API). Our primary focus here should be to converge on *something* and get https://github.com/metallb/metallb/milestone/9 released.

**Comment by champtar** [comment] 2020-10-02 19:39
In #595 we send less ARP than in #709, and we can't send less GARP without using the API to have true consistency.
#595 contains a full refactor of memberlist + a reasonably sized fix for this. You are confusing both and that is why you think it's too complicated.

Merging know buggy code (with known race condition) when working code (according to my tests at least) is written is hard to understand for me.
Please focus on #662 first, merge it, then we can discuss solution for this bug.

I've offered in the past to have a call to explain all of that, rata was not available (which is totaly fine), but reading a sumup of offline discussion and decision based on misconception upset me a bit.

**Comment by champtar** [comment] 2020-10-02 21:33
See #736, it's around the same size as #709, has no race conditions, and spam less.

**Comment by russellb** [comment] 2020-10-09 17:49
We now have #736 as a candidate PR to consider.  In short, I prefer it to mine (#709).

I find @champtar's approach to be a nice compromise between #709 and #730.  

* #730 would GARP far too often in some cases.  
* #709 tries to be really clever and do additional GARP in a particular scenario, but possibly too clever and leaves some races open.
* #736 is closer to #730 in terms of when it triggers GARP, but includes some rate limiting.  It won't run the GARP procedure multiple times for the same IP at the same time, in particular.  This is really what made #730 unworkable.

My current opinion would be to merge #736 at the conclusion of code review.  I've been reviewing it and @champtar is providing quick updates.

**Comment by johananl** [comment] 2020-10-09 17:50
Thanks @champtar and @russellb. I am reviewing #736 as we speak.

**Comment by johananl** [comment] 2020-10-09 18:34
Left some nits on #736. I am leaning strongly towards merging #736 to get things moving. If we catch more issues down the road we will fix them then.

@rata if you're available for a quick review I'll wait a bit. Otherwise I'd like to merge once the current feedback is handled.

**Closed** 2020-10-14 17:44 UTC
Labels: bug, protocol/layer2
