### ISSUE TITLE
Can't access MetalLB IPs from nodes

### ISSUE THREAD

**Issue by Slyke** [metallb/metallb#932] opened 2021-08-24 06:55 UTC
When accessing the service from outside the cluster from somewhere else on my LAN, everything works fine. For some reason none of  the nodes running the services can communicate with the service's external IP.

I've setup LB on K8s, using the same config as K3s.

metallb-config.yml:
```
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.7.7.10-10.7.7.254
```
And these:
 * https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml
 * https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml

arping ran from master:
```
$ while ! nc -w 1 10.7.arping -I eno1 10.7.7.14
ARPING 10.7.7.14 from 10.7.50.11 eno1
Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.063ms
Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.259ms
Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.085ms
Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.103ms
```

tcpdump from node running the pod the service connects to:
```
$ sudo tcpdump -n -i enp3s0 arp src host 10.7.7.14
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
06:47:23.845200 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
06:47:24.845179 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
06:47:25.845214 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
06:47:26.845272 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
```

nc run from a machine on my LAN:
```
$ while ! nc -w 1 10.7.7.14 80 ; do echo "Attemptign to contact Service"; sleep 1; done; echo "Contacted Service"
Contacted Service
```
The service also works fine (it's a webapp).

The same command run from the master or any of the worker nodes:
```
$ while ! nc -w 1 10.7.7.14 80 ; do echo "Attemptign to contact Service"; sleep 1; done; echo "Contacted Service"
Attemptign to contact Service
Attemptign to contact Service
```

Not sure if this is some sort of bug, because the exact same setup did work on my K3s instance.

**Comment by fedepaol** [comment] 2021-09-03 14:14
> When accessing the service from outside the cluster from somewhere else on my LAN, everything works fine. For some reason none of the nodes running the services can communicate with the service's external IP.
> 
> I've setup LB on K8s, using the same config as K3s.
> 
> metallb-config.yml:
> 
> ```
> apiVersion: v1
> kind: ConfigMap
> metadata:
>     namespace: metallb-system
>     name: config
> data:
>   config: |
>     address-pools:
>     - name: default
>       protocol: layer2
>       addresses:
>       - 10.7.7.10-10.7.7.254
> ```
> 
> And these:
> 
>     * https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/metallb.yaml
> 
>     * https://raw.githubusercontent.com/metallb/metallb/v0.9.6/manifests/namespace.yaml
> 
> 
> arping ran from master:
> 
> ```
> $ while ! nc -w 1 10.7.arping -I eno1 10.7.7.14
> ARPING 10.7.7.14 from 10.7.50.11 eno1
> Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.063ms
> Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.259ms
> Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.085ms
> Unicast reply from 10.7.7.14 [00:E8:4C:68:68:B8]  1.103ms
> ```
> 
> tcpdump from node running the pod the service connects to:
> 
> ```
> $ sudo tcpdump -n -i enp3s0 arp src host 10.7.7.14
> tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
> listening on enp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
> 06:47:23.845200 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
> 06:47:24.845179 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
> 06:47:25.845214 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
> 06:47:26.845272 ARP, Reply 10.7.7.14 is-at 00:e8:4c:68:68:b8, length 46
> ```
> 
> nc run from a machine on my LAN:
> 
> ```
> $ while ! nc -w 1 10.7.7.14 80 ; do echo "Attemptign to contact Service"; sleep 1; done; echo "Contacted Service"
> Contacted Service
> ```
> 
> The service also works fine (it's a webapp).
> 
> The same command run from the master or any of the worker nodes:
> 
> ```
> $ while ! nc -w 1 10.7.7.14 80 ; do echo "Attemptign to contact Service"; sleep 1; done; echo "Contacted Service"
> Attemptign to contact Service
> Attemptign to contact Service
> ```
> 
> Not sure if this is some sort of bug, because the exact same setup did work on my K3s instance.

If I got this right, ARPPing works from master but nc does not.
MetalLB is only responsible for getting the traffic to the node. Once there, it's a matter of the SDN of choice to drive the traffic to the right pod.
It could be that there's logic in place to accept only traffic from outside. You could rule metallb out of the equation by setting the loadBalancerIP field on the service and removing metallb, and setting a static route to the node hosting the backend. External traffic should still work.

**Comment by fedepaol** [comment] 2021-09-10 16:17
As described above, this is not a MetalLB issue. Closing this.

**Closed by fedepaol** 2021-09-10 16:17 UTC

**Comment by seumasdunlop** [comment] 2022-07-19 05:47
Hi @fedepaol,  I believe I'm seeing the same issue and would appreciate some clarifcation on whether it is expected behaviour.

In my case I can only access the virtual IP from within the cluster from pods running on the same node as the active listener.  All the nodes have the virtual IP configured on them so ping from a pod never has to leave the node and always works.  However, only the active node will accept a TCP connection to the virtual IP.  This is fine from outside the cluster because only the active node responds to arp requests but from within the cluster other nodes never need to make an arp request because they already have the virtual IP configured (on the kube-ipvs0 interface in my example).

In the following examples :
- 192.168.40.240 - the virtual IP created by metallb
- 192.168.40.228 - the kubernetes node that is active for that virtual IP
- 192.168.40.226 - a second kubernetes node

Example 1 - working from a pod running on node 192.168.40.228
```
root@ubuntu-deployment-7bcf4467dd-spplw:/# curl -k https://192.168.40.240
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
root@ubuntu-deployment-7bcf4467dd-spplw:/# traceroute 192.168.40.228
traceroute to 192.168.40.228 (192.168.40.228), 64 hops max
  1   192.168.40.228  0.004ms  0.002ms  0.002ms
root@ubuntu-deployment-7bcf4467dd-spplw:/# traceroute 192.168.40.226
traceroute to 192.168.40.226 (192.168.40.226), 64 hops max
  1   192.168.40.228  0.001ms  0.001ms  0.000ms
  2   192.168.40.226  0.350ms  0.300ms  0.284ms
root@ubuntu-deployment-7bcf4467dd-spplw:/# traceroute 192.168.40.240
traceroute to 192.168.40.240 (192.168.40.240), 64 hops max
  1   192.168.40.240  0.002ms  0.000ms  0.001ms
```

Example 2 - not working from a pod running on node 192.168.40.226
```
root@ubuntu-deployment-7bcf4467dd-vhpmt:/# curl -k https://192.168.40.240
curl: (7) Failed to connect to 192.168.40.240 port 443 after 0 ms: Connection refused
root@ubuntu-deployment-7bcf4467dd-vhpmt:/# traceroute 192.168.40.226
traceroute to 192.168.40.226 (192.168.40.226), 64 hops max
  1   192.168.40.226  0.003ms  0.001ms  0.000ms
root@ubuntu-deployment-7bcf4467dd-vhpmt:/# traceroute 192.168.40.228
traceroute to 192.168.40.228 (192.168.40.228), 64 hops max
  1   192.168.40.226  0.006ms  0.005ms  0.002ms
  2   192.168.40.228  0.395ms  0.326ms  0.345ms
root@ubuntu-deployment-7bcf4467dd-vhpmt:/# traceroute 192.168.40.240
traceroute to 192.168.40.240 (192.168.40.240), 64 hops max
  1   192.168.40.240  0.002ms  0.001ms  0.001ms
```

Please let me know if you'd prefer a new issue.
