### ISSUE TITLE
Share Public IP with multiple services

### ISSUE THREAD

**Issue by mseewooth** [metallb/metallb#679] opened 2020-07-23 06:39 UTC
I have a two vps with only public IP addresses.  167.XXX as master and 207.XX as worker . 

Kubernete version is v1.18.6
MetallB version : v0.9.3 
Flannel network : https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 

This the metallb configmap : 

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 207.XXX.XXX.XXX-207.XXX.XXX.XXX
```
Please note that the ip range in the Configmap is like this e.g  `192.168.100.20-192.168.100.20`  . I  have a single public ip and my vps does not have private ip addresses. i had to assign the public ip itself in the pool on the configmap manifest.
  
 i have deployed a service `selector` to a deployment (`vhost`) which consist a vhost red.nginx.com like below : 

```
apiVersion: v1
kind: Service
metadata:
  name: vhost
  namespace: test
  annotations:
    metallb.universe.tf/allow-shared-ip: 207.XX.X.XX
  labels:
    app: vhost
spec:
  type: LoadBalancer
  loadBalancerIP: 207.XXX.X.X
  selector:
    app: vhost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-test
```

```
kubectl get svc -n test
NAME    TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)        AGE
vhost   LoadBalancer   10.102.116.194   207.XXX.X.X   80:31070/TCP   16s

```

Now i'm trying to deploy another service ` selector` to deployment (`vhosttest`) consisting a vhost blue.nginx.com: 

```
apiVersion: v1
kind: Service
metadata:
  name: vhosttest
  namespace: test
  annotations:
    metallb.universe.tf/allow-shared-ip: 207.XXX.XXX
  labels:
    app: vhosttest
spec:
  type: LoadBalancer
  loadBalancerIP: 207.XXX.XXX
  selector:
    app: vhosttest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-test

```

```
kubectl get svc -n test 
NAME        TYPE           CLUSTER-IP       EXTERNAL-IP       PORT(S)        AGE
vhost       LoadBalancer   10.102.116.194   207.XX.XX.X   80:31070/TCP   6m53s
vhosttest   LoadBalancer   10.102.241.105   <pending>         80:31250/TCP   3s
```

I'm not getting the ip address  `207.xx.x.xx`  shared with the `svc vhosttest`

If this option is not possible, this mean that you can only have one service pointing to single deployment. 

I want to do something like this : 

```
                     METALLB  207.XX.XX.XX
                                         |
                                         |
                  ---------------------------
                 |                                             |
   svc  vhost ip 207.xx.xx.xx        svc  vhosttest  ip 207.xx.xx.xx
       (selector=vhost)                    (selector=vhosttest)
                 |                                             |
            deployment                       deployment
        ( selector= vhost)         (selector=vhostest)
```

In this approach which is a simple, i i can have several apps(websites) on a single IP. 

Please let know if this is possible or a solution how to get the public ip share across multiple services.

Thanks

**Comment by Aoana** [comment] 2020-07-23 10:49
Hi!

I believe the reason the VIP is kept in pending is because your services are using the same port (port=80).

You cannot share a VIP among two k8s services of type:loadbalancer using same port. The layer4 loadbalancing taking place in k8s (implemented by kubeproxy) cannot differentiate between the two in that case.

What you want to achieve is in most cases solved by an Ingress Controller with an Ingress Resource, as this can perform layer7 loadbalancing taking a vhost into account. The Ingress Controller would be assigned the VIP in that case and the two backends deployed as type:ClusterIP.

Another solution is to expose the second service over different port (port 8080 or something), but that might not be what you want. It can however be tested to prove this being the root cause.

Sidenote: The allow-shared-ip annotation can be any string and using the VIP for that purpose could a bit non-dynamic depending on the deployment scenarios.

Best Regards
Anders

**Comment by mseewooth** [comment] 2020-07-23 11:51
Hi @Aoana  , thanks a bunch, i knew layer 4 was for TCP but never knew service type:Loadbalancer is at the layer 4. 

Is a service type:LoadBalancer by default a Layer 4 ? Or its the metallb which makes it act as Layer 4  ?  

I made the test by replacing the vhosttest  service port to 8080 . And  yes ,  both services now have got the ip shared.

But in my case , i would be adding ingress controller for doing the layer 7 loadBalancing . 

One very important question before i proceed, as i know in GCP an ip is provisioned to the ingress controller automatically. 
My case is a baremetal. Will Metallb provide the Nginx/Traefik  Ingress controller the ip 207.XX.XX.XX ? If not , is there a way if this ? 

Thank you

**Comment by mseewooth** [comment] 2020-07-23 12:52
Hi @Aoana  , i couldnt wait, i went to install the nginx ingress followed my metallb and the services in cluster ip . 

damn , telnet responded on port 80 . As well as the nginx minikube i used,  its doing the layer 7 loadbalancing as well. Obviously am gonna try traefik and haproxy as well :D 

Damn thats gr8 metallb is the one that provided the VIP to the ingress .. thats amazing gr8 

Thank you very much for your help

**Comment by Aoana** [comment] 2020-07-23 13:59
Hi!

Yes, a plain kubernetes service of type: Loadbalancer is layer4. It can be TCP, UDP (or SCTP, but SCTP is not available by default and is in pre-alpha).
When using an Ingress Controller to manage HTTP, the protocol will of course be TCP. 

Metallb assigns a VIP but its not involved in the internal loadbalancing which is managed by kubeproxy (k8s process). There is no notion of http headers when kubeproxy performs its loabalancing in vanilla k8s.

So with the scope that Metallb have today, metallb cannot "redefine" what a type:Loadbalancer means in k8s, and this is how Metallb is designed.

Best Regards
Anders

**Comment by mseewooth** [comment] 2020-07-23 15:59
Hello, 

Thanks for this. Its clear enough now.  But i come to know another problem :(  . Client source Ip is not being logged with service type:ClusterIP.

**Comment by Aoana** [comment] 2020-07-23 16:32
Hi!

Great that you got answers to your Metallb related questions. 

I suggest you close this ticket as your current problem has nothing to do with Metallb.

Good luck!
Anders

**Closed** 2020-07-23 16:34 UTC
