### ISSUE TITLE
Controller Leader Election

### ISSUE THREAD

**Issue by abmybgx** [metallb/metallb#2629] opened 2024-12-09 09:28 UTC
### MetalLB Version

0.14.8

### Deployment method

Charts

### Main CNI

kube-ovn

### Describe the bug

When I scaled the controller to multiple pods for HA, I noticed that there was no leader election mechanism between the pods. This led to a small chance of conflicts causing failures when multiple controllers simultaneously worked to update a LoadBalancer Service.

### To Reproduce

1. scaled the controller to multiple pods
2. apply too many lb service at the same time 

### Expected Behavior

Only one controller works at any given time.

### Additional Context

no

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment] 2024-12-09 10:05
This is a dupe of https://github.com/metallb/metallb/issues/2216 . Please have a look at the motivations provided there.
Closing the issue

**Closed by fedepaol** 2024-12-09 10:05 UTC
Labels: bug
