### ISSUE TITLE
Official installation guide installs v.0.8.2 instead of v0.8.3

### ISSUE THREAD

**Issue by mekstrem** [metallb/metallb#543] opened 2020-03-17 10:16 UTC
### Problem

The official [installation guide](https://metallb.universe.tf/installation/) installs v0.8.2 in the manifest even if it the manifest link in the guide points to tag v0.8.3 on Github.

### Solution

Update the manifest and change from v0.8.2 to v0.8.3.

**Comment by nielsbasjes** [comment] 2020-03-18 13:01
I noticed the same thing today.

I had a look and as far as I can tell the problem is in the https://github.com/metallb/metallb/blob/v0.8.3/manifests/metallb.yaml which has been tagged as v0.8.3 (tags should be immutable) yet contains
    image: metallb/speaker:v0.8.2

If I look at the branch v0.8  (which is mutable) 
https://github.com/metallb/metallb/blob/v0.8/manifests/metallb.yaml
then that does contain the desired v0.8.3

So I cannot create a fix against the tag (which has this problem) and I can create a fix against the branch ... which is already correct.

**Comment by rata** [comment] 2020-03-20 18:17
I think the fix should be to release 0.8.4 without changes, just tagged correctly.

I'm working in a new release (0.9.0), I can look at this later :)

**Comment by rata** [comment] 2020-03-24 00:59
[MetalLB v0.9.3](https://metallb.universe.tf/release-notes/#version-0-9-3) was just released (in fact, probably the same bug affected v0.9.2). Thanks for the report! :-)

Do you have any need for us to release 0.8.4 just fixing the manifests? (the bug in the release script is [fixed here](https://github.com/metallb/metallb/commit/9094482fa09be46ab6b085768ca2552e91929982)).

**Comment by rata** [comment] 2020-04-11 00:05
@mekstrem friendly ping?

**Comment by nielsbasjes** [comment] 2020-04-11 06:46
For me this solution is fine.

**Comment by mekstrem** [comment] 2020-04-11 08:41
This is fine for me +1

Mvh
Mikko Ekström

**Comment by rata** [comment] 2020-04-12 00:52
Release 0.9.3 is fine? Cool, closing then. Thanks again for the report! And do not hesitate to open more bugs or re-open if I misunderstood :)

**Closed by rata** 2020-04-12 00:52 UTC
Labels: bug
