### ISSUE TITLE
controller assigns IP ignoring L2adv. rules

### ISSUE THREAD

**Issue by dberardo-com** [metallb/metallb#2068] opened 2023-09-07 08:10 UTC
### MetalLB Version

0.13.5

### Deployment method

Manifests

### Main CNI

flannel

### Kubernetes Version

1.27

### Cluster Distribution

k3s

### Describe the bug

currently using 2 ip pools and 2 load balancer services in L2 mode. 
1 ip pool works fine and the ip is correctly announced via the speaker, which is "behaving" by the rules defined in an L2assingment object.

the second ip pool however, does not behave as it should, in fact the ip is not announced by any speaker, but directly assigned by the controller, with log: "IP address assigned by controller", on the wrong node (node not include in node selector constraints)

the question is: how to avoid direct assignment by the controller ?

### To Reproduce

no idea

### Expected Behavior

speakers should announce ips, not controller

### Additional Context

.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment] 2023-09-07 08:14
Can you share your full config and the definition of the services?
The controller ALWAYS assignes the IP to the service, the speaker chooses to announce it or not.
It's not totally clear what the problem is. Is that the service is not being announced? Or that it's being annoucned from the wrong node?

**Comment by dberardo-com** [comment] 2023-09-07 08:19
both services get the IP, but one of them is announced on the wrong node... despite L2Advertisement rules using nodeSelector to prevent that.

> The controller ALWAYS assignes the IP to the service, the speaker chooses to announce it or not.

in the case of the first IP (the one correctly assigned), i see that the IP is not logged in the controller container, but only in one of the speaker announcing them. As for the seocnd IP, none of the speakers announces it, and it is the only IP logged in the controller logs ... i would expect both the IPs to pop up in the controller log, right ?

**Comment by dberardo-com** [comment] 2023-09-07 08:20
also: can a speaker announce more than 1 ip at the same time ? maybe thats the issue here

**Comment by fedepaol** [comment] 2023-09-07 08:21
> also: can a speaker announce more than 1 ip at the same time ? maybe thats the issue here

yes, it can (otherwise we'd be limited by the number of nodes).
Please provide the configuration and the logs as the item you checked above: 

I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue

 I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by dberardo-com** [comment] 2023-09-07 08:40
there you go ... i had to censor our some private info:
[report.zip](https://github.com/metallb/metallb/files/12546698/report.zip)

**Comment by cyclinder** [comment] 2023-09-08 03:49
Can you use the following command to collect information?

- kubectl describe svc <wrong_service_name> ?
- kubectl logs -n metallb-system <wrong_ announce_node>?
- kubectl get nodes -l <L2Advertisement_nodeSelector> ?

**Comment by dberardo-com** [comment] 2023-09-11 16:23
now is too late :-/ 
i rebooted the nodes and everything it seems  to work again. (i did try to remove the pods before rebooting but that was not helpful) sorry that i cant provide any more logs ..

**Comment by fedepaol** [comment] 2023-09-19 07:22
closing this as non reproducible.
Feel free to reopen if you manage to collect the logs

**Closed by fedepaol** 2023-09-19 07:22 UTC
Labels: bug
