### ISSUE TITLE
Port is already in use and LoadBalancer IP stays on pending

### ISSUE THREAD

**Issue by Atomique** [metallb/metallb#1704] opened 2022-11-11 15:06 UTC
Hi, 

I tried to check first if this is a troubleshooting-issue on the kubernetes slack channel #metallb. @fedepaol asked me to open up this issue because he thinks that this could be related to his request: https://github.com/metallb/metallb/pull/1647 

For someone interested into the talk about this: https://kubernetes.slack.com/archives/C8FSTGU56/p1668004924746339 

Here are informations about my systems and versions: 

"If you're reporting a bug, please specify all of the following:"
     - Version of MetalLB: App-Version v0.13.7, Helm-Chart Version: metallb-0.13.7
     - Version of Kubernetes: 1.24.6
     - Name and version of network addon (e.g. Calico, Weave...): Calico / Tigera-Operator App-Version v3.24.2, Helm-Chart Version: tigera-operator-v3.24.2
     - Whether you've configured kube-proxy for iptables or ipvs mode: ipvs-mode configured

The bug itself, as detailed as you can: 

I have a problem with a "burned" port in metallb and I wonder how I can solve this problem:
I have deployed metallb via helm:

```
$ helm ls
NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
metallb metallb-system  1               2022-10-27 18:28:51.791122504 +0200 CEST        deployed        metallb-0.13.7  v0.13.7
```

I rebooted my nodes and my services (not all) went into "pending":
```
$ kubectl get svc -A | grep Load

app-prod         app-debug                                      LoadBalancer   10.110.91.64     <pending>      21009:30794/TCP                       36s
app-prod         app-monit                                      LoadBalancer   10.109.71.115    <pending>      22009:32509/TCP                       36s
app-prod         app-web                                        LoadBalancer   10.106.161.151   <pending>      20009:31766/TCP                       36s
app-prod         mariadb                                        LoadBalancer   10.109.47.151    <pending>      20009:32333/TCP                       36s
```

after that I checked the logs of the controller
```
[metallb-controller.log](https://github.com/metallb/metallb/files/9991107/metallb-controller.log)

W1109 13:50:26.459581       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool                                                                                                                 ││ {"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/app-web","ts":"2022-11-09T13:54:26Z"}                                                                                  ││ {"caller":"service.go:140","error":"port TCP/20009 is already in use on \"10.23.19.112\"","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2022-11-09T13:54:26Z"}                                                   ││ {"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/app-web","level":"info","ts":"2022-11-09T13:54:26Z"}                                                                                   ││ {"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/mariadb","ts":"2022-11-09T13:54:26Z"}                                                                                    ││ {"caller":"service.go:140","error":"port TCP/20009 is already in use on \"10.23.19.113\"","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2022-11-09T13:54:26Z"}                                                   ││ {"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/mariadb","level":"info","ts":"2022-11-09T13:54:26Z"}                                                                                     ││ {"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/app-debug","ts":"2022-11-09T13:54:26Z"}                                                                                ││ {"caller":"service.go:140","error":"port TCP/21009 is already in use on \"10.23.19.112\"","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2022-11-09T13:54:26Z"}                                                   ││ {"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/app-debug","level":"info","ts":"2022-11-09T13:54:26Z"}                                                                                 ││ {"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/app-monit","ts":"2022-11-09T13:54:26Z"}                                                                                ││ {"caller":"service.go:140","error":"port TCP/22009 is already in use on \"10.23.19.112\"","level":"error","msg":"IP allocation failed","op":"allocateIPs","ts":"2022-11-09T13:54:26Z"}                                                   ││ {"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"default/app-monit","level":"info","ts":"2022-11-09T13:54:26Z"}
```

The only solution I had was to change the ports to another port. But I wasnt able to get it working again with this port. Deleting and re-applying the Services didnt help.
Can anyone help me out with this? Can I see used ports with something like a CLI or something similar? And second question: How can I prevent the deprecation warning? I already deployed the pool with IPAddressPool and there is no addresspool in my namespace metallb-system.

I have also attached the controller logs (after restarting it). 

Thanks a lot for your help! Please let me know if I can assist you with more information.

**Comment by fedepaol** [comment] 2022-11-24 13:15
Hi @Atomique , I don't see the controller logs anymore so it _might_ be that gh has some file retention policy. Would you be so kind to re-attach them? Thanks!

**Comment by Atomique** [comment] 2022-12-06 08:34
Hi @fedepaol 

here are my cleaned logs (removed sensible information, if something is unclear, let me know)

[metallb_controllerlogs_20221206.txt](https://github.com/metallb/metallb/files/10164251/metallb_controllerlogs_20221206.txt)

Thanks a lot for your help!

**Comment by fedepaol** [comment] 2022-12-06 17:53
What I can see from the logs is you have one service on the default ns consuming the same port:

```
{"kind":"Service","apiVersion":"v1","metadata":{"name":"appname-web","namespace":"default","uid":"3149e235-3aab-4e26-ba40-292961027041","resourceVersion":"158792373","creationTimestamp":"2022-11-09T13:54:26Z","labels":{"app":"appname"},"annotations":{"field.cattle.io/publicEndpoints":"[{\"addresses\":[\"10.23.19.112\"],\"port\":20009,\"protocol\":\"TCP\",\"serviceName\":\"default:appname-web\",\"allNodes\":false}]","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"metallb.universe.tf/allow-shared-ip\":\"rqcmqhrA82UeTCVu\"},\"labels\":{\"app\":\"appname\"},\"name\":\"appname-web\",\"namespace\":\"default\"},\"spec\":{\"loadBalancerIP\":\"10.23.19.112\",\"ports\":[{\"name\":\"appname-web\",\"port\":20009,\"protocol\":\"TCP\",\"targetPort\":45605}],\"selector\":{\"app\":\"appname\"},\"type\":\"LoadBalancer\"}}\\n","metallb.universe.tf/allow-shared-ip":"rqcmqhrA82UeTCVu"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"v1","time":"2022-11-09T13:54:26Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:metallb.universe.tf/allow-shared-ip":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:loadBalancerIP":{},"f:ports":{".":{},"k:{\"port\":20009,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}}},{"manager":"agent","operation":"Update","apiVersion":"v1","time":"2022-12-06T08:27:49Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:field.cattle.io/publicEndpoints":{}}}}},{"manager":"controller","operation":"Update","apiVersion":"v1","time":"2022-12-06T08:27:49Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:loadBalancer":{"f:ingress":{}}}},"subresource":"status"}]},"spec":{"ports":[{"name":"appname-web","protocol":"TCP","port":20009,"targetPort":45605,"nodePort":32290}],"selector":{"app":"appname"},"clusterIP":"10.111.199.246","clusterIPs":["10.111.199.246"],"type":"LoadBalancer","sessionAffinity":"None","loadBalancerIP":"10.23.19.112","externalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","allocateLoadBalancerNodePorts":true,"internalTrafficPolicy":"Cluster"},"status":{"loadBalancer":{"ingress":[{"ip":"10.23.19.112"}]}}}

{"kind":"Service","apiVersion":"v1","metadata":{"name":"appname-web","namespace":"customer1-restore-cluster3-02","uid":"729ff4a1-e64b-4530-9406-8687896b970e","resourceVersion":"158792374","creationTimestamp":"2022-10-31T14:32:27Z","labels":{"app":"appname"},"annotations":{"field.cattle.io/publicEndpoints":"null","kubectl.kubernetes.io/last-applied-configuration":"{\\"apiVersion\\":\\"v1\\",\\"kind\\":\\"Service\\",\\"metadata\\":{\\"annotations\\":{\\"metallb.universe.tf/allow-shared-ip\\":\\"rqcmqhrA82UeTCVu\\"},\\"labels\\":{\\"app\\":\\"appname\\"},\\"name\\":\\"appname-web\\",\\"namespace\\":\\"appname-customer1-prod\\"},\\"spec\\":{\\"loadBalancerIP\\":\\"10.23.19.112\\",\\"ports\\":[{\\"name\\":\\"appname-web\\",\\"port\\":20009,\\"protocol\\":\\"TCP\\",\\"targetPort\\":45605}],\\"selector\\":{\\"app\\":\\"appname\\"},\\"type\\":\\"LoadBalancer\\"}}\\n","metallb.universe.tf/allow-shared-ip":"rqcmqhrA82UeTCVu"},"managedFields":[{"manager":"agent","operation":"Update","apiVersion":"v1","time":"2022-10-31T14:32:27Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:field.cattle.io/publicEndpoints":{}}}}},{"manager":"executor-server","operation":"Update","apiVersion":"v1","time":"2022-10-31T14:32:27Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:metallb.universe.tf/allow-shared-ip":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ipFamilies":{},"f:ipFamilyPolicy":{},"f:loadBalancerIP":{},"f:ports":{".":{},"k:{\\"port\\":20009,\\"protocol\\":\\"TCP\\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}}}]},"spec":{"ports":[{"name":"appname-web","protocol":"TCP","port":20009,"targetPort":45605,"nodePort":32578}],"selector":{"app":"appname"},"clusterIP":"10.102.192.196","clusterIPs":["10.102.192.196"],"type":"LoadBalancer","sessionAffinity":"None","loadBalancerIP":"10.23.19.112","externalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","allocateLoadBalancerNodePorts":true,"internalTrafficPolicy":"Cluster"},"status":{"loadBalancer":{}}}

```

So metallb is complaining because both services can't share the same port.

**Comment by fedepaol** [comment] 2022-12-20 11:17
Closing this as I suspect it's the root cause. Feel free to reopen otherwise.

**Comment by Atomique** [comment] 2022-12-22 15:08
Hey @fedepaol - sorry for being this late. Missed to answer! 
I created this port after the problem came up to test it out. Thats why this is mentioned in the logs so it wasnt used twice at the root cause.

**Comment by fedepaol** [comment] 2022-12-22 15:25
but I see it being there right after the controller restart. If you are able to reproduce it without this extra service, please provide the new logs. I'll reopen the issue in the meanwhile

**Comment by Atomique** [comment] 2022-12-22 15:37
Yes, you asked me to gather some new logs and I restarted it to generate new logs for you! 

I need to delete the test-service and restart the controller. I hope I can do this today - I am on vacation at the moment 

Thanks a lot for reopening the issue!

**Comment by fedepaol** [comment] 2022-12-22 15:38
Yep but this time the poor controller's complaint is legit!

**Comment by Atomique** [comment] 2022-12-22 16:59
I dont think so: 

- At first I was told I cant use the port
- after that I changed the original service to a new port to get the production running fast
- Then I created the test-service with the „burned“ port for testing
- I opened up this issue / the request on slack 
- At last I restarted the controller to regather the logs

thats the history of tasks I did in the past

**Comment by fedepaol** [comment] 2022-12-23 14:22
yes I didn't want to say you are not hitting a proper problem. I am just saying that in the lst log you added, the dupe port is caused by two services really sharing the same port.

**Comment by Atomique** [comment] 2023-01-16 08:46
Hi @fedepaol , 
I deleted the testservice and readded the services with the exact same port and IP (but different namespace, I dont want to affect prod again) and I didn't had any issues again. Seems like everything works fine now. Thats a bit weired and makes me afraid of reoccuring again. 

I am sure that the port and the IP were free BEFORE applying the config / restarting. Is there something like a cache that could have made this kind of problems? 

Thanks a lot for your patience and help (also in slack, really nice). 

Have a nice day!

**Comment by fedepaol** [comment] 2023-01-16 08:48
No worries, and thanks for taking the time to follow this up!
I am going to close the issue, if it reoccurs please ping me on slack and we'll look at it again!

**Closed by fedepaol** 2023-01-16 08:48 UTC
