### ISSUE TITLE
I have questions!  Is 0.8.3 your latest version of MetalLB with a release date of 10/30/2019?  Do you happen to have a release schedule that you follow? I see your dates for old releases but don't see anything about following a certain schedule for new releases. If you have anything to provide that would be great.

### ISSUE THREAD

**Issue by kthurs** [metallb/metallb#508] opened 2019-12-16 18:33 UTC
Thanks for filing an issue! A few things before we get started:

1. This is not the place to ask for troubleshooting. Unfortunately
   troubleshooting LB issues in k8s takes a lot of time and effort
   that we simply don't have. If your load-balancers aren't working,
   please don't file an issue unless you have identified a _specific_
   bug to fix. Otherwise, please ask for help in the `#metallb`
   channel on the Kubernetes Slack.
2. Please search the bug tracker for duplicates before filing your
   bug.
3. If you're reporting a bug, please specify all of the following:
     - The bug itself, as detailed as you can.
     - Version of MetalLB
     - Version of Kubernetes
     - Name and version of network addon (e.g. Calico, Weave...)
     - Whether you've configured kube-proxy for iptables or ipvs mode

**Comment by adampl** [comment] 2020-01-03 20:43
@kthurs This issue looks like you created it accidentally while writing #515. Please close it.

**Comment by rata** [comment] 2020-03-23 03:12
Closing as duplicate of the mentioned issue

**Closed by rata** 2020-03-23 03:12 UTC
