### ISSUE TITLE
possible issue with metallb_speaker_announced metric and speaker node switching

### ISSUE THREAD

**Issue by ksyblast** [metallb/metallb#1972] opened 2023-06-06 16:21 UTC
Summary:
We are using metallb in ARP mode. We have noticed that when an active speaker announcing IP address has changed to another node (e.g. previous speaker pod was deleted) the old speaker node still returns metallb_speaker_announced for this service in the metrics. In other words,  after the new election is done the previously elected node still returns metallb_speaker_announced in the metrics. At the same time we have ensured there is no split brain and only one node actually responds to ARP.

However metrics in prometheus are the following:
```
metallb_speaker_announced{instance="k8s-worker1.example.com", ip="1.2.3.4", job="k8s_speaker", kubernetes_io_cluster="k8s", kubernetes_io_hostname="k8s-worker1", node="k8s-worker1", protocol="layer2", service="default/apache-1677160163"}
metallb_speaker_announced{instance="k8s-worker2.example.com", ip="1.2.3.4", job="k8s_speaker", kubernetes_io_cluster="k8s", kubernetes_io_hostname="k8s-worker2", node="k8s-worker2", protocol="layer2", service="default/apache-1677160163"}
metallb_speaker_announced{instance="k8s-worker3.example.com", ip="1.2.3.4", job="k8s_speaker", kubernetes_io_cluster="k8s", kubernetes_io_hostname="k8s-worker3", node="k8s-worker3", protocol="layer2", service="default/apache-1677160163"}
```

Version of MetalLB: 1.12.1
Version of Kubernetes: v1.25.6
Name and version of network addon: Calico
Whether you've configured kube-proxy for iptables or ipvs mode: iptables

Steps to reproduce:
Normally it's sufficient to delete the speaker pod which is "active" (announcing) for the service. I could also reproduce it with
```
kubectl rollout restart -n metallb-system daemonset speaker
````
Events from the service showing the announcing node has been changed several times:
```
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker1"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker2"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker2"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker2"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker3"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker3"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker2"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker3"
0s          Normal   nodeAssigned   service/apache-1677160163   announcing from node "k8s-worker3"
```
Try to get metrics one by one:
```
prometheus:~$ curl -s http://k8s-worker1.example.com:7472/metrics |  grep metallb_speaker_anno
metallb_speaker_announced{ip="1.2.3.4",node="k8s-worker1",protocol="layer2",service="default/apache-1677160163"} 1
prometheus:~$ ^worker1^worker2
curl -s http://k8s-worker2.example.com:7472/metrics |  grep metallb_speaker_anno
metallb_speaker_announced{ip="1.2.3.4",node="k8s-worker2",protocol="layer2",service="default/apache-1677160163"} 1
prometheus:~$ ^worker2^worker3
curl -s http://k8s-worker3.example.com:7472/metrics |  grep metallb_speaker_anno
metallb_speaker_announced{ip="1.2.3.4",node="k8s-worker3",protocol="layer2",service="default/apache-1677160163"} 1
```

Could it be a bug or is it some misconfiguration from our side?

**Comment by fedepaol** [comment] 2023-06-12 09:44
What I am not sure I understand is, why the old speaker doesn't get the service back when it restarts?
In any case, let's assume that while the speaker is down, the service migrates to another speaker and doesn't get back (because the etp is local and the endpoint moved away too, for example).

What happens in this case is, the old speaker doesn't know that it was announcing the service, so it won't set the gauge back to 0 (as it would for example if it withdraws the service while it is still running).
I also hope that a speaker restart is an exceptional event , so this is not too critical.

Said that, a possible way to fix this is to have each speaker enumerate all the existing LB services and setting the metric to 0 before starting to process the services.

**Comment by fedepaol** [comment] 2023-12-01 09:18
> Hi! Any input on the issue? Should I provide more test results?

nope, I think we have a good grasp of what's happening. I was hoping for somebody to pick this up but if not, we'll fix it.

**Comment by ksankeerth** [comment] 2023-12-29 03:47
Hi @fedepaol,

I'm new to MetalLB. Can I pick this issue? 

Thanks,
Sankeerthan

**Comment by ksankeerth** [comment] 2024-02-12 02:13
Hi Team,

Sorry for the delay. I've tried to reproduce in my cluster. I couldn't reproduce it. 
I also configure etp as local. In that case also, after new speaker pod started (killed one to reproduce), metrics were produced by only one speaker. 

In my observations, I've never seen  permanent change of announcing  node. If I kill one speaker pod (that currently announces the svc), other pods running on other nodes will announce the svc until new speaker pod is started. Once the new pod is started, it started announcing IP for svc. For reproducing I used v0.13.12 since the issue was reported 6+ months before.

Appreciate, If You can offer any help to reproduce.


Thanks!

**Comment by ksyblast** [comment] 2024-02-12 13:14
Hello! 
@ksankeerth thanks for checking, we have upgraded recently to K8s v1.27.5 and metallb v0.13.9 and I cannot reproduce the issue anymore. Not sure what has changed since then but seems it's fixed!

**Comment by fedepaol** [comment] 2024-02-12 16:25
Weird, can't think about a reason why this could be self fixed. In any case, I am going to close the issue.
@ksyblast feel free to reopen / file a new one if you hit it again, and thanks!

**Closed by fedepaol** 2024-02-12 16:25 UTC
Labels: help wanted, good first issue, experience-report, protocol/layer2, observability
