### ISSUE TITLE
failover ~40s, v0.8.3, arp mode, k8s-1.17.2, calico-3.12/cilium-1.6.6/flannel, both ipvs&iptables

### ISSUE THREAD

**Issue by morgwai** [metallb/metallb#524] opened 2020-02-06 07:00 UTC
both iptables and ipvs had very similar failover ranges (between 35-45s)

in addition to the above, `curl` clients who attempted to make connection before the failover happened, were usually suspended 10-20s more after the clients who attempted to make a new connection could communicate with the service without problems.
(edit: initially I thought it was happening only in `iptables` mode, but after more tests I observed this problem also in `ipvs` mode)

cluster consists of 1 master and 3 worker nodes setup on libvirt/KVM VMs on a single computer. each VM is running ubuntu-18.04.3 cloud image and has 2 vcpus and 2GB RAM. host is also running ubuntu 18.04.3, has 16GB RAM, 2 physical cores + 2 virtual with hyper-threading. My libvirt/KVM is using network with 192.168.122.0/24 cidr:
```xml
<network>
  <name>default</name>
  <uuid>a2d171cf-1a10-447b-a14c-93274c4a4174</uuid>
  <forward mode='nat'/>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:09:94:08'/>
  <ip address='192.168.122.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.122.101' end='192.168.122.254'/>
      <host mac='52:54:00:bf:69:11' name='kmaster1' ip='192.168.122.11'/>
      <host mac='52:54:00:bf:69:21' name='knode1' ip='192.168.122.21'/>
      <host mac='52:54:00:bf:69:22' name='knode2' ip='192.168.122.22'/>
      <host mac='52:54:00:bf:69:23' name='knode3' ip='192.168.122.23'/>
    </dhcp>
  </ip>
</network>
```

the master was initialized as follows:
```bash
kubeadm init --config ./init.json
wget https://docs.projectcalico.org/manifests/calico.yaml
sed -i -e "s?192.168.0.0/16?10.244.0.0/16?g" calico.yaml
kubectl apply -f ./calico.yaml
wget https://raw.githubusercontent.com/google/metallb/v0.8.3/manifests/metallb.yaml
sed -i -e "s?0.8.2?0.8.3?g" metallb.yaml
kubectl apply -f ./metallb.yaml
kubectl apply -f ./metallbConfig.yaml
```
init.json:  (when testing iptables mode, "mode" was changed and whole "ipvs" section removed)
```json
{
	"kind": "KubeProxyConfiguration",
	"apiVersion": "kubeproxy.config.k8s.io/v1alpha1",
	"mode": "ipvs",
	"ipvs": {
		"strictARP": true,
		"scheduler": "lc"
	}
}
---
{
	"kind": "ClusterConfiguration",
	"apiVersion": "kubeadm.k8s.io/v1beta2",
	"networking": {
		"podSubnet": "10.244.0.0/16"
	}
}
```
metallbConfig.yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.122.71-192.168.122.99
```

after that a simple http app with 2 replicas was deployed and exposed as a `LoadBalancer` type service with cluster external traffic policy. it was assigned `192.168.122.71` VIP.

The app includes remote IP in the response to all requests, which helped me to determine which node was holding the VIP at a given moment.
The test was performed by shutting down the VM holding the VIP and running a 1 line script `while true; do date; curl 'http://192.168.122.71/dumpRequest/?IPsOnly' ; echo; sleep 3; done` from the host's terminal and observing the output.

in ipvs mode I was also performing `ping 192.168.122.71` from the other terminal. both ping was starting to get responses after about 30-50s. `curls` that initiated connection before the failover happened, sometimes needed about 20s more to catch up, but sometimes were catching up immediately. I've run the test 3 times in ipvs mode, each time by deleting all VMs completely and setting up everything from scratch again.

in iptables mode I was in addition manually running curl from the other terminal and interrupting it with ^C if there was no response within 2-3 seconds and repeating it until I was getting responses. this allowed to notice that failover was happening about 10-20s faster than the curl from the loop who initiated the connection before the failover was catching up. the test in iptables mode was also performed 3 times with setting everything from scratch each time.

I will try Cilium or Flannel later today or tomorrow to see if it changes anything.

**Comment by morgwai** [comment] 2020-02-08 09:41
just tested with cilium (ipvs mode) : the failover time is also around 40s :(

moreover I observed the following glitches:
- it took about additional 25s for curl that attempted to connect before failover happened, to catch up (with calico similar behavior happened only in iptables mode)
- it seems that metallb's yaml has to be applied after all cilium pods are running and ready, otherwise the failover will not work at all (with calico it could be applied right away and it didn't affect anything). tested only 1 time though, so it needs further verification.

i will test flannel later today

**Comment by morgwai** [comment] 2020-02-08 11:03
also ~40s on flannel (current master) on `ipvs` mode.

additionally flannel seems to be generally unstable in my environment: simple node-port requests fail sometimes randomly. not sure if it is related to metallb in anyway. will try flannel without metallb (node-port requests) and will update here if it works better without metallb.

**Comment by morgwai** [comment] 2020-02-08 12:18
just tried on k8s-1.14.10 (v0.8.3, calico-3.12, ipvs) : also about ~40s  :(

**Comment by danderson** [comment] 2020-02-08 20:12
Known issue. Kubernetes is very slow to detect node failure, and MetalLB relies on node failure detection to do a failover.

You can adjust the kubelet healthcheck and timeout intervals to make this better, but it'll still be slow.

If you need rapid failover, I suggest using BGP mode.

**Comment by danderson** [comment] 2020-02-08 20:12
Duplicate of #298

**Closed by danderson** 2020-02-08 20:12 UTC
