### ISSUE TITLE
Conflicting leader announcements from Speaker's when using a shared IP

### ISSUE THREAD

**Issue by teeram** [metallb/metallb#805] opened 2021-02-02 02:19 UTC
Hey guys, I've found that it is possible for two different instances of Speaker within my Kubernetes cluster to both announce themselves as a leader for a shared IP address (via gratuitous ARP) in layer 2 mode. This happens when I have a shared IP amongst a set of services and one (or more) of the pods load balanced by the underlying services is restarted (either due to failure or upgrade). The action of a pod restarting is noticed by the Speaker and it immediately recomputes the set of nodes (from the endpoints list) which could be the leader for an IP address. The Speaker (and underlying node) determined to be the leader for each of the respective services is often different, which results in multiple instances of Speaker issuing gratuitous ARP's all claiming to be the leader for a single shared IP address.

Many times, this goes unnoticed; particularly with quick requests / responses to the MetalLB IP address. However, long lived TCP streams will get reset when another Speaker issues the conflicting gratuitous ARP for a shared IP address and takes over as the leader. This can result in very poor reliability for services hosted inside of Kubernetes and made accessible with a MetalLB IP address when pods are actively coming and going.

I think that in an ideal world, only one instance of Speaker would announce itself a the leader for IP address at any given time within the entire Kubernetes cluster. Particularly when that IP address is shared amongst a set of services. Having multiple instances of Speaker issue conflicting gratuitous ARP's shifts the network traffic immediately and in a very nondeterministic manner. I think it is still fair for another instance of Speaker to pick up all the traffic immediately should the former leader of an IP address fail though.

MetalLB Version: 0.9.5
Kubernetes Version: 1.20.1
CNI: Flannel
kube-proxy: iptables

**Comment by makeacode** [comment] 2021-02-12 20:10
i'm also seeing this behavior with metallb 0.9.5 in a 1.18.12 cluster.  i've migrated one of our workloads from metallb 0.8.1 on kubernets 1.15.12 and it went from no tcp resets to resets every few seconds.  my inclination is that something is preventing the memberlist feature from working correctly but i can't find anything wrong.  tcpdump would indicate that both tcp and udp packets are flowing as expected

**Comment by MaxRink** [comment] 2021-02-19 18:46
We are also seeing this, this also causes connection resets

**Comment by russellb** [comment] 2021-06-16 14:15
I think this is a duplicate of #558

**Closed by russellb** 2021-06-16 14:15 UTC
Labels: protocol/layer2
