### ISSUE TITLE
metallb : Multiple protocol like TCP & UDP usses issue

### ISSUE THREAD

**Issue by shailendra-singh93** [metallb/metallb#530] opened 2020-02-25 04:37 UTC
As we know load balancer doesn't support multiple protocol such as TCP & UDP in kubernetes services. So is there any way that load balancer could be used for multiple protocols?

**Comment by ttyS0** [comment] 2020-02-25 15:00
I use the `allow-shared-ip` feature for this. Specifically, the service config for my Unifi controller looks like this:

```
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-tcp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: unifi-device-inform
    port: 8080
  - name: unifi-controller-ui
    port: 8443
  - name: unifi-http
    port: 8880
  - name: unifi-https
    port: 8843
  - name: unifi-speed-test
    port: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-udp
  namespace: unifi
  annotations:
    metallb.universe.tf/allow-shared-ip: "unifi-controller"
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
  - name: unifi-discovery
    port: 10001
    protocol: UDP
  - name: unifi-stun
    port: 3478
    protocol: UDP
```

**Comment by johanfleury** [comment] 2020-02-25 16:00
This use-case is well explained in the [usage section of the documentation](https://metallb.universe.tf/usage/#ip-address-sharing).

**Comment by praseodym** [comment] 2020-03-14 21:04
I found that when using two services (TCP+UDP) with the `Local` traffic policy, the same shared IP and the same set of pods (as described in the documentation), MetalLB sometimes assigns the two services to two different pods. This breaks on of the services, and probably also causes the virtual IP to be announced twice.

I've worked around that by instead setting `externalIPs` on one of the services to the shared virtual IP.

**Comment by rata** [comment] 2020-03-23 03:32
@praseodym linked doc says:
> may colocate the two services on the same IP, but does not have to. If you want to ensure that they share a specific address, use the spec.loadBalancerIP functionality described above.

IIUC, the link and the example should answer this. Am I missing something?

**Comment by champtar** [comment] 2020-03-23 03:39
@rata from the top of my head, to elect the node in charge of a particular loadbalancer we use the hash of the loadbalancer name modulo the number of nodes. We should use the IP.

**Comment by champtar** [comment] 2020-03-23 03:44
Hash of node name + service name
https://github.com/metallb/metallb/blob/main/speaker/layer2_controller.go#L80

**Comment by rata** [comment] 2020-03-23 04:03
@champtar ups, sorry for my quick message (1am here :-D), I was focusing in the previous comments and missed the point on @praseodym comment.

It makes sense, there might be a bug in that case for Layer 2, good catch! :-)

Do you happen to have the setup for testing in layer 2 handy? :-)

**Comment by praseodym** [comment] 2020-03-23 07:16
@rata
> can you confirm you saw this when using Layer 2 mode? And, just in case, which version of MetalLB?
Yes, this is almost certainly what happened in my setup. This was using MetalLB 0.8.2.

**Comment by rata** [comment] 2020-03-23 14:33
Thanks! @praseodym can you create a new issue to track this (the original issue to ask how to support LB with multiple protocols, not really related), ideally with as much detail as possibe? (i.e. services sharing the ip, a `kubectl describe` for those services showing which nodes is announcing, so it is clear that different services with shared IPs are announced by two different nodes, etc.)

**Comment by praseodym** [comment] 2020-03-23 20:24
@rata Sure thing, I’ve created #558. It’s related to this issue to the extent that the current solution for doing TCP+UDP requires multiple services, which can trigger this bug. I’ll try to create an easy way to reproduce this.

**Comment by rata** [comment] 2020-03-23 20:28
Thanks! Let's continue that bug there, and if you can add an easy way to reproduce, great!

Closing this issue, as the documentation linked solves the initial question.

**Closed by rata** 2020-03-23 20:28 UTC
