### ISSUE TITLE
race condition between ip announcement and k8s node network programming

### ISSUE THREAD

**Issue by juliantaylor** [metallb/metallb#496] opened 2019-11-18 13:53 UTC
When using metallb in bgb mode with services in `externalTrafficPolicy: Local` there is a race condition between metallb announcing the ip address and kubernetes components (e.g. kube-proxy) setting up the network on the node.

With `externalTrafficPolicy: Local` only pods running on the same machine the traffic comes in to are valid endpoints for a kubernetes service.
If a new pod becomes ready on a node where no pod of that services was present before metallb will see the endpoint and announce the ip.
At the same time k8s components like kube-proxy will see the endpoint and setup the node network (e.g. iptables or ipvs).

As both see the same change at the same time the ip announcement can be faster than the node network setup so traffic to the ip will not arrive at the pod.

This seems to be a fundamental problem with the way kubernetes currently works so it is probably not possible to avoid it in a clean way.
Though we do need to solve this issue as it causes regular traffic disruptions during redeployments.

What we did was add a wait to metallb before it announces the ip to allow the kube-proxy time to setup the network, this fixed the disruptions.

Here is the POC patch we currently are using (it also avoids unnecessary waits for already existing endpoints using an k8s annotation):

```patch
--- a/speaker/main.go
+++ b/speaker/main.go
@@ -19,6 +19,7 @@ import (
        "fmt"
        "net"
        "os"
+       "time"
 
        "go.universe.tf/metallb/internal/bgp"
        "go.universe.tf/metallb/internal/config"
@@ -227,6 +228,30 @@ func (c *controller) SetBalancer(l log.Logger, name string, svc *v1.Service, eps
                return c.deleteBalancer(l, name, deleteReason)
        }
 
+       waitTime := 10 * time.Second
+       // annotation created on last service change
+       annot, ok := eps.ObjectMeta.Annotations["endpoints.kubernetes.io/last-change-trigger-time"]
+       if ok {
+               changeTime, err := time.Parse(time.RFC3339, annot)
+               if err == nil {
+                       timeDiff := time.Now().Sub(changeTime)
+                       waitTime = waitTime - timeDiff
+               }
+       // new endpoint may not have a change annotation, use creation timestamp
+       } else {
+               changeTime := eps.ObjectMeta.GetCreationTimestamp().Time
+               timeDiff := time.Now().Sub(changeTime)
+               waitTime = waitTime - timeDiff
+       }
+       // only wait for TrafficPolicyTypeLocal services which are only
+       // configured on the nodes they are running on, other services always
+       // have have an active endpoint configured on all nodes so the race
+       // potential is only during initial node startup which can be handled
+       // better in the deployments
+       if svc.Spec.ExternalTrafficPolicy == v1.ServiceExternalTrafficPolicyTypeLocal && waitTime > 0 {
+               l.Log("event", "waiting", "msg", fmt.Sprintf("Waiting %s seconds for network programming", waitTime))
+               time.Sleep(waitTime)
+       }
```

Do you have any suggestions on solving it or maybe would even be willing to accept this approach into metallb proper?

**Comment by fedepaol** [comment] 2024-04-12 10:04
Seems a dupe of https://github.com/kubernetes/kubernetes/issues/113203 which is declared as fixed in k8s.
Closing the issue.

**Closed by fedepaol** 2024-04-12 10:04 UTC
Labels: bug, protocol/BGP

**Comment by juliantaylor** [comment] 2024-04-12 11:33
I do not see how that kubernetes issue is related to this issue.
This problem cannot be solved by kubernetes alone, it requires metallb consumes feedback from kubernetes when the network has been programmed.
So far I know this does not exist yet thus the workarounds with checking for open ports.

**Comment by fedepaol** [comment] 2024-04-12 12:52
> I do not see how that kubernetes issue is related to this issue. 

From https://github.com/kubernetes/kubernetes/issues/113203#issuecomment-1286447095

```
. Here i think there is no scope for the pod to send an RST to the client. When the pod comes up on NODE-B, the speaker advertises the route to DCGW before the IPTABLE rules are setup. 
```

and again from https://github.com/kubernetes/kubernetes/issues/113203#issuecomment-1292907189

```
why metallb should be faster than kube-proxy?
```

So to me it looks EXACTLY the race you are talking about.

**Comment by juliantaylor** [comment] 2024-04-12 14:44
> why metallb should be faster than kube-proxy?

metallb announces the route when the endpoint is ready, kube-proxy configures the node network when the endpoint is ready

metallb just does a bgb announcement, kube-proxy configures thousands of iptables (or ipvs) rules in large clusters, this can take up to a minute in some cases.

metallb will always be a lot faster

**Comment by juliantaylor** [comment] 2024-04-12 14:50
What did happen in kubernetes 1.28 is that the kube-proxy iptables implementation was significantly speed up for incremental updates. This is probably why some cannot reproduce this anymore.

But even with this improvement, it still takes on average 2-5 seconds to configure the node in our clusters (around 20000 pods) and this issue very much still exists.
