### ISSUE TITLE
Controller failing after upgrading MetalLB to v0.13.7

### ISSUE THREAD

**Issue by KnudFrandsen** [metallb/metallb#1743] opened 2022-12-12 12:57 UTC
Hey,
Complications is met when upgrading MetalLB from `v0.13.4` to `v0.13.7`. All other resources than the controller is deployed successfully. The issue is NOT provoked when changing the image target of the controller to `v0.13.6`, therefore is the suspicion that it is related to `v0.13.7`. 

## **Environment**
- OKD v4.10
- MetalLB v0.13.7

## **Logs**

Logs of the Controller after failed startup.
```bash
oc logs controller
```
```bash
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"metallb-system/webhook-service","ts":"2022-12-12T12:42:31Z"}
{"caller":"service_controller.go:103","controller":"ServiceReconciler","end reconcile":"metallb-system/webhook-service","level":"info","ts":"2022-12-12T12:42:31Z"}
{"level":"info","ts":1670848956.8723037,"msg":"Stopping and waiting for non leader election runnables"}
I1212 12:42:36.872555       1 trace.go:205] Trace[1810115296]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.24.0/tools/cache/reflector.go:167 (12-Dec-2022 12:42:12.673) (total time: 24199ms):
Trace[1810115296]: [24.199023089s] [24.199023089s] END
{"level":"info","ts":1670848956.8725839,"msg":"Stopping and waiting for leader election runnables"}
{"level":"info","ts":1670848956.8726323,"msg":"Shutdown signal received, waiting for all workers to finish","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool"}
{"level":"info","ts":1670848956.8726523,"msg":"Shutdown signal received, waiting for all workers to finish","controller":"service","controllerGroup":"","controllerKind":"Service"}
{"level":"info","ts":1670848956.8726573,"logger":"cert-rotation","msg":"stopping cert rotator controller"}
{"level":"error","ts":1670848956.872701,"logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *unstructured.Unstructured Informer to sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:144\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:580\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:545\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:132"}
{"level":"info","ts":1670848956.8727448,"msg":"Starting workers","controller":"cert-rotator","worker count":1}
{"level":"info","ts":1670848956.8727543,"msg":"Shutdown signal received, waiting for all workers to finish","controller":"cert-rotator"}
{"level":"error","ts":1670848956.8729188,"msg":"Reconciler error","controller":"cert-rotator","object":{"name":"webhook-server-cert","namespace":"metallb-system"},"namespace":"metallb-system","name":"webhook-server-cert","reconcileID":"7b03b710-dee3-477b-821f-2e60af9220ba","error":"cache not ready","errorVerbose":"cache not ready\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:620\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
{"level":"info","ts":1670848956.8730543,"msg":"All workers finished","controller":"cert-rotator"}
{"level":"error","ts":1670848956.8730688,"logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *unstructured.Unstructured Informer to sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:144\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:580\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:545\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:132"}
{"level":"info","ts":1670848956.8730884,"msg":"All workers finished","controller":"service","controllerGroup":"","controllerKind":"Service"}
{"level":"info","ts":1670848956.8730917,"msg":"All workers finished","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool"}
{"level":"info","ts":1670848956.8730955,"msg":"Stopping and waiting for caches"}
{"level":"info","ts":1670848956.9723296,"msg":"Stopping and waiting for webhooks"}
{"level":"info","ts":1670848956.9723997,"msg":"Wait completed, proceeding to shutdown the manager"}
```

**Comment by fedepaol** [comment] 2022-12-23 14:57
Seems like a duplicate of https://github.com/metallb/metallb/issues/1731 which I am not able to reproduce.
My gut feeling is that it is related to some race introduced by https://github.com/metallb/metallb/pull/1648

@KnudFrandsen are you able to reproduce this consistently? I remember @cyclinder saying this was fixed by changing the helm manifests because he sets the resources (link https://kubernetes.slack.com/archives/C8FSTGU56/p1669955151195249) Need to dig more, but closing this as dupe of https://github.com/metallb/metallb/issues/1731

**Closed by fedepaol** 2022-12-23 14:57 UTC
