### ISSUE TITLE
Endless stream of nodeAssigned events after updating to MetalLB 0.10

### ISSUE THREAD

**Issue by mologie** [metallb/metallb#978] opened 2021-10-03 13:14 UTC
Hi, I am using MetalLB under Talos (0.11) with K8s 1.21. The cluster has been running on MetalLB 0.9.6 for months w/o issues. I have just attempted to update to 0.10 but found that it misbehaves as explained in this ticket.

The problem:

In 0.9.6 I would see a single "nodeAssigned" event per LB; in 0.10.2 I see a flood of them, roughly one per LB every 2 seconds, which generates hundreds of events every minute.

LBs themselves continue to work, but clearly something is not right.

My configuration/environment:

* MetalLB 0.9.6 (working) and 0.10.2 (nodeAssigned spam)
* Installation method: by manifest
* L2 mode
* kube-proxy in iptables mode (Talos default)
* Talos 0.11.5 with K8s 1.21.3 under Linux 5.10.52
* Calico CNI 3.19.0

My config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: ingress-public
        protocol: layer2
        addresses:
          - 10.99.99.122/32
        auto-assign: false
      - name: ingress-foo
        protocol: layer2
        addresses:
          - 10.99.99.123/32
        auto-assign: false
      - name: ingress-internal
        protocol: layer2
        addresses:
          - 10.4.99.0/32
        auto-assign: false
      - name: default
        protocol: layer2
        addresses:
          - 10.4.99.1-10.4.99.31
```

Special cluster settings: The `MixedProtocolLBService=true` api-server feature gate is set, and one LB on the cluster serves both TCP and UDP. The issue appears to be unrelated to this setting however.

Instead of updating I have also tried to delete the metallb-system namespace and recreate it from scratch with no change.

If you believe that this issue is not due to a configuration/cluster at my end I would appreciate your input. I can dedicate some time to diagnosing and fixing this issue w/ code contributions if needed.

**Comment by fedepaol** [comment] 2021-10-05 07:17
@mologie would you mind adding the logs of the speakers?

**Comment by mologie** [comment] 2021-10-05 10:06
Of course, please find a shell log attached. These are raw logs filtered slightly by sed to obfuscate service names.

Compared to my original report I made the following two changes:

* Fixed the following warning: `28m Warning AllocationFailed service/foo-ingress-udp Failed to allocate IP for "avas6/foo-ingress-udp": can't change sharing key for "foo6/foo-ingress-udp", address also in use by traefik/traefik-public`
* Updated Calico to 3.20.1

These two changes do not seem to make a difference though. For example, grep for `serviceAnnounced","ip":"10.4.100.0","msg":"service has IP, announcing","pool":"ingress-internal"` and notice how it still announces the service every 5 seconds.

[metallb-0.9.6-to-0.10-update.log](https://github.com/metallb/metallb/files/7284823/metallb-0.9.6-to-0.10-update.log)

**Comment by champtar** [comment] 2021-10-05 12:41
This is fixed in master and will be released in 0.10.3 https://github.com/metallb/metallb/pull/909/files
@russellb @johananl any ETA ?

**Comment by mologie** [comment] 2021-10-05 12:44
Ack, sorry for the dupe in that case, I did not find these issues or the PR with `nodeAssigned` and related keywords I saw in the logs. Thank you!

(Please close at will, or pin the ticket since I'm the 3rd one to report this now.)

**Comment by fedepaol** [comment] 2021-10-06 11:11
Closing this as dupe of https://github.com/metallb/metallb/issues/901 and https://github.com/metallb/metallb/issues/899

**Closed by fedepaol** 2021-10-06 11:11 UTC
Labels: bug

**Comment by russellb** [comment] 2021-10-11 11:08
You’re welcome. Thanks for confirming.
