### ISSUE TITLE
metallb-controller failed to start with v0.13.7

### ISSUE THREAD

**Issue by cyclinder** [metallb/metallb#1731] opened 2022-12-02 04:53 UTC
metallb-controller fall into `CrashLoopBackOff`, the logs show :
```
{"level":"error","ts":1669955982.4525785,"logger":"cert-rotation","msg":"secret is not well-formed, cannot update webhook configurations","error":"Cert secret is not well-formed, missing ca.crt","errorVerbose":"Cert secret is not well-formed, missing ca.crt"
```

**Comment by cyclinder** [comment] 2022-12-02 04:55
```
➜  git:(main) ✗ kubectl get po -n metallb-system --kubeconfig test/.config  -o wide
NAME                                  READY   STATUS             RESTARTS       AGE   IP           NODE                          NOMINATED NODE   READINESS GATES
metallb-controller-7679968996-7cf7d   0/1     CrashLoopBackOff   17 (45s ago)   34m   172.40.1.3   network-chart-worker          <none>           <none>
metallb-speaker-gwhzs                 1/1     Running            0              34m   172.18.0.2   network-chart-worker          <none>           <none>
metallb-speaker-hpn7k                 1/1     Running            0              34m   172.18.0.3   network-chart-control-plane   <none>           <none>

```

**Comment by cyclinder** [comment] 2022-12-02 04:56
```
git:(main) ✗ kubectl describe po -n metallb-system          metallb-controller-7679968996-7cf7d --kubeconfig test/.config
...
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  35m                  default-scheduler  Successfully assigned metallb-system/metallb-controller-7679968996-7cf7d to network-chart-worker
  Normal   Started    34m (x2 over 35m)    kubelet            Started container controller
  Warning  Unhealthy  33m (x6 over 35m)    kubelet            Liveness probe failed: Get "http://172.40.1.3:7472/metrics": dial tcp 172.40.1.3:7472: connect: connection refused
  Normal   Killing    33m (x2 over 34m)    kubelet            Container controller failed liveness probe, will be restarted
  Normal   Created    33m (x3 over 35m)    kubelet            Created container controller
  Warning  Unhealthy  30m (x30 over 35m)   kubelet            Readiness probe failed: Get "http://172.40.1.3:7472/metrics": dial tcp 172.40.1.3:7472: connect: connection refused
  Normal   Pulled     10m (x14 over 35m)   kubelet            Container image "quay.m.daocloud.io/metallb/controller:v0.13.7" already present on machine
  Warning  BackOff    17s (x103 over 29m)  kubelet            Back-off restarting failed container

```

**Comment by fedepaol** [comment] 2022-12-02 09:17
Hi @cyclinder , is this happening constantly?
Can you print the content of the "webhook-server-cert" secret?

**Comment by cyclinder** [comment] 2022-12-02 09:26
```
➜  ~ kubectl logs -f -n metallb-system       metallb-controller-7679968996-bxpcl
{"branch":"dev","caller":"main.go:141","commit":"dev","goversion":"gc / go1.18.3 / amd64","level":"info","msg":"MetalLB controller starting version 0.13.7 (commit dev, branch dev)","ts":"2022-12-02T09:24:53Z","version":"0.13.7"}
{"action":"setting up cert rotation","caller":"webhook.go:34","level":"info","op":"startup","ts":"2022-12-02T09:25:03Z"}
{"caller":"k8s.go:380","level":"info","msg":"Starting Manager","op":"Run","ts":"2022-12-02T09:25:04Z"}
{"level":"info","ts":1669973104.9480574,"logger":"cert-rotation","msg":"starting cert rotator controller"}
{"level":"info","ts":1669973105.546511,"msg":"Starting EventSource","controller":"cert-rotator","source":"&{{%!s(*v1.Secret=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] []  []} <nil> map[] map[] }) %!s(*cache.informerCache=&{0xc00054eac0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
{"level":"info","ts":1669973105.84648,"msg":"Starting EventSource","controller":"cert-rotator","source":"&{{%!s(*unstructured.Unstructured=&{map[apiVersion:admissionregistration.k8s.io/v1 kind:ValidatingWebhookConfiguration]}) %!s(*cache.informerCache=&{0xc00054eac0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
{"level":"info","ts":1669973106.0460896,"msg":"Starting EventSource","controller":"cert-rotator","source":"&{{%!s(*unstructured.Unstructured=&{map[apiVersion:apiextensions.k8s.io/v1 kind:CustomResourceDefinition]}) %!s(*cache.informerCache=&{0xc00054eac0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
{"level":"info","ts":1669973106.4465783,"msg":"Starting EventSource","controller":"cert-rotator","source":"&{{%!s(*unstructured.Unstructured=&{map[apiVersion:apiextensions.k8s.io/v1 kind:CustomResourceDefinition]}) %!s(*cache.informerCache=&{0xc00054eac0}) %!s(chan error=<nil>) %!s(func()=<nil>)}}"}
{"level":"info","ts":1669973106.5470076,"msg":"Starting Controller","controller":"cert-rotator"}
{"level":"info","ts":1669973106.5471854,"msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1beta1.IPAddressPool"}
{"level":"info","ts":1669973106.5472555,"msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1beta1.AddressPool"}
{"level":"info","ts":1669973106.5472693,"msg":"Starting EventSource","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","source":"kind source: *v1beta1.Community"}
{"level":"info","ts":1669973106.5473042,"msg":"Starting Controller","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool"}
{"level":"info","ts":1669973107.2460241,"msg":"Starting EventSource","controller":"service","controllerGroup":"","controllerKind":"Service","source":"kind source: *v1.Service"}
{"level":"info","ts":1669973107.2463114,"msg":"Starting EventSource","controller":"service","controllerGroup":"","controllerKind":"Service","source":"channel source: 0xc00013ed20"}
{"level":"info","ts":1669973107.6463435,"msg":"Starting Controller","controller":"service","controllerGroup":"","controllerKind":"Service"}
W1202 09:25:09.646039       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
W1202 09:25:12.345926       1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool
{"level":"info","ts":1669973113.1464357,"logger":"cert-rotation","msg":"refreshing CA and server certs"}
{"level":"info","ts":1669973113.6461742,"msg":"Starting workers","controller":"service","controllerGroup":"","controllerKind":"Service","worker count":1}
{"caller":"service_controller.go:60","controller":"ServiceReconciler","level":"info","start reconcile":"default/kubernetes","ts":"2022-12-02T09:25:14Z"}
{"level":"info","ts":1669973115.5466266,"msg":"Starting workers","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool","worker count":1}
{"level":"info","ts":1669973115.9460409,"msg":"Stopping and waiting for non leader election runnables"}
{"level":"info","ts":1669973116.1465201,"msg":"Stopping and waiting for leader election runnables"}
{"level":"info","ts":1669973116.5461323,"msg":"Shutdown signal received, waiting for all workers to finish","controller":"ipaddresspool","controllerGroup":"metallb.io","controllerKind":"IPAddressPool"}
{"level":"info","ts":1669973116.5464077,"msg":"Shutdown signal received, waiting for all workers to finish","controller":"service","controllerGroup":"","controllerKind":"Service"}
{"level":"error","ts":1669973116.6460412,"logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *unstructured.Unstructured Informer to sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:144\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:580\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:545\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:132"}
{"level":"error","ts":1669973116.6463106,"logger":"controller-runtime.source","msg":"failed to get informer from cache","error":"Timeout: failed waiting for *unstructured.Unstructured Informer to sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:144\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:233\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:580\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.0/pkg/util/wait/wait.go:545\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/source/source.go:132"}
{"level":"error","ts":1669973116.546582,"msg":"Could not wait for Cache to sync","controller":"cert-rotator","error":"failed to wait for cert-rotator caches to sync: cache did not sync","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:210\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:241\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/manager/runnable_group.go:219"}
```

**Comment by fedepaol** [comment] 2022-12-05 11:51
hi, can you share also your values.yaml? I tried to reproduce it locally but wasn't able to.

**Comment by pbptaker** [comment] 2022-12-25 14:38
I have the same issue here. The controller pod cant start since he cant connect to himself using tcp 7472. Own readiness and liveness checks are failing. No firewall on the host, no k8s networkpolicies applied. Installed / reacrated using helm several times. Newest version. Any Ideas? Thank you

**Comment by cyclinder** [comment] 2022-12-29 08:16
@pbptaker Did you set the resources of controller?

**Comment by KnudFrandsen** [comment] 2023-01-02 13:38
Removing resource limits solved my issue.

**Comment by fedepaol** [comment] 2023-01-17 17:19
Closing as the pr was merged

**Closed by fedepaol** 2023-01-17 17:19 UTC
