### ISSUE TITLE
metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool

### ISSUE THREAD

**Issue by migs35323** [metallb/metallb#1798] opened 2023-01-24 11:12 UTC
New fresh k3s cluster (v1.24) (no service lb and no traefik as usual, using flannel)
used official helm to install metallb v 1.13.7 
created namespace with pod security labels as mentioned in the docs (not sure if this is needed)
no resources applied yet (no ip-pools, no adverts)
speaker pods throw warn every few seconds:  
```
1 warnings.go:70] metallb.io v1beta1 AddressPool is deprecated, consider using IPAddressPool 
```

**Comment by fedepaol** [comment] 2023-01-24 11:15
This is a red herring caused by the fact that metallb is still watching the old version of the api for backward compatibility. 
Closing as non issue

**Closed by fedepaol** 2023-01-24 11:15 UTC

**Comment by MQPearth** [comment] 2023-05-31 09:50
But I have already used IPAddressPool, why am I still getting this prompt?
