### ISSUE TITLE
L2 Mode on k8s workers on different L2 segments

### ISSUE THREAD

**Issue by yee379** [metallb/metallb#511] opened 2019-12-20 02:22 UTC
# The bug itself, as detailed as you can.

I have a small test cluster with worker nodes across 3 different l2 network segments. Each network segment is configured with its on unique subnet. Each worker has a single network interface.

What i think i'm seeing is that that controller is handing out ownership of the LoadBalance'd IP address to just one of the speakers as the logs (from the speaker) indicate:

    {"caller":"main.go:246","event":"serviceAnnounced","ip":"172.23.99.176","msg":"service has IP, announcing","pool":"internal","protocol":"layer2","service":"default/my-nginx","ts":"2019-12-20T02:03:17.546896714Z"}

however, if the speaker who gets allocated is not on the same L2 segment-L3 subnet as that of the LoadBalancer IP range, then of course, the network will never forward the traffic to into MetalLB. ie if my LoadBalanced IP is 172.23.99.176, then this address will only work it has been assigned to worker nodes that are on 172.23.99.128/26.

So i attempt to restrict where i run the speaker; by essentially creating a `nodeSelector` on the speaker daemonset; therefore (in my naivety) forcing all metallb traffic to just those nodes on the same subnet as the allocated IP pool dished out by metallb.... however, there are times where none of the metallb speakers even log the above message! and hence the LoadBalancer IP is never actually assigned - and hence no traffic.

# Version of MetalLB

            image: metallb/controller:main

# Version of Kubernetes

1.17.0, deployed with `kubeadm init` (no options)

# Name and version of network addon (e.g. Calico, Weave...)

Calico 3.10.2

# Whether you've configured kube-proxy for iptables or ipvs mode

iptables

**Comment by johananl** [comment] 2020-06-12 18:45
Layer to mode relies on ARP, which means only a single node can be "active" (namely respond to ARP requests) for an IP address at any given time. This is explained in the [docs](https://metallb.universe.tf/concepts/layer2/).

If you have node A in subnet A and node B in subnet B, the two nodes can never announce the same IP address in layer 2 mode because the IP address must belong to either subnet A **or** subnet B.

I'm assuming you have multiple *groups* of nodes and you want MetalLB to do layer 2 failover **within** a group. AFAICT this could have been possible if we could specify multiple address pools and configure a pool to be announced only by a specific set of nodes. Unfortunately this functionality doesn't exist in MetalLB at the moment.

Without looking into this too deeply, it does make sense to me to have an "affinity" between an address pool and a set of nodes, i.e. something like a "node selector" for a pool. This could possibly even be protocol-independent. I've opened #630 to explore this idea.

**Comment by russellb** [comment] 2020-06-15 13:43
#502 was one attempt at implementing pools assigned to a groups of nodes.  The author suggested he may follow up with another PR

**Comment by danielkucera** [comment] 2020-09-10 12:48
We are also facing this problem. I tried to deploy two metallb instances into two separate namespaces:
- metallb-system
  - modified speaker daemonset with node selector to select nodes in backend L2
  - using subnet-1 in config
- metallb-system-dmz
  - modified speaker daemonset with node selector to select nodes in DMZ L2
  - using subnet-2 in config

The problem is that they BOTH try to handle ALL services in the cluster - those, which externalIP matches but also those which doesn't and they modify it's status, overwriting each other:
```
$ oc describe service abc -n cde | tail
TargetPort:               30109/TCP
NodePort:                 data-30109  32736/TCP
Endpoints:
Session Affinity:         ClientIP
External Traffic Policy:  Cluster
Events:
  Type     Reason            Age                  From                Message
  ----     ------            ----                 ----                -------
  Warning  AllocationFailed  1s (x4761 over 80m)  metallb-controller  Failed to allocate IP for "cde/abc": "10.10.10.64" is not allowed in config
  Normal   IPAllocated       1s (x4761 over 80m)  metallb-controller  Assigned IP "10.10.10.64"
```

I see two possible solutions here:
- metallb won't touch services with IP from subnets not configure and won't report errors 
- create an annotation for each service to assign it to a specific metallb instance

What do you think about this?

**Comment by johananl** [comment] 2020-09-10 13:28
@danielkucera I think the 2nd option sounds better. A similar thing has been discussed in https://github.com/metallb/metallb/issues/685.

I think the issue you're describing is slightly different than the one described by @yee379 though: they have *one* MetalLB deployment and nodes in multiple subnets whereas you have *multiple* MetalLB deployments (and nodes in multiple subnets). So, I think you are affected by both this (#511) issue and by #685. Does that make sense?

**Comment by danielkucera** [comment] 2020-09-10 13:40
@johananl I would prefer having only one metallb in the cluster managing different subnets with dedicated nodes as @yee379 described but as this is not currently possible I started looking into workarounds. But I got your point, let's leave this issue for single instance and I'll continue discussing multiple instances in the other issue.

**Comment by fedepaol** [comment] 2022-04-20 16:42
Closed by https://github.com/metallb/metallb/pull/1302

**Closed by fedepaol** 2022-04-20 16:42 UTC
Labels: protocol/layer2, flexibility
