### ISSUE TITLE
Controller hangs up on ""Ensuring CA cert""

### ISSUE THREAD

**Issue by ArsenyBelorukov** [metallb/metallb#1814] opened 2023-02-01 11:18 UTC
metallb 0.13.7 that is deployed by ArgoCD using helm chart
kubernetes v1.24.7
cilium v1.12.3 without kube-proxy

After restart, a controller pod is being killed by `kubelet` because doesn't answer on Readiness probe.
```
Readiness probe failed: Get "http://172.27.5.96:7472/metrics": dial tcp 172.27.5.96:7472: connect: connection refused
```

controller's logs:
```
2023-02-01T11:01:16.989086496Z {"caller":"service_controller_reload.go:103","controller":"ServiceReconciler - reprocessAll","end reconcile":"metallbreload/reload","level":"info","ts":"2023-02-01T11:01:16Z"}
2023-02-01T11:01:17.081338269Z {"level":"info","ts":1675249277.0811827,"msg":"Starting workers","controller":"cert-rotator","worker count":1}
2023-02-01T11:01:17.081967543Z {"level":"info","ts":1675249277.081889,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}


2023-02-01T11:01:54.165726938Z {"level":"info","ts":1675249314.1656103,"msg":"Stopping and waiting for non leader election runnables"}
...
```

Secret webhook-server-cert:
```
kubectl -n metallb-system get secrets webhook-server-cert -o yaml | kubectl-neat
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFoTVJBd0RnWURWUVFLRXdkdFpYUmgKYkd4aU1RMHdDd1lEVlFRREV3UmpaWEowTUI0WERUSXpNREV6TURFME16UXlOVm9YRFRNek1ERXlOekUxTXpReQpOVm93SVRFUU1BNEdBMVVFQ2hNSGJXVjBZV3hzWWpFTk1Bc0dBMVVFQXhNRVkyVnlkRENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGg4b09WVENFakhRaDRUc2NhNjFuNlZUbW5tZkthUU1LcFkKK1NhYU9PanJaUWFVSHNESlZLZEVVVFVobFdqcVB4dW81QkNxeFNZYXpVeERhYW9mb3JZcVUxRlhYVkZJTUEzQQoydjZFRTN3alNLT1Y5UnJMWmh0UkFlTHJwemh2ZENLMTFWbnpaS3ZiWXhyQ1Exa0dreUY1NVN1cEhSbXJ4VFcrCjM0WitDTVoxd1U4NVc1YXlYM05GQVFaZDNlTTUyYnhYYWJwOGtuVFNDVU5HeVllS2ZMZFZ1QktjVUNmMHN2aUcKc3JIU0E0ZytibWdJdGN2UGJJQk1BV0FmRnV2UFluY01GQ0ZjbC9SY2EvZExSR0pKSmZ0Y3hMRWlvWURIUmZlSgpMZ2xHUWNpMWRuMUQrNjlBNFBhSWdDdHZKK25VZnlVUDBFNXhjUXBrdnZSMDR3eFBTVmtDQXdFQUFhTlRNRkV3CkRnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkZoUXZyQUYKVUVhRTNUdzJialNjb1phaG5EMW9NQThHQTFVZEVRUUlNQWFDQkdObGNuUXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUhXQjh2cGlHRGN1MitDRCtMWldYM29qRGdJUGVGSyt6ZFZpV2pNYXVDZUo5Y1c0Z1RQak81dzByb1gyCnpJUStTNzQ4N1I0UGlHeG5IOXN6NFJkNldEZWlnRlY2cmthTG9TNDQwYjJuL1hoN1lCUUtIVVpmeHVpTnZaSEkKL2xSS0hTRTlWQVliQXdxd0ZMMFpHbUpta2VkVFJLNVlYd2h2TEY3bmgzYzh2Y0pJQndldEROZW85WjBFb1ZTLwpBZ2xGVzJZNGFyb0RlUVlYRW1JYXNLNjRGdWlMSzZ6aTg3K1hpdExoVE5DV1VrbEo4cFdiZGxnK2t1V1oxSjhrCkk3Z3JUK0szTFVRdi9IckFOZldaVmhTdjUyekw1eEppWWRpVVlsV0xZZmtTdVB3cFFBU2k3cFh6RjZHdFlOS2sKUEl6NmVQZko4VW91VDU0MmNvREpzdVZzb1VBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  ca.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdUh5ZzVWTUlTTWRDSGhPeHhycldmcFZPYWVaOHBwQXdxbGo1SnBvNDZPdGxCcFFlCndNbFVwMFJSTlNHVmFPby9HNmprRUtyRkpock5URU5wcWgraXRpcFRVVmRkVVVnd0RjRGEvb1FUZkNOSW81WDEKR3N0bUcxRUI0dXVuT0c5MElyWFZXZk5rcTl0akdzSkRXUWFUSVhubEs2a2RHYXZGTmI3ZmhuNEl4blhCVHpsYgpsckpmYzBVQkJsM2Q0em5adkZkcHVueVNkTklKUTBiSmg0cDh0MVc0RXB4UUovU3krSWF5c2RJRGlENXVhQWkxCnk4OXNnRXdCWUI4VzY4OWlkd3dVSVZ5WDlGeHI5MHRFWWtrbCsxekVzU0toZ01kRjk0a3VDVVpCeUxWMmZVUDcKcjBEZzlvaUFLMjhuNmRSL0pRL1FUbkZ4Q21TKzlIVGpERTlKV1FJREFRQUJBb0lCQUNjcVJob0pJNVFYd1NDVAplOFU5dXZXS2l1Z09oMTN3OUhQbGlaYzVYR1dPTzVkRzhMUnF5Vzd0SVBSUG1lRjVBVWJFOXczV3d4M1F5TTZzCjdReXh4S0E1b2hCOXBKRHg2MG13TEkybHltRXJPR3VLRlV2SDdIaFdIVGxvWDhxcVZwUmIxOXhOd0l4L2VhMmYKbWg2WE43citucmxESUt0bmZPbHBDUmtMUHArcTJZNTFqS0ZJWENpUU8rQzBlSmFkL05QQTYzTlFxejA4MlpPYgpxckpXZFluTkxSSlQvQ1dYRjRvSVdjczBCMmRLMHdWelcxTG4zRThLOVhKTHdvSUZhRENPRjBjU1F3UDljdG9WCmRSb0U0bmg3YkRhVysvc295bXdIY0xLUnorYmhQTW1OMkZqOWZESSsreDVKd29JV3ZtNTVIZG5JTWFQZElYeXYKR25Qcm9wRUNnWUVBNk1kRlNVVVdlNXVBK0NDWkloNnc3NW82SEhQMUNLNzlvSlYxNWFuUEdSdy9ETVprQTVZOApocTEydjA1VkJTblJBUkdqZUs2UHNsejVONGp0YjdVR213Ylhzd2V6aXFYNGJoeTg1L0pYdkxLQU56aU0xaTJaCnhrYjJIci9OYW9nWjJFRjU3Z0FrT2Y2TktrUWo5UWNPYnJ5TFBEaTFLaUdxem15QWRmY3dSZVVDZ1lFQXl1UVUKbnA5UUJMbWpQTnhFaERkZ25EdHdCbGJHUmEwR1daNktHWGNtRitLQklscndYVkl5c2xYWXhhdzFZMG1LQ0k0bwp1WjlqbnlXWm5xSHd2Y3Qrd0hKdEJJdUNqcldOR2FveDd5YUxvYXlPRlB5N0QrK2pPdVV1eU5DSm1EZ3RsNFY0ClNSQmxaeEg2VVIxUmpQQkJuR1JVdTNzMkFRWk1wN20zVVNhWmZtVUNnWUFMSU1PYUxoaFdEbWdLOUp2OWVwUWcKMERHby9JNGhQU1JZMGV4UjcxMDhLUktHak5GcExueDBQOFNtZnBzbjVRamQwVGNNWk9QdnRld2dFSWF4U1drbwpiaHBQcjdXUWtrQ2ZHdmFZN0FmdnVHVFN2dnhVbk5kMkdCeForZmRhK1dpcTR1NXVSMGwwRUV3MVVnNloveDFjCmc5endJeEhlRXIvMG9GRS8wbkpYVlFLQmdEbCtGaVc0eVVqOWZiZENSNXdid1NHa2FpTXh0YStLenpEWUR4UVcKUWxJa1dpbHRFWTJ3UEROeXhpR0ZvZjlIbUhqQ0orSXB1MlllbG9Cd0xUTHJGampjYys0RXhuTkFHUUs3eXJpVQorSjVRc2xaYUkzdnBrUnlnVXZpT3QxN09GSVZLU2dLU1JkbkdLMk9PNWt3RXpPTFBQMzk4ODVtb3VsSVErMVJnCmxzQk5Bb0dBYmNEOEFoTE9IVTlwSEUwTlVtQmFVNHpkcGY2RE1RS0N2eSs2NmpxQnpiYzQyaHF1MndHZ0kvV0UKK05GRjlqaVBzWEl5Vkx1OE9IWWt4TmpEMkFOUXJQU3ZDUkdDRGxTWnVLaGZzZlFzYkI0em16bm5SalcrSkp6WQprTHpwOVBzc0EyVzA5OUN5SEJFZGxtRkdOTmo0UVh1a1dHVlFlNWlkbUxnV2xraVhHK009Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQWtpZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFoTVJBd0RnWURWUVFLRXdkdFpYUmgKYkd4aU1RMHdDd1lEVlFRREV3UmpaWEowTUI0WERUSXpNREV6TURFME16UXlOVm9YRFRNek1ERXlOekUxTXpReQpOVm93TlRFek1ERUdBMVVFQXhNcWJXVjBZV3hzWWkxM1pXSm9iMjlyTFhObGNuWnBZMlV1YldWMFlXeHNZaTF6CmVYTjBaVzB1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdjB3elM0UFgKUjdnV0VEU1kwaVgzNFgweEN4a3R4RTQ3MmlBck5nTGlnTGMxNU8rWXRUb1dlL25XTncvNVI3YlVwb0RqY09SZwpRWEdlbWJJY1BNd1VRSVFFaFZZL084L2J5NXRZL3lMR25lUkhjWGlFTmp4dDBpVHlsakhFa3NPeTVCTnB2SHpnClJoZ2QwcVpNOWV3OGNjUzlMVkY1clozTU4wN2szb2lhczY3enFEdG03STlxWTMzZVZpWm5KOUg4UU81aG9uWXoKZWYxTjBmRkRDWnEvOXAyMWRYVWZIeFl2dFNiR3hGdHROcTR4aDdSaXRsWnVSWE1USVVaSXVaT1VkN1ZMRnpjbgp2TnZsSmlWaFlvclQycUFMYm5jNWZzS3h3SWlIY2R3K05BRExtVEhNQ3BobkZIMEQzKzltV1hZQlArRTlhVHgyClhvd0hZL1FTYy9TNStRSURBUUFCbzRHT01JR0xNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUsKQmdnckJnRUZCUWNEQVRBTUJnTlZIUk1CQWY4RUFqQUFNQjhHQTFVZEl3UVlNQmFBRkZoUXZyQUZVRWFFM1R3MgpialNjb1phaG5EMW9NRFVHQTFVZEVRUXVNQ3lDS20xbGRHRnNiR0l0ZDJWaWFHOXZheTF6WlhKMmFXTmxMbTFsCmRHRnNiR0l0YzNsemRHVnRMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWhMRHlYcFBERUJ2aGdhMlgKbjFiQU1jQ1NaTnVyNHI0RE44VXg3TThualJOcTdTSThZK2RJMFZ3M0k2eit1NU5WdjR1alk0TTkzRHpFVTZnTgppMGhTNjkrcG1zVU1iaTJJSW53aWJaS3d4aGd6RmhMdEE4TWl4S3ZUNlFoUks1dHM2M2ViaThnUTI1Z3N2eWN1CmVNdHc4S2pWc0dmSTBRaGR2YVhwSHY5cTZrL2F2MlBPMlpQNXlSTUx2SmgyV2ZScVJUMlBaMlVDZUp6RnZaNnAKZmJzUEJFSlM3NWc1Rko1emp0blZFcThUL3VSQnorbjZvSWhzRzNOR1RBREVJVzI0WXdBbmh4N0Nsais3bGlPbQoxbGRzWVlmcGZiL1NzMGpxTFg0L2x1TEtBajVUeCswbkM1MWliTVpZeGk1WHBtV05sTGU1U2FXelFILzRySFV0CjFHKzUyZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdjB3elM0UFhSN2dXRURTWTBpWDM0WDB4Q3hrdHhFNDcyaUFyTmdMaWdMYzE1TytZCnRUb1dlL25XTncvNVI3YlVwb0RqY09SZ1FYR2VtYkljUE13VVFJUUVoVlkvTzgvYnk1dFkveUxHbmVSSGNYaUUKTmp4dDBpVHlsakhFa3NPeTVCTnB2SHpnUmhnZDBxWk05ZXc4Y2NTOUxWRjVyWjNNTjA3azNvaWFzNjd6cUR0bQo3STlxWTMzZVZpWm5KOUg4UU81aG9uWXplZjFOMGZGRENacS85cDIxZFhVZkh4WXZ0U2JHeEZ0dE5xNHhoN1JpCnRsWnVSWE1USVVaSXVaT1VkN1ZMRnpjbnZOdmxKaVZoWW9yVDJxQUxibmM1ZnNLeHdJaUhjZHcrTkFETG1USE0KQ3BobkZIMEQzKzltV1hZQlArRTlhVHgyWG93SFkvUVNjL1M1K1FJREFRQUJBb0lCQVFDSlVLWmxaMTdwNFU4ZApGTlE1elAxUkErOW5Xd3lLSStvOG1laktuV2wvSVlQek1MVjZLUmNvcU43R3FaV3pqNTYzWWo5Z3N0NFJQQUN2CnJMVXVRd09xaDlsQzZQVDg5eWg3ejZnamhBLzBHSC9jQ0xsR3dUdkhvN1BxY2hEN2xMUmRtVDNHQ2hGbTN6clIKRVlTZTVwTkF5d3RNYzNhWFZIVFpvcTBRdkJmb0w4YjRJNGVKREtpWm03UTArTWVtTXZXTnlrQTdQS3RFbTNpNApTT3BaMzd6dVFxZTJ1WTZ1SlIya0tBLzdUeG1naDEwbGZuZk05UjFpOGhFK2RScC93R0ZIdHBaaEFFQ3h4MVg2Cjd2cC9CbmZqT0ZydUprN202RDdqb1J1dW1KNVZudnBqSlJOSVVTZjg2K2paZ3FmWVAzV0J6NXpYa3hLdkVXcUYKMnIrOVp2dnhBb0dCQU1oSDJpenVqUDZrcDM4S3RxSmE5aytYSGE0WXZ6VmNWZTR1TkN0cHgzbE9hOUcvVldQUQpEaERnOUtVNHVBZWNJUkJLMjV3NzM4TTVqL3VaZVIycW9mRGhBYWFJcEdzN0I3QlI4S2NadHRBbXVCeWFDaUt2CkkzZEhDWTE3WEtQMStIK0g4WWFNUHJQWEtqOFVjZkZORDFEbXRZNVhUalY0bXlYcDdWSDd6RVF0QW9HQkFQU0UKa2hpUFZvRW05RXJjeENRVTBxK1hxQ3VpOERCZ0JMR1pyeUxPOU4weHdYWWdrZkt5Z1FpYVhKWmlqVkIxY3UzZgpmb21MUEZpZnlGeFJXcUpkcDdwWWpTTExGVGppcSt2N3JtVE40Q3dIUmdRU2F3eFN6VXRyejAvOUt5S0NodXJuCklQZTlFZzZLeWM5Y1VsV1FBcGZhYWRlalN4V1ROVkJpbDZYd2l6QjlBb0dBSVgyYVp5OFExcmdUNWpPVmJMckgKTzNIcW5hVTN2Q1dQblArTzY3K0pncWh4Y1NhTWtkOUZxdDdqS2dtOUJGREFXcWdaNXh0QUJMWklkR3NxaktKdQo2QWZJTGQvbGxxVE5XVmVxWlZid2NnZzNlMWpxM3Zmb2QxYWlxMHo0cGRaSTBwS1orY1RUNjJETWlMWFRnK1U5CjdXcFc2OUYvbTROcWRrR1MxTVhGVjVVQ2dZRUFoLytRVG82eTIyU3lMVTA2M3FLaVNEMitzSDZRdnljNGxSdFkKZUxESktwbjQ4MTNNTDBPdlZ2eWNFSnpCNG9WZ3BnTlBtdXJSWnEyQVFEQ1RpNGt4dUFoMmYycWE1Q2ZXM1lyLwpoVnVvbW5SMU1lQ1luNk1TUWllMWg5VFUvLzIvVXJtNDhYRzhzRS9yVFNVWk9qTzk3WDN5cnBoSk03Zkx5R2o5CjFiTERoL1VDZ1lBSXRjNnJQY0hXZWg0OXVpVVpxMytQYVlHNThTc0dpNnc3WnRjTjhydHVVQmJBcGxBL1VlaUoKZ0hRczNwWjRYcWdxVExMTCsydFVSbVV6bkRBVEF4NUxvNG11dWhVUU5ZTEJhcUViN01DdEw4RnpXQnZObkIzLwpLSkEwcTJBWE9VRFgyaStlQWZJZjhHNCtzTzhyeExEMEt6U1VTVkhWVk04SC82citldUtxdEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: metallb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    app.kubernetes.io/version: v0.13.7
    argocd.argoproj.io/instance: metallb
    helm.sh/chart: metallb-0.13.7
  name: webhook-server-cert
  namespace: metallb-system
type: Opaque
```

if I delete all data from the secret, the controller starts normally.
```
2023-02-01T11:13:27.959397508Z {"level":"info","ts":1675250007.959287,"msg":"Starting workers","controller":"cert-rotator","worker count":1}
2023-02-01T11:13:27.959692978Z {"level":"error","ts":1675250007.9595048,"logger":"cert-rotation","msg":"secret is not well-formed, cannot update webhook configurations","error":"Cert secret is not well-formed, missing ca.crt","errorVerbose":"Cert secret is not well-formed, missing ca.crt\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.buildArtifactsFromSecret\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:380\ngithub.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:635\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"github.com/open-policy-agent/cert-controller/pkg/rotator.(*ReconcileWH).Reconcile\n\t/go/pkg/mod/github.com/open-policy-agent/cert-controller@v0.3.0/pkg/rotator/rotator.go:637\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
2023-02-01T11:13:28.311711578Z {"level":"info","ts":1675250008.3115845,"logger":"cert-rotation","msg":"server certs refreshed"}
2023-02-01T11:13:28.311973366Z {"level":"info","ts":1675250008.3119004,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
2023-02-01T11:13:28.324497438Z {"level":"info","ts":1675250008.3244448,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
2023-02-01T11:13:28.337126783Z {"level":"info","ts":1675250008.3370569,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
2023-02-01T11:13:28.354493923Z {"level":"info","ts":1675250008.3544023,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
2023-02-01T11:13:28.364357733Z {"level":"info","ts":1675250008.3642607,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
2023-02-01T11:13:28.375018071Z {"level":"info","ts":1675250008.374944,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
2023-02-01T11:13:28.388259712Z {"level":"info","ts":1675250008.3881829,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration","name":"metallb-webhook-configuration","gvk":"admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
2023-02-01T11:13:28.397652345Z {"level":"info","ts":1675250008.3975668,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"addresspools.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
2023-02-01T11:13:28.413117526Z {"level":"info","ts":1675250008.4130027,"logger":"cert-rotation","msg":"Ensuring CA cert","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition","name":"bgppeers.metallb.io","gvk":"apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"}
2023-02-01T11:13:29.377197464Z {"level":"info","ts":1675250009.3771055,"logger":"cert-rotation","msg":"certs are ready in /tmp/k8s-webhook-server/serving-certs"}
2023-02-01T11:13:29.377248344Z {"level":"info","ts":1675250009.377161,"logger":"cert-rotation","msg":"CA certs are injected to webhooks"}
2023-02-01T11:13:29.377348616Z {"action":"webhooks enabled","caller":"webhook.go:55","level":"info","op":"startup","ts":"2023-02-01T11:13:29Z"}
2023-02-01T11:13:29.377394583Z {"level":"info","ts":1675250009.3773136,"logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called","GVK":"metallb.io/v1beta1, Kind=AddressPool"}
2023-02-01T11:13:29.377467330Z {"level":"info","ts":1675250009.3773913,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"metallb.io/v1beta1, Kind=AddressPool","path":"/validate-metallb-io-v1beta1-addresspool"}
2023-02-01T11:13:29.377581545Z {"level":"info","ts":1675250009.377507,"logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
```

**Comment by fedepaol** [comment] 2023-02-02 16:03
Sounds like a dupe of https://github.com/metallb/metallb/issues/1731

Can you try the main branch to see if that fixes it (you can probably just replace the controller tag, the parameters should be compatible).

**Comment by ArsenyBelorukov** [comment] 2023-02-03 21:58
Hi, @fedepaol,
I have the same behaviour with the helm chart from the main branch and with the controller's image tag `main`.
I don't have set resources for resources, as discussed in https://github.com/metallb/metallb/issues/1731

**Comment by pperiyasamy** [comment] 2023-02-14 11:39
Hi @ArsenyBelorukov Have you deployed helm chart on a clean `metallb-system` namespace ? Can you also send the following ?
```
kubectl get pod metallb-controller-... -n metallb-system -o yaml
kubectl logs metallb-controller-... -n metallb-system
```

**Comment by ArsenyBelorukov** [comment] 2023-03-25 13:05
Currently, I can't reproduce this behaviour. 
I suppose upgrading api-server from 1.24.7 to 1.24.12 fixed this issue.

**Closed** 2023-03-25 13:06 UTC
