### ISSUE TITLE
Assgin wrong IP after controller restarted

### ISSUE THREAD

**Issue by joy717** [metallb/metallb#1774] opened 2023-01-11 09:40 UTC
- Version of MetalLB: v0.13.7
- Version of Kubernetes: v1.24.6
- Name and version of network addon:  Calico v3.23.3
- Whether you've configured kube-proxy for iptables or ipvs mode:  ipvs

There is a race condition for assigning IP after controller restarted.

I have a pool which only contain one ip `192.168.0.2` 
And I have 2 svc. (default/svc1, default/svc2)
Assume MetalLB assigned this ip to svc1, and svc2 is pending.

Everything is ok now. (becuase there is only one IP)

If I restart the controller of MetalLB, then there is a chance that 2 svcs has the same ip `192.168.0.2`.
```
[root@k8s-1 yamls]# kubectl get svc
NAME          TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE
svc1   LoadBalancer   10.233.35.211   192.168.0.2   80:32156/TCP   6h1m
svc2   LoadBalancer   10.233.45.111   192.168.0.2   80:31718/TCP   11m
```

Although svc1 will have an event:
```
Events:
  Type     Reason             Age                 From                Message
  ----     ------             ----                ----                -------
  Normal   IPAllocated        19m (x5 over 178m)  metallb-controller  Assigned IP ["192.168.0.2"]
  Warning  svcCannotShareKey  58s (x35 over 11m)  metallb-controller  current IP not allowed by config:can't change sharing key for "default/svc1", address also in use by default/svc2: services can't share key
```

What I expected:
Controller should not assgin IPs which has been assgined.

**Comment by joy717** [comment] 2023-01-13 09:23
Here is my thought:
This problem is controller saves the IPs in memory, when restart controller,  will lost these configured IPs.
But k8s saves this IPs in etcd (service.status.loadBalancer).

Ways to solve this problem:
1.  When controller start, check all LB services, reload all configured IPs to memory.
2. Persistent this IPs

**Comment by fedepaol** [comment] 2023-01-18 14:22
This is a duplicate of https://github.com/metallb/metallb/issues/1591
We haven't released it yet

**Closed by fedepaol** 2023-01-18 14:22 UTC
