### ISSUE TITLE
Can not reach nginx from ouside cluster and only inside cluster

### ISSUE THREAD

**Issue by mfaridi1394** [metallb/metallb#2414] opened 2024-05-29 17:27 UTC
### MetalLB Version

0.14.5

### Deployment method

Manifests

### Main CNI

calico

### Kubernetes Version

1.29.5

### Cluster Distribution

kubespray

### Describe the bug

Hi friends,
I have big problem by metallb, I run nginx by helm on my cluster run on proxmox server, metallb give an ip to nginx but I can not see nginx from outside of cluster and see it only inside cluster
this is my metallb configs
`apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool`
  and 
`apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.1.20.200-10.1.20.245`
  I see this 
`NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kubernetes   ClusterIP      10.233.0.1      <none>        443/TCP                      5d22h
nginx6       LoadBalancer   10.233.33.190   10.1.20.200   80:30691/TCP,443:32351/TCP   18m`

I  can not reach 10.1.20.200 from outside cluster and use it. 
This is log of one of the speaker 
`{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node03","level":"info","ts":"2024-05-29T17:19:58Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node02","ts":"2024-05-29T17:20:05Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node02","level":"info","ts":"2024-05-29T17:20:05Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node01","ts":"2024-05-29T17:20:05Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node01","level":"info","ts":"2024-05-29T17:20:05Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node03","ts":"2024-05-29T17:20:08Z"}
{"caller":"speakerlist.go:274","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2024-05-29T17:20:08Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node03","level":"info","ts":"2024-05-29T17:20:08Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node02","ts":"2024-05-29T17:20:15Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node02","level":"info","ts":"2024-05-29T17:20:15Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node01","ts":"2024-05-29T17:20:16Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node01","level":"info","ts":"2024-05-29T17:20:16Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node03","ts":"2024-05-29T17:20:19Z"}
{"caller":"speakerlist.go:274","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2024-05-29T17:20:19Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node03","level":"info","ts":"2024-05-29T17:20:19Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node02","ts":"2024-05-29T17:20:25Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node02","level":"info","ts":"2024-05-29T17:20:25Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node01","ts":"2024-05-29T17:20:26Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node01","level":"info","ts":"2024-05-29T17:20:26Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node03","ts":"2024-05-29T17:20:29Z"}
{"caller":"speakerlist.go:274","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2024-05-29T17:20:29Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node03","level":"info","ts":"2024-05-29T17:20:29Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node02","ts":"2024-05-29T17:20:35Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node02","level":"info","ts":"2024-05-29T17:20:35Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node01","ts":"2024-05-29T17:20:36Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node01","level":"info","ts":"2024-05-29T17:20:36Z"}
{"caller":"node_controller.go:46","controller":"NodeReconciler","level":"info","start reconcile":"/dd-hetzner-root01-k8s01-node03","ts":"2024-05-29T17:20:39Z"}
{"caller":"speakerlist.go:274","level":"info","msg":"triggering discovery","op":"memberDiscovery","ts":"2024-05-29T17:20:39Z"}
{"caller":"node_controller.go:69","controller":"NodeReconciler","end reconcile":"/dd-hetzner-root01-k8s01-node03","level":"info","ts":"2024-05-29T17:20:39Z"}
`

I run this cluster on proxmox server and I made three VMs on proxmox cluster and made this cluster by kubespray.

### To Reproduce

1- I create two files 
IPAddressPool.yaml  l2Advertisement.yaml
and after that apply by kubectl 

### Expected Behavior

service get IP but can not accessible from outside cluster

### Additional Context

I check logs and I do not understand what happen 

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following I do not why I get arp command time out and how I can fix it

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by tbernacchi** [comment] 2024-06-06 01:35
same here

**Comment by fedepaol** [comment] 2024-06-06 06:51
Please follow the troubleshooting guide and all the items that were checked while filing this issue, including doing the arping test and providing logs with debug verblevel.

**Comment by fedepaol** [comment] 2024-06-06 06:51
And then try to ask for help on the #metallb slack channel, it's likely that other users will help you since this is a basic scenario.

**Comment by turnkeyautomation** [comment] 2024-06-06 07:28
Exactly same error here as well. I have VM on esxi where I have installed k8s using kubespray and have installed metal-lb using manifest file. IP is attached to ingress service but isn't accessible from outside(L2 network). 

To solve this, I had to actually use Gratuitous ARP(G-ARP) from within the VM(on which metallb is running) to advertise the attached IP manually. This is a workaround and not a correct way of advertising. 

Also, I share this on slack channel mentioned above by @fedepaol but things haven't moved there. Slack post -> https://kubernetes.slack.com/archives/C8FSTGU56/p1717529622887269

**Comment by tbernacchi** [comment] 2024-06-07 00:39
@fedepaol it's indeed a bug - (I'm still collecting all evidences). 

I was able to make it work in my scenario installing the [v0.13.11](https://metallb.universe.tf/release-notes/#version-0-13-11)  

```
helm repo add metallb https://metallb.github.io/metallb
helm install my-metallb metallb/metallb --version 0.13.11
```

**Comment by fedepaol** [comment] 2024-06-07 07:27
> @fedepaol it's indeed a bug - (I'm still collecting all evidences).
> 
> I was able to make it work in my scenario installing the [v0.13.11](https://metallb.universe.tf/release-notes/#version-0-13-11)
> 
> ```
> helm repo add metallb https://metallb.github.io/metallb
> helm install my-metallb metallb/metallb --version 0.13.11
> ```

@tbernacchi please file a separate issue, it's gonna be easier to follow as your root cause could be different from this other one.

**Comment by empereira** [comment] 2024-06-13 18:49
@tbernacchi Have you been able to collect the evidence?

I also have a similar problem, but I use BGP. And version 0.13.12 works correctly for me.
https://github.com/metallb/metallb/issues/2424

**Comment by tbernacchi** [comment] 2024-06-28 13:13
@empereira I wasn't able to get together all the evidences yet. Now my EXTERNAL-IP it's not working smooth, it's intermittent for some reason. Does your environment it's ok?

**Comment by grizzly885** [comment] 2024-06-28 13:59
Probably I had the same issue.

Raspberry Pi 5
k3s
Metallb

External IP was assigned and is accessable from the PI
From my workstation the external IP was was accessable ca 5 seconds long after exposing my service.

for me setting the used network interface into promiscuous mode fixed my issue
- "ip link set dev eth0 promisc on"
--> https://github.com/k3s-io/k3s/issues/2260

**Comment by itay47** [comment] 2024-06-30 13:11
same issue for me - IPaddressPools are assigned to Loadbalancer SVCs but traffic outside the cluster (single node)  is not reachable (no route to host).
curl -iLk https://<assigned_IP>/ -H "<expected_host_name>".
[200] ...

OS: RHEL 9.4
MetalLB Version: 0.14.5
Deployment method: Manifests (Helm)
Main CNI: calico v3.27.3
Kubernetes Version: 1.29.5
Cluster Distribution: kubespray

**it works with v0.13.12!**

**Comment by fedepaol** [comment] 2024-07-06 17:22
I am closing this issue as the original author did not follow up with the information required.
To all the others, despite the syntoms might be the same, you might be having different causes.

I'd suggest to follow the troubleshooting guide and file additional issues, trying all the suggested things before doing so.
Thanks!

**Closed by fedepaol** 2024-07-06 17:22 UTC
Labels: bug

**Comment by tbernacchi** [comment] 2024-07-15 15:04
[update] - I've moved to Cilium and everything it's fine, If anyone needs help with it just let me know, I'm in the [cilium.slack.com](cilium.slack.com) slack channel.

**Comment by lnnt** [comment] 2024-08-30 14:34
same here
I'm using Flannel. **It works with v0.13.12!**
