### ISSUE TITLE
MetalLB assigns an IP Address to a Nginx Ingress Controller but the site cannot be reached  I can't ping this address

### ISSUE THREAD

**Issue by pptfz** [metallb/metallb#2214] opened 2023-12-14 04:21 UTC
### MetalLB Version

v0.13.12

### Deployment method

Charts

### Main CNI

flannel v0.23.0

### Kubernetes Version

v1.28.2

### Cluster Distribution

kubeadm install

### Describe the bug

Install ingress-nginx by running the following command
```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace
```

The svc EXTERNAL-IP whose name is ingress-nginx-controller and type is loadbalancer is in pending state
```
$ kubectl -n ingress-nginx get all
NAME                                            READY   STATUS    RESTARTS   AGE
pod/ingress-nginx-controller-5865555b87-t6c4f   1/1     Running   0          3m2s

NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
service/ingress-nginx-controller             LoadBalancer   10.107.37.98    <pending>     80:32654/TCP,443:32694/TCP   3m3s
service/ingress-nginx-controller-admission   ClusterIP      10.104.192.71   <none>        443/TCP                      3m3s

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ingress-nginx-controller   1/1     1            1           3m2s

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/ingress-nginx-controller-5865555b87   1         1         1       3m2s
```

Install metallb with the following command
```
$ helm repo add metallb https://metallb.github.io/metallb
$ helm install metallb metallb/metallb
```

View installation
```
$ kubectl get all
NAME                                      READY   STATUS    RESTARTS       AGE
pod/metallb-controller-5f9bb77dcd-62mhg   1/1     Running   1 (34m ago)    34m
pod/metallb-speaker-5h68v                 4/4     Running   2 (115s ago)   34m
pod/metallb-speaker-d9g9m                 4/4     Running   4 (73s ago)    34m

NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/metallb-webhook-service   ClusterIP   10.98.244.197   <none>        443/TCP   34m

NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/metallb-speaker   2         2         2       2            2           kubernetes.io/os=linux   34m

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/metallb-controller   1/1     1            1           34m

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/metallb-controller-5f9bb77dcd   1         1         1       34m
```

Create the following resources
```
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  #- 203.0.113.10-203.0.113.15
  - 10.0.0.100-10.0.0.105
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default
```

View the svc in the ingress-nginx namespace  You can see that the ip address is obtained
```
$ kubectl -n ingress-nginx get svc
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.107.37.98    10.0.0.100    80:32654/TCP,443:32694/TCP   41m
ingress-nginx-controller-admission   ClusterIP      10.104.192.71   <none>        443/TCP                      41m
```

But the address cannot be pinged
```
$ ping 10.0.0.100
PING 10.0.0.100 (10.0.0.100) 56(84) bytes of data.
From 10.0.0.10 icmp_seq=1 Destination Host Unreachable
From 10.0.0.10 icmp_seq=5 Destination Host Unreachable
From 10.0.0.10 icmp_seq=6 Destination Host Unreachable
^C
--- 10.0.0.100 ping statistics ---
8 packets transmitted, 0 received, +3 errors, 100% packet loss, time 7183ms
pipe 4
```

stackoverflow Another person  [The same problem](https://stackoverflow.com/questions/77636803/metallb-assigns-an-ip-address-to-a-nginx-ingress-controller-but-the-site-cannot)

### To Reproduce

Follow the official documents exactly

### Expected Behavior

I should be able to ping through the ip address that I got from metallb

### Additional Context

Experimental environment mac A virtual machine installed locally through pd

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my issue is not there.
- [X] This bug is reproducible when deploying MetalLB from the main branch
- [X] I have read the [troubleshooting guide](https://metallb.universe.tf/troubleshooting/) and I am still not able to make it work
- [X] I checked the logs and MetalLB is not discarding the configuration as not valid
- [X] I enabled the debug logs, collected the information required from the cluster using the [collect script](https://raw.githubusercontent.com/metallb/metallb/main/troubleshooting/collect.sh) and will attach them to the issue
- [X] I will provide the definition of my service and the related endpoint slices and attach them to this issue

**Comment by fedepaol** [comment] 2023-12-14 09:05
It's described in the troubleshooting you asserted to have read out:
https://metallb.universe.tf/troubleshooting/#general-concepts

**please be aware that pinging the service IP won’t work.**

Closing the issue as not a bug

**Closed by fedepaol** 2023-12-14 09:05 UTC
Labels: bug

**Comment by tbernacchi** [comment] 2024-06-05 15:19
same here, and I'm not pinging
