### ISSUE TITLE
V0.11.0: Internal IPs instead of external IPs. In V0.9.3 it was working

### ISSUE THREAD

**Issue by CoreTechnologyAG** [metallb/metallb#1178] opened 2022-01-20 17:08 UTC
Hello

We have a problem with 0.11.0-Release. 

We tried to migrate from 0.9.3 to 0.11.0 and had to go back.

Problem:
We got an internal IP in the Mailserver- and in Traefik-Logs. Therefore those containers are responding incorrect because of the internal IP-Addresses (e.g. ipwhitelist in traefik cannot work correct) 

Reproduce:
- Install metallb via standard https://raw.githubusercontent.com/metallb/metallb/v0.11.0/manifests/metallb.yaml. The only thing we changed, are the namespaces.
- Install Traefik and a Middleware  ipwhitelist-config
- Install mailu (Mailserver) and here we got an openrelay issue, because metallb sends in 0.11.0 the internal IP and not the external IP

metallb Version 0.9.3 (everything works as expected)
Mail-Server-Log mailu
10.244.3.54 - - [05/Jan/2022:08:17:50 +0000] "GET /.well-known/acme-challenge/kuAs8hxL2RQS99QZsz_NR6YWVaXLpzvexH7UUXtIjTU HTTP/1.1" 404 196 "-" "cert-manager/v1.5.4 (clean)"
10.244.4.1 - - [05/Jan/2022:08:17:51 +0000] "GET /health HTTP/1.1" 204 0 "-" "kube-probe/1.23"
2022/01/05 08:17:53 [info] 12#12: *23931 client 18.205.72.90:13359 connected to 0.0.0.0:25						<<<<<<<< client IP = extneral IP from mxtoolbox 18.205.72.90

Traefik ipwhitelist
178.197.217.209 - - [05/Jan/2022:08:20:35 +0000] "GET /favicon.ico HTTP/1.1" 404 19 "-" "-" 14413 "-" "-" 0ms   <<<<<<<<<<< Client IP = 178.197.217.209 = Mobile-Device IP

metallb Version 0.11.0
Request:
how to we have to configure metallb 0.11.0, so we got the external IP again?

Infrastructure:
- Ubuntu 20.04
- Kubernetes V1.23.1 (latest)
- Metallb 0.9.3 (working correct), 0.11.0 (latest) Problems as mentioned
- kube-router v1.3.2 (latest)
- traefik: V2.5.6  (latest)

Thanks in advance
Ritzo

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata: 
  name: ipwhitelist-custom
  namespace: system-ingress
spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.0/32
      # new rz2 network range
      - 10.2.32.0/19
      # external IP-Ranges will be blocked

**Comment by fedepaol** [comment] 2022-01-20 17:17
Not sure what you mean by internalip.

Is the issue the ip assigned to the service by metallb? Or something else?
Can you share the metallb configuration and the loadbalancer service?

**Comment by fedepaol** [comment] 2022-01-21 16:41
The only ip metallb handles is the one that gets assigned to the traefik service (in this case `10.2.235.33`).

Is traefik_service_def.yaml.txt the output of a file, or of `kubectl get service -o yaml` ? If it is the file, can you provide the output of the command?

If it is from the command, can you provide the logs of the metallb's controller pod?

**Comment by CoreTechnologyAG** [comment] 2022-01-24 16:54
I will come back to you on thursday/friday this week..
need some more time to document the situation with v0.9.3 and v0.11..  sorry

**Comment by CoreTechnologyAG** [comment] 2022-01-28 09:18
My test I had to do with our test infra. So internal IP has changed.

- MetalLB/Traefik-Loadbalancer-IP: 10.2.33.33

**Analysis myself:**
in the traefik-log it's not the external ip-address from the client. It is the ip-Adresse of the kubernetes master (in our case the 2nd master node-ip) in the traefik-log.
In the metallb speaker and controller logs I don't see a lot. Even I have set the log-level = all

### V0.10.3: Traefik works correct
traefik-Log: External access to https://plantuml.dev1.kub.core.ch/  via iPhone: Ext-IP: 194.230.148.220

`**_194.230.148.220_** - - [28/Jan/2022:07:28:33 +0000] "GET / HTTP/1.1" 403 9 "-" "-" 1870 "plantuml-extern-ct-dev-plantuml-m-plantuml-dev1-kub-core-ch@kubernetes" "-" 0ms`

In the Attachment Documents beginning with V0.10.3 belongs to this release

### V0.11.0: Traefik works incorrect because of "internal"-IP
traefik-Log with V0.11.0: External access to http://plantuml.dev1.kub.core.ch/ via iPhone: Ext-IP: It is not 194.230.148.220 in the traefic-log, it's 10.2.50.22 = Kubernetes-Master-IP second node

`**_10.2.50.22_** - - [28/Jan/2022:08:19:07 +0000] "GET /uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 HTTP/1.1" 200 3218 "-" "-" 2656 "plantuml-extern-ct-dev-plantuml-m-plantuml-dev1-kub-core-ch@kubernetes" "http://10.244.4.237:8080" 5ms`

In the Attachment Documents beginning with V0.11.0 belongs to this release

**div Logs testing with metallb V0.10.3**
[V0.10.3-GetEndpoints.txt](https://github.com/metallb/metallb/files/7957212/V0.10.3-GetEndpoints.txt)
[V0.10.3-GetServiceOnlyExternalIP.txt](https://github.com/metallb/metallb/files/7957213/V0.10.3-GetServiceOnlyExternalIP.txt)
[V0.10.3-MetalLBController.log.txt](https://github.com/metallb/metallb/files/7957214/V0.10.3-MetalLBController.log.txt)
[V0.10.3-MetalLBSpeaker.log.txt](https://github.com/metallb/metallb/files/7957201/V0.10.3-MetalLBSpeaker.log.txt)
[V0.10.3-TraefikExternLog20220128.txt](https://github.com/metallb/metallb/files/7957203/V0.10.3-TraefikExternLog20220128.txt)

**div Logs testing with metallb V0.11.0**
[V0.11.0-GetEndpoints.txt](https://github.com/metallb/metallb/files/7957204/V0.11.0-GetEndpoints.txt)
[Kubernetes-Master-Server-IP: 10.2.50.22: V0.11.0-GetPodWithIP10.2.50.22.txt](https://github.com/metallb/metallb/files/7957205/V0.11.0-GetPodWithIP10.2.50.22.txt)
[V0.11.0-GetServiceOnlyExternalIP.txt](https://github.com/metallb/metallb/files/7957206/V0.11.0-GetServiceOnlyExternalIP.txt)
[V0.11.0-MetalLBController.log.txt](https://github.com/metallb/metallb/files/7957207/V0.11.0-MetalLBController.log.txt)
[V0.11.0-MetalLBSpeaker.log.txt](https://github.com/metallb/metallb/files/7957208/V0.11.0-MetalLBSpeaker.log.txt)
[V0.11.0-TraefikExternLog20220128.txt](https://github.com/metallb/metallb/files/7957209/V0.11.0-TraefikExternLog20220128.txt)

**yaml-definitions**
[traefik_service_def_kubectlGetServ-DevSystem.yaml.txt: from command kubectl get service -n system-ingress-extern traefik -o yaml](https://github.com/metallb/metallb/files/7957246/traefik_service_def_kubectlGetServ-DevSystem.yaml.txt)
[ConfigMap-DevSystem.yaml.txt](https://github.com/metallb/metallb/files/7957210/ConfigMap-DevSystem.yaml.txt)
[HELM-Chart: traefik-DevSystem.yaml.txt](https://github.com/metallb/metallb/files/7957211/traefik-DevSystem.yaml.txt)

**Website-Access forbidden = ok**
![V0 10 3-WebsiteAccessPlant_correct](https://user-images.githubusercontent.com/7665561/151517406-221133f0-6b0e-4678-a4ab-691ade7c29da.PNG)



**Website-Access is shown, but it should not be accessibale. So it's not ok**
![V0 11 0-WebsiteAccessPlant_wrong](https://user-images.githubusercontent.com/7665561/151517409-cb1f5574-123e-445d-be3e-967a4365e2fa.PNG)

**Comment by fedepaol** [comment] 2022-01-28 09:33
> ### V0.10.3: Traefik works correct
> 
> traefik-Log: External access to https://plantuml.dev1.kub.core.ch/ via iPhone: Ext-IP: 194.230.148.220
> 
> `**_194.230.148.220_** - - [28/Jan/2022:07:28:33 +0000] "GET / HTTP/1.1" 403 9 "-" "-" 1870 "plantuml-extern-ct-dev-plantuml-m-plantuml-dev1-kub-core-ch@kubernetes" "-" 0ms`
> 
> In the Attachment Documents beginning with V0.10.3 belongs to this release
> ### V0.11.0: Traefik works incorrect because of "internal"-IP
> 
> traefik-Log with V0.11.0: External access to http://plantuml.dev1.kub.core.ch/ via iPhone: Ext-IP: It is not 194.230.148.220 in the traefic-log, it's 10.2.50.22 = Kubernetes-Master-IP second node
> 
> `**_10.2.50.22_** - - [28/Jan/2022:08:19:07 +0000] "GET /uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000 HTTP/1.1" 200 3218 "-" "-" 2656 "plantuml-extern-ct-dev-plantuml-m-plantuml-dev1-kub-core-ch@kubernetes" "http://10.244.4.237:8080" 5ms`
> 

Sorry, but I am still missing some details and I don't know how traefik works. What are 194.230.148.220 and 10.2.50.22 ? The source ip of the request? Is that the issue?

**Comment by CoreTechnologyAG** [comment] 2022-01-28 10:16
Sorry, from my side.

Yes, the source IP of the request should be transfered from metallb to the services/pods, which run behind metallb.

Is there a way to configure metallb's new version v0.11.0, that it behaves like v.0.10.3?
 
**try to explain how traefik decides:**
Definition:
- In traefik we have defined a whitelist with ip-ranges. If the client-ip in this ip-whitelist-ranges exists, access is allowed, otherwise access is denied.
- In the whitelist are all internal-ip ranges mentioned incl. kubernetes service-ip-range and pod-ip-range.

**V0.10.3**
Now if we work with V0.10.3: traefik got the "real" external IP like 194.230.148.220. In this case it's a mobile ip-address from a telco provider.

**V0.11.0**
If we work with V0.11.0: traefik got the IP 10.2.50.22, which is the internal IP-Address from the kubernetes master node and not the real ip-number from the client device, which would be 194.230.148.220.

**Because of this, traefik decides wrong.**

Another examples is with postfix and smtp. Here we will run into an open relay problem

**Comment by fedepaol** [comment] 2022-01-28 10:29
Ok, now I think I understand what the issue is.
With 0.11.0, we fixed Cluster Traffic policy on services, meaning that a request entering one node may end up being served by a pod on a different node. See https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies

So, the obvious fix to this is to change the service to use ExternalTrafficPolicy: local

**Comment by CoreTechnologyAG** [comment] 2022-01-28 11:23
Thanks for the info.
I will try this in the next days.

**Comment by CoreTechnologyAG** [comment] 2022-02-03 11:11
It works.
Reconfigure the traefik-configuration and now I see the external IP.

Maybe you should mention this in the release notes of V.0.11.0. as well the part with the ExternalTrafficPolicy: local :-)

Thanks a lot.

**Comment by fedepaol** [comment] 2022-02-03 11:42
Yeah will change that. It's a "secondary" effect of having the policy local, did not think it would have effects on applications.
Closing the issue, glad it helped.

**Closed by fedepaol** 2022-02-03 11:42 UTC
Labels: need-more-info
