### ISSUE TITLE
Possible multipath bug with FRR Peer.

### ISSUE THREAD

**Issue by jonwilliams84** [metallb/metallb#1139] opened 2021-12-21 10:15 UTC
I think I may have found a bug with multi-path (Cluster ExternalTrafficPolicy) when peered with FRR AS. Hopefully this doesn't turn into a config troubleshooting post, that is not my intention. 

Cluster:  8 x Nodes running K3s. (host IPs=10.32.100.15-22)
Router: UDMPro + FRR pod (host IP= 10.32.100.1)

Current FRR BGP configuration:
```
!
frr version 8.1_git
frr defaults traditional
hostname UDM-Pro
domainname localdomain
log stdout
!
password zebra
!
router bgp 64588
 bgp router-id 10.32.100.1
 neighbor V4 peer-group
 neighbor V4 remote-as 64500
 neighbor V4 password zebra
 neighbor V4 capability dynamic
 neighbor 10.32.100.15 peer-group V4
 neighbor 10.32.100.16 peer-group V4
 neighbor 10.32.100.17 peer-group V4
 neighbor 10.32.100.18 peer-group V4
 neighbor 10.32.100.19 peer-group V4
 neighbor 10.32.100.20 peer-group V4
 neighbor 10.32.100.21 peer-group V4
 neighbor 10.32.100.22 peer-group V4
 !
 address-family ipv4 unicast
  network 10.32.100.0/25
  redistribute connected route-map ALLOW-ALL
  neighbor V4 next-hop-self
  neighbor V4 soft-reconfiguration inbound
  neighbor V4 route-map ALLOW-ALL in
  neighbor V4 route-map ALLOW-ALL out
 exit-address-family
exit
!
route-map ALLOW-ALL permit 10
exit
!
end
```

Current Metallb Config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
  config: |
    peers:
    - peer-address: 10.32.100.1
      peer-asn: 64588
      my-asn: 64500
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.0.8.0/24
      avoid-buggy-ips: true
      bgp-advertisements:
      - aggregation-length: 32
        localpref: 100
        communities:
        - no-advertise
      - aggregation-length: 24
    bgp-communities:
      no-advertise: 65535:65282
```

When I create an LB (either Cluster or Local ExternalTrafficPolicy) and check the bgp table on the FRR container, I can see the route being picked up, both the /24 and the /32 multi/single path routes:
```
BGP table version is 67, local router ID is 10.32.100.1, vrf id 0
Default local pref 100, local AS 64588
Status codes:  s suppressed, d damped, h history, * valid, > best, = multipath,
               i internal, r RIB-failure, S Stale, R Removed
Nexthop codes: @NNN nexthop's vrf id, < announce-nh-self
Origin codes:  i - IGP, e - EGP, ? - incomplete
RPKI validation codes: V valid, I invalid, N Not found

   Network          Next Hop            Metric LocPrf Weight Path
...
*= 10.0.8.0/24      10.32.100.15                           0 64500 ?
*=                  10.32.100.16                           0 64500 ?
*=                  10.32.100.19                           0 64500 ?
*=                  10.32.100.18                           0 64500 ?
*=                  10.32.100.20                           0 64500 ?
*=                  10.32.100.21                           0 64500 ?
*=                  10.32.100.22                           0 64500 ?
*>                  10.32.100.17                           0 64500 ?
*= 10.0.8.1/32      10.32.100.15                           0 64500 ?
*=                  10.32.100.17                           0 64500 ?
*=                  10.32.100.21                           0 64500 ?
*=                  10.32.100.16                           0 64500 ?
*=                  10.32.100.19                           0 64500 ?
*=                  10.32.100.20                           0 64500 ?
*=                  10.32.100.18                           0 64500 ?
*>                  10.32.100.22                           0 64500 ?
*> 10.0.8.2/32      10.32.100.16                           0 64500 ?
...
```

However the full route table shows the route as failed/rejected unless the `ExternalTrafficPolicy` is set to Local (in the case of 10.0.8.2):
```
B>r 10.0.8.0/24 [20/0] via 10.32.100.15, br0, weight 1, 3d09h35m
  r                    via 10.32.100.16, br0, weight 1, 3d09h35m
  r                    via 10.32.100.17, br0, weight 1, 3d09h35m
  r                    via 10.32.100.18, br0, weight 1, 3d09h35m
  r                    via 10.32.100.19, br0, weight 1, 3d09h35m
  r                    via 10.32.100.20, br0, weight 1, 3d09h35m
  r                    via 10.32.100.21, br0, weight 1, 3d09h35m
  r                    via 10.32.100.22, br0, weight 1, 3d09h35m
B>r 10.0.8.1/32 [20/0] via 10.32.100.15, br0, weight 1, 3d09h35m
  r                    via 10.32.100.16, br0, weight 1, 3d09h35m
  r                    via 10.32.100.17, br0, weight 1, 3d09h35m
  r                    via 10.32.100.18, br0, weight 1, 3d09h35m
  r                    via 10.32.100.19, br0, weight 1, 3d09h35m
  r                    via 10.32.100.20, br0, weight 1, 3d09h35m
  r                    via 10.32.100.21, br0, weight 1, 3d09h35m
  r                    via 10.32.100.22, br0, weight 1, 3d09h35m
B>* 10.0.8.2/32 [20/0] via 10.32.100.16, br0, weight 1, 1d15h54m
```

If I change a Cluster service to `Local` - the route gets advertised correctly.

Interestingly - If I change it back to `Cluster` mode, the route stays advertised, but if I move (kill) the pod so it runs on a different node the route is cleared from the table and I can no longer route to it, until I change it to `Local` again.

As another note, I have tested the same MetalLB config peered with a Fortigate and it works flawlessly "out of the box."

Any thoughts?

**Comment by jonwilliams84** [comment] 2021-12-21 11:56
I have tested this with a simpler BGP conf below and confirm I still never get the multi-path routes advertised:
```
Current configuration:
!
frr version 8.1_git
frr defaults traditional
hostname UDM-Pro
domainname localdomain
!
router bgp 64588
 bgp router-id 10.32.100.1
 bgp log-neighbor-changes
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 neighbor metallb peer-group
 neighbor metallb remote-as 64500
 neighbor 10.32.100.15 peer-group metallb
 neighbor 10.32.100.16 peer-group metallb
 neighbor 10.32.100.17 peer-group metallb
 neighbor 10.32.100.18 peer-group metallb
 neighbor 10.32.100.19 peer-group metallb
 neighbor 10.32.100.20 peer-group metallb
 neighbor 10.32.100.21 peer-group metallb
 neighbor 10.32.100.22 peer-group metallb
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor metallb soft-reconfiguration inbound
 exit-address-family
exit
!
end
```

**Comment by jonwilliams84** [comment] 2021-12-21 13:14
Ok...Found the issue!!!  FRR config and MetalLB config were fine and there is no bug!

It was the kernel on the UDM Pro. It doesn't support multi-path routing! So I have installed a custom kernel and enabled multi-path routing!! Whoop:

```
B>* 10.0.8.0/24 [20/0] via 10.32.100.15, br0, weight 1, 00:02:12
  *                    via 10.32.100.16, br0, weight 1, 00:02:12
  *                    via 10.32.100.17, br0, weight 1, 00:02:12
  *                    via 10.32.100.21, br0, weight 1, 00:02:12
  *                    via 10.32.100.22, br0, weight 1, 00:02:12
B>* 10.0.8.1/32 [20/0] via 10.32.100.22, br0, weight 1, 00:02:12
B>* 10.0.8.2/32 [20/0] via 10.32.100.16, br0, weight 1, 00:02:16
B>* 10.0.8.3/32 [20/0] via 10.32.100.15, br0, weight 1, 00:02:16
B>* 10.0.8.4/32 [20/0] via 10.32.100.21, br0, weight 1, 00:02:12
  *                    via 10.32.100.22, br0, weight 1, 00:02:12
B>* 10.0.8.5/32 [20/0] via 10.32.100.22, br0, weight 1, 00:02:12
B>* 10.0.8.6/32 [20/0] via 10.32.100.17, br0, weight 1, 00:02:16
```

**Comment by fedepaol** [comment] 2021-12-21 16:31
Thanks for informing us @jonwilliams84 ! I am gonna close the issue as it looks like it wasn't a metallb issue

**Closed by fedepaol** 2021-12-21 16:31 UTC

**Comment by Trackhe** [comment] 2022-08-18 11:47
@jonwilliams84 for the UDM-Pro the multipath support get patched. But is that working noe without the modification of the kernel?

**Comment by jonwilliams84** [comment] 2022-08-18 12:14
> @jonwilliams84 for the UDM-Pro the multipath support get patched. But is that working now without the modification of the kernel?

I have no idea, I am still running patched kernel.  Where did you see that it had been patched?

**Comment by Trackhe** [comment] 2022-08-18 12:29
Hm i don't find the release notes for that anymore, but i maintain a second UDM-Pro for my Parents, and they watch IPTV over Magenta, which needs the IGMP Proxy, and that needs the multipath support on the Kernel, since 5-12 month i can run this without a custom kernel (maybe from release 1.11 or somthing like that). And since a few days say released also IGMP Support but i wasnt able to test it actually. So i m working at home on the Metallb/k8s/multiarch and FRR/BGP/UDM-PRO combo on the original Kernel.

**Comment by Trackhe** [comment] 2022-08-18 12:33
I found it.. 

https://github.com/fabianishere/udm-iptv
https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-0/eef95803-6976-499b-9169-bf6dfbbcc209

> UniFi Dream Machine (Pro): Multicast routing is supported natively in the stock kernel since [firmware version 1.11](https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-0/eef95803-6976-499b-9169-bf6dfbbcc209). If you for some reason cannot use firmware v1.11+, see [udm-kernel](https://github.com/fabianishere/udm-kernel) for a kernel that supports multicast routing for older firmware versions of the UDM/P.

**Comment by jonwilliams84** [comment] 2022-08-18 12:54
> I found it..
> 
> https://github.com/fabianishere/udm-iptv https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-0/eef95803-6976-499b-9169-bf6dfbbcc209
> 
> > UniFi Dream Machine (Pro): Multicast routing is supported natively in the stock kernel since [firmware version 1.11](https://community.ui.com/releases/UniFi-OS-Dream-Machines-1-11-0/eef95803-6976-499b-9169-bf6dfbbcc209). If you for some reason cannot use firmware v1.11+, see [udm-kernel](https://github.com/fabianishere/udm-kernel) for a kernel that supports multicast routing for older firmware versions of the UDM/P.
> 
> but i confused multipath with multicast

Ah...yeah, multi-cast is working...multi path not so much then ;-)

**Comment by Trackhe** [comment] 2022-08-18 13:21
With the newest version: 
`2022/08/18 13:18:24 ZEBRA: [NNACN-54BDA][EC 4043309110] Disabling MPLS support (no kernel support).`
Not working with the official kernel confirmed

**Comment by issmirnov** [comment] 2023-01-10 04:13
@jonwilliams84 

I want to express my PROFOUND gratitude to you for this solution. I have been banging my head on the wall for the past 2 months trying to understand how I'm managing to mess up 15 lines of BGP config. Turns out it wasn't the config or metallb, but the damn UDM kernel of all things. 🤯 

I'm shocked this isn't part of the default kernel, but I'm also very thankful that a workaround exists. I can confirm that installing the latest custom kernel on the latest UDM firmware works fine, and instantly all routes are happily accepted.
