### ISSUE TITLE
Liveness probe fails for frr container

### ISSUE THREAD

**Issue by ArturoGuerra** [metallb/metallb#1926] opened 2023-05-06 22:03 UTC
MetalLB Version: 0.13.9
Kubernetes Version: 1.27.1 (kubeadm if that matters)
Network Addon: Calico VXLan mode
Deployment Mode: FRR
The issue first started on metallb version: 0.13.7

When deploying Metallb using kustomize I'm encountering an issue causing all speakers to be restarted due to the frr container failing its startup probes and liveness probes. The root cause appears to be that the endpoint it's trying to ping (127.0.0.1:7473/livez) is returning a 404.

https://github.com/metallb/metallb/blob/0403ddab603b1580d0603f483cd19961201b193b/config/frr/speaker-patch.yaml#L81-L92
https://github.com/metallb/metallb/blob/0403ddab603b1580d0603f483cd19961201b193b/charts/metallb/templates/speaker.yaml#L361-L374
https://github.com/metallb/metallb/blob/0403ddab603b1580d0603f483cd19961201b193b/config/manifests/metallb-frr.yaml#L1927C11-L1946
https://i.arturonet.com/gYsptvyIl6.png

**Comment by fedepaol** [comment] 2023-05-08 11:45
Can you provide the logs of the reloader container and a -o yaml of the speaker pod?

**Comment by 2fst4u** [comment] 2023-06-01 09:58
I seem to be getting this now too. My frr container never becomes healthy for this reason.

**Comment by fedepaol** [comment] 2023-06-01 10:05
@2fst4u so it's not because of the low timeout?
Can you provide the logs collected with https://github.com/metallb/metallb/blob/main/troubleshooting/collect.sh
?

**Comment by 2fst4u** [comment] 2023-06-01 10:08
> @2fst4u so it's not because of the low timeout?
> Can you provide the logs collected with https://github.com/metallb/metallb/blob/main/troubleshooting/collect.sh
> ?

Which logs would you need? The container logs themselves don't show anything (I don't think) because at the application level it seems to run as intended. This can be proven by turning off all the probes completely.

It seems the liveness probe is causing kubernetes to just kill the pod and never mark it as ready. Are there any kubernetes logs itself that could help?

**Comment by fedepaol** [comment] 2023-06-01 10:10
the liveness probe hits the frrmetrics container which checks if the frr daemons are running, afair.
So those are the logs I'd need, but just run the script and let it collect everything.

**Comment by ArturoGuerra** [comment] 2023-06-01 22:10
Sorry haven't been home ill send the logs in a bit, but idk how useful they'll be since it appears it's trying to hit an endpoint that doesn't exist at all

**Comment by ArturoGuerra** [comment] 2023-06-01 23:54
[metallb_report.zip](https://github.com/metallb/metallb/files/11630675/metallb_report.zip)
I replaced 2 of the 3 nodes recently and it looks like its working properly on those nodes

**Comment by ArturoGuerra** [comment] 2023-06-02 01:46
I re-pulled all the images and it fixed the issue, I'm guessing it was `quay.io/metallb/speaker:main` since it's the only image that doesn't have a version tag

**Comment by ArturoGuerra** [comment] 2023-06-02 20:39
is there a reason for having this set to the main tag instead of a specific release? https://github.com/metallb/metallb/blob/e708fc9010afb80c379bdfadd5d543931164ca5e/config/frr/speaker-patch.yaml#LL41C16-L41C16

**Comment by fedepaol** [comment] 2023-06-05 07:33
> is there a reason for having this set to the main tag instead of a specific release? https://github.com/metallb/metallb/blob/e708fc9010afb80c379bdfadd5d543931164ca5e/config/frr/speaker-patch.yaml#LL41C16-L41C16

oh, good catch. That is a mistake. Luckily, the compontents being copied by those containers are pretty stable and shouldn't cause any issues. But we need to fix it.
The "main" speaker container (the one which holds the logic) is tagged properly.
https://github.com/metallb/metallb/blob/v0.13.10/config/controllers/speaker.yaml#L48

**Comment by fedepaol** [comment] 2023-06-05 07:40
Filed https://github.com/metallb/metallb/issues/1969 to track this.

**Comment by fedepaol** [comment] 2023-06-12 08:08
Closing this as using latest fixed the issue

**Closed by fedepaol** 2023-06-12 08:08 UTC
