### ISSUE TITLE
No ARP announcement for Windows Containers

### ISSUE THREAD

**Issue by szentesik** [metallb/metallb#954] opened 2021-09-16 15:06 UTC
I have a 2 node cluster, 1x Debian 10 as control + worker, 1x Windows Server 2019 as worker.

Services with only Windows containers behind are not answering on service Ip from the extern (This would be my desired use-case). 
Linux services are working fine (or even mixed container services, one Linux container starts the show). arp -a and arping shows that the head node listens on the service IP correctly.
Kubectl show no problem, node ports are working fine for all nodes for all services. 

My analysis ends at that speaker not starts announcing the service if it has no Linux endpoint.

Logs: adding a Linux service:
`[speaker-h5tsh] {"caller":"main.go:215","event":"startUpdate","msg":"start of service update","service":"database/pgadmin","ts":"2021-09-16T14:3                    1:11.654595927Z"}
[speaker-h5tsh] {"caller":"main.go:224","event":"endUpdate","msg":"end of service update","service":"database/pgadmin","ts":"2021-09-16T14:31:11                    .654729326Z"}
[speaker-h5tsh] {"caller":"main.go:215","event":"startUpdate","msg":"start of service update","service":"database/pgadmin","ts":"2021-09-16T14:3                    1:11.6589393Z"}
[speaker-h5tsh] {"caller":"main.go:287","event":"serviceAnnounced","ip":"192.168.26.210","msg":"service has IP, announcing","pool":"my-ip-space"                    ,"protocol":"layer2","service":"database/pgadmin","ts":"2021-09-16T14:31:11.661348286Z"}
[speaker-h5tsh] {"caller":"main.go:290","event":"endUpdate","msg":"end of service update","service":"database/pgadmin","ts":"2021-09-16T14:31:11                    .664181168Z"}
[speaker-h5tsh] {"caller":"main.go:215","event":"startUpdate","msg":"start of service update","service":"database/pgadmin","ts":"2021-09-16T14:3                    1:11.679144577Z"}
[speaker-h5tsh] {"caller":"main.go:287","event":"serviceAnnounced","ip":"192.168.26.210","msg":"service has IP, announcing","pool":"my-ip-space"                    ,"protocol":"layer2","service":"database/pgadmin","ts":"2021-09-16T14:31:11.679840673Z"}
[speaker-h5tsh] {"caller":"main.go:290","event":"endUpdate","msg":"end of service update","service":"database/pgadmin","ts":"2021-09-16T14:31:11                    .679919272Z"}`

Logs: adding a Windows service:
`[speaker-h5tsh] {"caller":"main.go:215","event":"startUpdate","msg":"start of service update","service":"default/gorest","ts":"2021-09-16T14:37:59.024456632Z"}
[speaker-h5tsh] {"caller":"main.go:224","event":"endUpdate","msg":"end of service update","service":"default/gorest","ts":"2021-09-16T14:37:59.024705031Z"}
[speaker-h5tsh] {"caller":"main.go:215","event":"startUpdate","msg":"start of service update","service":"default/gorest","ts":"2021-09-16T14:37:59.030800393Z"}
[speaker-h5tsh] {"caller":"main.go:268","event":"endUpdate","msg":"end of service update","service":"default/gorest","ts":"2021-09-16T14:37:59.032613281Z"}
[speaker-h5tsh] {"caller":"main.go:215","event":"startUpdate","msg":"start of service update","service":"default/gorest","ts":"2021-09-16T14:37:59.041401127Z"}
[speaker-h5tsh] {"caller":"main.go:268","event":"endUpdate","msg":"end of service update","service":"default/gorest","ts":"2021-09-16T14:37:59.041461226Z"}`

MetalLB: 0.10.2, ipvs
K8S: 1.21.4 (KubeAdm)
network: Flannel 0.14.0 VXLAN
[Guide at https://medium.com/@JockDaRock/kubernetes-metal-lb-for-on-prem-baremetal-cluster-in-10-minutes-c2eaeb3fe813
and docu at https://metallb.universe.tf/installation/#installation-by-manifest was used to deploy.]

Please let me know if any further details or logs are needed or I should test again with some other environment.

**Comment by fedepaol** [comment] 2021-09-17 12:54
Hi, I believe because MetalLB currently requires to have both a speaker AND and endpoint running on a given node in order to be able to announce from it.

The speaker daemonset has a [linux only](https://github.com/metallb/metallb/blob/dae0dc0d1998a49cb623ca786d63810c43e33702/manifests/metallb.yaml#L387) node selector, so if your endpoint is running only on windows note it won't work.

Loosening that selector won't work either I am afraid, the speaker assumes some unix-ness of the underlying filesystem (see https://github.com/metallb/metallb/blob/5d236989e61683daf1eaad00777b81ce7dd98c5d/internal/layer2/announcer.go#L76 )

Loosening the requirement of having the speaker and the endpoint on the same node is part of [this proposal](https://github.com/metallb/metallb/pull/942/files#diff-da12e30c79612eec28b7649f676c81535527552e304289ce34b5877ebb06c1ddR216) .

Hope this helps

**Comment by fedepaol** [comment] 2021-09-17 16:46
Closing this as duplicate of https://github.com/metallb/metallb/issues/302

**Closed by fedepaol** 2021-09-17 16:46 UTC

**Comment by szentesik** [comment] 2021-09-19 13:08
Thanks for your help, using the magic one-liner from **_layer2: fallback speaker election if no endpoints are in nodes with speaker daemonset_** #665 helped me to use metalLB for my mixed cluster, waiting for the official solution. 
(My image, own risk only: _kubectl set image -n metallb-system daemonset speaker speaker=docker.io/szentesik/metallb-speaker:0.10.3-beta-winsupport_)
