### ISSUE TITLE
Auto-assign: false doesn't work with Layer 2

### ISSUE THREAD

**Issue by Cspellz** [metallb/metallb#599] opened 2020-05-08 11:28 UTC
Hi team, 

I am using Kubernetes 1.18 and MetalLb 0.9.3.

I am using Layer 2 mode and I am unable to assign a specific IP to a service even though I map an IP to it in the services yaml file.
Also when I set the auto-assign to false in the config file, it gets stuck at pending and an error as shown below. Doesn't this feature not work with Layer 2 mode. 

  Warning  AllocationFailed  29s   metallb-controller  Failed to allocate IP for "app-service-lb": no available IPs

Thank you for your time and response.

**Comment by champtar** [comment] 2020-05-08 22:32
Hi @Cspellz, issue like that are better handled on the slack channel, but in any case show the exact yaml if you want help ;)

**Comment by russellb** [comment] 2020-05-20 18:00
Manual address assignment is working for me with the layer2 mode and metallb 0.9.3.

I set `auto-assign: false` in my address pool config, created a load balancer without an IP, and then observed it get handled properly once I specified the IP to use.

```
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  AllocationFailed  101s  metallb-controller  Failed to allocate IP for "manual-assign-test/manual-assign-test-lb": no available IPs
  Normal   LoadbalancerIP    3s    service-controller  -> 192.168.111.140
  Normal   IPAllocated       3s    metallb-controller  Assigned IP "192.168.111.140"
```

**Comment by russellb** [comment] 2020-06-09 02:54
I'm going to close this since I wasn't able to reproduce it.  If you're still having trouble, please reach out on slack as suggested, or just re-open this issue with more info.  Thanks!

**Closed by russellb** 2020-06-09 02:54 UTC

**Comment by vhosakot** [comment] 2021-02-18 20:59
I see this issue with metallb `v0.8.3` and k8s `v1.18.12`. Metallb did not assign the loadbalancer IP when `auto-assign: false` was set and I saw the error `"error":"no available IPs","msg":"IP allocation failed"` in logs of `metallb-controller` pod.

After `auto-assign: false` was removed, metallb assigned loadbalancer IP as expected.

**Comment by russellb** [comment] 2021-02-18 21:03
can you try the latest release?

**Comment by TheDarkula** [comment] 2023-10-28 18:27
@russellb This just started happening for me.

I have a number of `IPAddressPool`s, all set with `autoAssign: false`.

I have tried creating a new `IPAddressPool` both ways.


I have metallb installed via the following:

```
helm upgrade --install metallb metallb/metallb --namespace metallb-system --version 0.13.12
```

This is all running in K3S version 1.27.4.



I ran the following commands to verify:

```
kubectl create deployment nginx --image=nginx
kubectl annotate deployment nginx ingress.metallb.universe.tf/address-pool=test
kubectl describe deployment nginx
kubectl expose deployment nginx --type=LoadBalancer --port 80
kubectl describe svc nginx
```


This is with `autoAssign` allowed:

```
Events:
  Type    Reason       Age   From                Message
  ----    ------       ----  ----                -------
  Normal  IPAllocated  0s    metallb-controller  Assigned IP ["192.168.1.208"]
```


This is with `autoAssign: false`:

```
Events:
  Type     Reason            Age   From                Message
  ----     ------            ----  ----                -------
  Warning  AllocationFailed  1s    metallb-controller  Failed to allocate IP for "default/nginx": no available IPs
```

**Comment by TheDarkula** [comment] 2023-11-08 23:02
@fedepaol I am not certain who to reach out to, but you seem to be the most active contributor as of recently.
Can I get some eyes on this please?

**Comment by TheDarkula** [comment] 2023-11-10 08:08
I had an error in the way I was doing the annotation.
It should have been:
```
kubectl create deployment nginx --image=nginx
kubectl describe deployment nginx
kubectl expose deployment nginx --type=LoadBalancer --port 80
kubectl annotate service nginx metallb.universe.tf/address-pool=test
kubectl describe svc nginx
```

This actually functions properly.

I may have an issue with a certain helm chart to work out.

Pardon the confusion :)

**Comment by fedepaol** [comment] 2023-11-10 08:36
awesome! And sorry for the delay in replying!

**Comment by TheDarkula** [comment] 2023-11-10 08:39
No worries :)
