### ISSUE TITLE
speaker will announce service LB IP from every nic of node, can it choose only one nic to broadcast arp?

### ISSUE THREAD

**Issue by qingwusunny** [metallb/metallb#1299] opened 2022-03-31 06:41 UTC
speaker will announce service LB IP from every nic of node, can it choose only one nic to broadcast arp?

**Comment by fedepaol** [comment] 2022-03-31 07:13
It's currently not possible. Closing this as duplicate of https://github.com/metallb/metallb/issues/277

**Closed by fedepaol** 2022-03-31 07:13 UTC
